using System;
using System.Collections.Generic;
using System.ComponentModel;
using Content.Shared.Damage;
using Content.Shared.FixedPoint;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;
using Robust.Shared.Serialization.TypeSerializers.Implementations.Custom;

namespace Content.Shared.Atmos.Rotting;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentPause]
[Access(new Type[] { typeof(SharedRottingSystem) })]
public sealed class RottingComponent : Component, ISerializationGenerated<RottingComponent>, ISerializationGenerated
{
	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class RottingComponent_AutoPauseSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<RottingComponent, EntityUnpausedEvent>((ComponentEventRefHandler<RottingComponent, EntityUnpausedEvent>)OnEntityUnpaused, (Type[])null, (Type[])null);
		}

		private void OnEntityUnpaused(EntityUid uid, RottingComponent component, ref EntityUnpausedEvent args)
		{
			component.NextRotUpdate += args.PausedTime;
		}
	}

	[DataField(null, false, 1, false, false, null)]
	public bool DealDamage;

	[DataField(null, false, 1, false, false, typeof(TimeOffsetSerializer))]
	[AutoPausedField]
	public TimeSpan NextRotUpdate = TimeSpan.Zero;

	[DataField(null, false, 1, false, false, null)]
	public TimeSpan RotUpdateRate = TimeSpan.FromSeconds(5L);

	[DataField(null, false, 1, false, false, null)]
	public TimeSpan TotalRotTime = TimeSpan.Zero;

	[DataField(null, false, 1, false, false, null)]
	public DamageSpecifier Damage = new DamageSpecifier
	{
		DamageDict = new Dictionary<string, FixedPoint2>
		{
			{ "Blunt", 0.06 },
			{ "Cellular", 0.06 }
		}
	};

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref RottingComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_00f7: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (RottingComponent)(object)definitionCast;
		if (serialization.TryCustomCopy<RottingComponent>(this, ref target, hookCtx, false, context))
		{
			return;
		}
		bool DealDamageTemp = false;
		if (!serialization.TryCustomCopy<bool>(DealDamage, ref DealDamageTemp, hookCtx, false, context))
		{
			DealDamageTemp = DealDamage;
		}
		target.DealDamage = DealDamageTemp;
		TimeSpan NextRotUpdateTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(NextRotUpdate, ref NextRotUpdateTemp, hookCtx, false, context))
		{
			NextRotUpdateTemp = serialization.CreateCopy<TimeSpan>(NextRotUpdate, hookCtx, context, false);
		}
		target.NextRotUpdate = NextRotUpdateTemp;
		TimeSpan RotUpdateRateTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(RotUpdateRate, ref RotUpdateRateTemp, hookCtx, false, context))
		{
			RotUpdateRateTemp = serialization.CreateCopy<TimeSpan>(RotUpdateRate, hookCtx, context, false);
		}
		target.RotUpdateRate = RotUpdateRateTemp;
		TimeSpan TotalRotTimeTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(TotalRotTime, ref TotalRotTimeTemp, hookCtx, false, context))
		{
			TotalRotTimeTemp = serialization.CreateCopy<TimeSpan>(TotalRotTime, hookCtx, context, false);
		}
		target.TotalRotTime = TotalRotTimeTemp;
		DamageSpecifier DamageTemp = null;
		if (Damage == null)
		{
			throw new NullNotAllowedException();
		}
		if (!serialization.TryCustomCopy<DamageSpecifier>(Damage, ref DamageTemp, hookCtx, false, context))
		{
			if (Damage == null)
			{
				DamageTemp = null;
			}
			else
			{
				serialization.CopyTo<DamageSpecifier>(Damage, ref DamageTemp, hookCtx, context, true);
			}
		}
		target.Damage = DamageTemp;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref RottingComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		RottingComponent cast = (RottingComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		RottingComponent cast = (RottingComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		RottingComponent def = (RottingComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override RottingComponent Instantiate()
	{
		return new RottingComponent();
	}
}
