using System;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;

namespace Content.Shared._RMC14.Requisitions.Components;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(true, false)]
[Access(new Type[] { typeof(SharedRequisitionsSystem) })]
public sealed class RequisitionsGearComponent : Component, ISerializationGenerated<RequisitionsGearComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class RequisitionsGearComponent_AutoState : IComponentState
	{
		public RequisitionsGearMode Mode;

		public string StaticState;

		public string MovingState;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class RequisitionsGearComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<RequisitionsGearComponent, ComponentGetState>((ComponentEventRefHandler<RequisitionsGearComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<RequisitionsGearComponent, ComponentHandleState>((ComponentEventRefHandler<RequisitionsGearComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, RequisitionsGearComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new RequisitionsGearComponent_AutoState
			{
				Mode = component.Mode,
				StaticState = component.StaticState,
				MovingState = component.MovingState
			};
		}

		private void OnHandleState(EntityUid uid, RequisitionsGearComponent component, ref ComponentHandleState args)
		{
			//IL_004c: Unknown result type (might be due to invalid IL or missing references)
			if (((ComponentHandleState)(ref args)).Current is RequisitionsGearComponent_AutoState state)
			{
				component.Mode = state.Mode;
				component.StaticState = state.StaticState;
				component.MovingState = state.MovingState;
				AfterAutoHandleStateEvent ev = default(AfterAutoHandleStateEvent);
				((AfterAutoHandleStateEvent)(ref ev))._002Ector(((ComponentHandleState)(ref args)).Current);
				((IDirectedEventBus)base.EntityManager.EventBus).RaiseComponentEvent<AfterAutoHandleStateEvent, RequisitionsGearComponent>(uid, component, ref ev);
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public RequisitionsGearMode Mode;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public string StaticState = "base";

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public string MovingState = "moving";

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref RequisitionsGearComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_0088: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (RequisitionsGearComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<RequisitionsGearComponent>(this, ref target, hookCtx, false, context))
		{
			RequisitionsGearMode ModeTemp = RequisitionsGearMode.Static;
			if (!serialization.TryCustomCopy<RequisitionsGearMode>(Mode, ref ModeTemp, hookCtx, false, context))
			{
				ModeTemp = Mode;
			}
			target.Mode = ModeTemp;
			string StaticStateTemp = null;
			if (StaticState == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<string>(StaticState, ref StaticStateTemp, hookCtx, false, context))
			{
				StaticStateTemp = StaticState;
			}
			target.StaticState = StaticStateTemp;
			string MovingStateTemp = null;
			if (MovingState == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<string>(MovingState, ref MovingStateTemp, hookCtx, false, context))
			{
				MovingStateTemp = MovingState;
			}
			target.MovingState = MovingStateTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref RequisitionsGearComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		RequisitionsGearComponent cast = (RequisitionsGearComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		RequisitionsGearComponent cast = (RequisitionsGearComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		RequisitionsGearComponent def = (RequisitionsGearComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override RequisitionsGearComponent Instantiate()
	{
		return new RequisitionsGearComponent();
	}
}
