using System;
using System.ComponentModel;
using System.Numerics;
using Content.Shared.Inventory;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.FarSight;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] { typeof(FarSightSystem) })]
public sealed class FarSightItemComponent : Component, IClothingSlots, ISerializationGenerated<FarSightItemComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class FarSightItemComponent_AutoState : IComponentState
	{
		public EntProtoId ActionId;

		public NetEntity? Action;

		public bool Enabled;

		public Vector2 Zoom;

		public SlotFlags Slots;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class FarSightItemComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<FarSightItemComponent, ComponentGetState>((ComponentEventRefHandler<FarSightItemComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<FarSightItemComponent, ComponentHandleState>((ComponentEventRefHandler<FarSightItemComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, FarSightItemComponent component, ref ComponentGetState args)
		{
			//IL_0008: Unknown result type (might be due to invalid IL or missing references)
			//IL_000d: Unknown result type (might be due to invalid IL or missing references)
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new FarSightItemComponent_AutoState
			{
				ActionId = component.ActionId,
				Action = ((EntitySystem)this).GetNetEntity(component.Action, (MetaDataComponent)null),
				Enabled = component.Enabled,
				Zoom = component.Zoom,
				Slots = component.Slots
			};
		}

		private void OnHandleState(EntityUid uid, FarSightItemComponent component, ref ComponentHandleState args)
		{
			//IL_0012: Unknown result type (might be due to invalid IL or missing references)
			//IL_0017: Unknown result type (might be due to invalid IL or missing references)
			//IL_0024: Unknown result type (might be due to invalid IL or missing references)
			if (((ComponentHandleState)(ref args)).Current is FarSightItemComponent_AutoState state)
			{
				component.ActionId = state.ActionId;
				component.Action = ((EntitySystem)this).EnsureEntity<FarSightItemComponent>(state.Action, uid);
				component.Enabled = state.Enabled;
				component.Zoom = state.Zoom;
				component.Slots = state.Slots;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public EntProtoId ActionId = EntProtoId.op_Implicit("RMCActionToggleFarSight");

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public EntityUid? Action;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool Enabled;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public Vector2 Zoom = new Vector2(1.13f, 1.13f);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public SlotFlags Slots { get; set; } = SlotFlags.EYES;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref FarSightItemComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0028: Unknown result type (might be due to invalid IL or missing references)
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_0056: Unknown result type (might be due to invalid IL or missing references)
		//IL_0044: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (FarSightItemComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<FarSightItemComponent>(this, ref target, hookCtx, false, context))
		{
			EntProtoId ActionIdTemp = default(EntProtoId);
			if (!serialization.TryCustomCopy<EntProtoId>(ActionId, ref ActionIdTemp, hookCtx, false, context))
			{
				ActionIdTemp = serialization.CreateCopy<EntProtoId>(ActionId, hookCtx, context, false);
			}
			target.ActionId = ActionIdTemp;
			EntityUid? ActionTemp = null;
			if (!serialization.TryCustomCopy<EntityUid?>(Action, ref ActionTemp, hookCtx, false, context))
			{
				ActionTemp = serialization.CreateCopy<EntityUid?>(Action, hookCtx, context, false);
			}
			target.Action = ActionTemp;
			bool EnabledTemp = false;
			if (!serialization.TryCustomCopy<bool>(Enabled, ref EnabledTemp, hookCtx, false, context))
			{
				EnabledTemp = Enabled;
			}
			target.Enabled = EnabledTemp;
			Vector2 ZoomTemp = default(Vector2);
			if (!serialization.TryCustomCopy<Vector2>(Zoom, ref ZoomTemp, hookCtx, false, context))
			{
				ZoomTemp = serialization.CreateCopy<Vector2>(Zoom, hookCtx, context, false);
			}
			target.Zoom = ZoomTemp;
			SlotFlags SlotsTemp = SlotFlags.NONE;
			if (!serialization.TryCustomCopy<SlotFlags>(Slots, ref SlotsTemp, hookCtx, false, context))
			{
				SlotsTemp = Slots;
			}
			target.Slots = SlotsTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref FarSightItemComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		FarSightItemComponent cast = (FarSightItemComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		FarSightItemComponent cast = (FarSightItemComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		FarSightItemComponent def = (FarSightItemComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override FarSightItemComponent Instantiate()
	{
		return new FarSightItemComponent();
	}
}
