// Decompiled with JetBrains decompiler
// Type: Content.Shared.Remotes.Components.DoorRemoteComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared.Remotes.Components;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
public sealed class DoorRemoteComponent : 
  Component,
  ISerializationGenerated<DoorRemoteComponent>,
  ISerializationGenerated
{
  [AutoNetworkedField]
  [DataField(null, false, 1, false, false, null)]
  public OperatingMode Mode;
  [AutoNetworkedField]
  [DataField(null, false, 1, false, false, null)]
  public bool IncludeUserAccess;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref DoorRemoteComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (DoorRemoteComponent) target1;
    if (serialization.TryCustomCopy<DoorRemoteComponent>(this, ref target, hookCtx, false, context))
      return;
    OperatingMode target2 = OperatingMode.OpenClose;
    if (!serialization.TryCustomCopy<OperatingMode>(this.Mode, ref target2, hookCtx, false, context))
      target2 = this.Mode;
    target.Mode = target2;
    bool target3 = false;
    if (!serialization.TryCustomCopy<bool>(this.IncludeUserAccess, ref target3, hookCtx, false, context))
      target3 = this.IncludeUserAccess;
    target.IncludeUserAccess = target3;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref DoorRemoteComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    DoorRemoteComponent target1 = (DoorRemoteComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    DoorRemoteComponent target1 = (DoorRemoteComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    DoorRemoteComponent target1 = (DoorRemoteComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual DoorRemoteComponent Component.Instantiate() => new DoorRemoteComponent();

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class DoorRemoteComponent_AutoState : IComponentState
  {
    public OperatingMode Mode;
    public bool IncludeUserAccess;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class DoorRemoteComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<DoorRemoteComponent, ComponentGetState>(new ComponentEventRefHandler<DoorRemoteComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<DoorRemoteComponent, ComponentHandleState>(new ComponentEventRefHandler<DoorRemoteComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      DoorRemoteComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new DoorRemoteComponent.DoorRemoteComponent_AutoState()
      {
        Mode = component.Mode,
        IncludeUserAccess = component.IncludeUserAccess
      };
    }

    private void OnHandleState(
      EntityUid uid,
      DoorRemoteComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is DoorRemoteComponent.DoorRemoteComponent_AutoState current))
        return;
      component.Mode = current.Mode;
      component.IncludeUserAccess = current.IncludeUserAccess;
    }
  }
}
