// Decompiled with JetBrains decompiler
// Type: Content.Shared._RMC14.Marines.Squads.SquadSpawnerComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Content.Shared.Roles;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared._RMC14.Marines.Squads;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] {typeof (SquadSystem)})]
public sealed class SquadSpawnerComponent : 
  Component,
  ISerializationGenerated<SquadSpawnerComponent>,
  ISerializationGenerated
{
  [DataField(null, false, 1, true, false, null)]
  [AutoNetworkedField]
  public EntProtoId Squad;
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public ProtoId<JobPrototype>? Role;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref SquadSpawnerComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (SquadSpawnerComponent) target1;
    if (serialization.TryCustomCopy<SquadSpawnerComponent>(this, ref target, hookCtx, false, context))
      return;
    EntProtoId target2 = new EntProtoId();
    if (!serialization.TryCustomCopy<EntProtoId>(this.Squad, ref target2, hookCtx, false, context))
      target2 = serialization.CreateCopy<EntProtoId>(this.Squad, hookCtx, context);
    target.Squad = target2;
    ProtoId<JobPrototype>? target3 = new ProtoId<JobPrototype>?();
    if (!serialization.TryCustomCopy<ProtoId<JobPrototype>?>(this.Role, ref target3, hookCtx, false, context))
      target3 = serialization.CreateCopy<ProtoId<JobPrototype>?>(this.Role, hookCtx, context);
    target.Role = target3;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref SquadSpawnerComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    SquadSpawnerComponent target1 = (SquadSpawnerComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    SquadSpawnerComponent target1 = (SquadSpawnerComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    SquadSpawnerComponent target1 = (SquadSpawnerComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual SquadSpawnerComponent Component.Instantiate() => new SquadSpawnerComponent();

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class SquadSpawnerComponent_AutoState : IComponentState
  {
    public EntProtoId Squad;
    public ProtoId<JobPrototype>? Role;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class SquadSpawnerComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<SquadSpawnerComponent, ComponentGetState>(new ComponentEventRefHandler<SquadSpawnerComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<SquadSpawnerComponent, ComponentHandleState>(new ComponentEventRefHandler<SquadSpawnerComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      SquadSpawnerComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new SquadSpawnerComponent.SquadSpawnerComponent_AutoState()
      {
        Squad = component.Squad,
        Role = component.Role
      };
    }

    private void OnHandleState(
      EntityUid uid,
      SquadSpawnerComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is SquadSpawnerComponent.SquadSpawnerComponent_AutoState current))
        return;
      component.Squad = current.Squad;
      component.Role = current.Role;
    }
  }
}
