// Decompiled with JetBrains decompiler
// Type: Content.Shared._RMC14.Camera.RMCCameraComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared._RMC14.Camera;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] {typeof (SharedRMCCameraSystem)})]
public sealed class RMCCameraComponent : 
  Component,
  ISerializationGenerated<RMCCameraComponent>,
  ISerializationGenerated
{
  [DataField(null, false, 1, true, false, null)]
  [AutoNetworkedField]
  public EntProtoId? Id;
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public bool Rename = true;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref RMCCameraComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (RMCCameraComponent) target1;
    if (serialization.TryCustomCopy<RMCCameraComponent>(this, ref target, hookCtx, false, context))
      return;
    EntProtoId? target2 = new EntProtoId?();
    if (!serialization.TryCustomCopy<EntProtoId?>(this.Id, ref target2, hookCtx, false, context))
      target2 = serialization.CreateCopy<EntProtoId?>(this.Id, hookCtx, context);
    target.Id = target2;
    bool target3 = false;
    if (!serialization.TryCustomCopy<bool>(this.Rename, ref target3, hookCtx, false, context))
      target3 = this.Rename;
    target.Rename = target3;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref RMCCameraComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RMCCameraComponent target1 = (RMCCameraComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RMCCameraComponent target1 = (RMCCameraComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RMCCameraComponent target1 = (RMCCameraComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual RMCCameraComponent Component.Instantiate() => new RMCCameraComponent();

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class RMCCameraComponent_AutoState : IComponentState
  {
    public EntProtoId? Id;
    public bool Rename;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class RMCCameraComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<RMCCameraComponent, ComponentGetState>(new ComponentEventRefHandler<RMCCameraComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<RMCCameraComponent, ComponentHandleState>(new ComponentEventRefHandler<RMCCameraComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      RMCCameraComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new RMCCameraComponent.RMCCameraComponent_AutoState()
      {
        Id = component.Id,
        Rename = component.Rename
      };
    }

    private void OnHandleState(
      EntityUid uid,
      RMCCameraComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is RMCCameraComponent.RMCCameraComponent_AutoState current))
        return;
      component.Id = current.Id;
      component.Rename = current.Rename;
    }
  }
}
