using System;
using System.ComponentModel;
using Content.Shared._PUBG.Weapons.Ranged;
using Content.Shared._RMC14.Xenonids.Projectile;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Map;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.Weapons.Ranged;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[]
{
	typeof(CMGunSystem),
	typeof(XenoProjectileSystem),
	typeof(PubgGunRangeSystem)
})]
public sealed class ProjectileFixedDistanceComponent : Component, ISerializationGenerated<ProjectileFixedDistanceComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ProjectileFixedDistanceComponent_AutoState : IComponentState
	{
		public TimeSpan FlyEndTime;

		public MapCoordinates? TargetCoordinates;

		public bool ArcProj;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ProjectileFixedDistanceComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<ProjectileFixedDistanceComponent, ComponentGetState>((ComponentEventRefHandler<ProjectileFixedDistanceComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<ProjectileFixedDistanceComponent, ComponentHandleState>((ComponentEventRefHandler<ProjectileFixedDistanceComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, ProjectileFixedDistanceComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new ProjectileFixedDistanceComponent_AutoState
			{
				FlyEndTime = component.FlyEndTime,
				TargetCoordinates = component.TargetCoordinates,
				ArcProj = component.ArcProj
			};
		}

		private void OnHandleState(EntityUid uid, ProjectileFixedDistanceComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is ProjectileFixedDistanceComponent_AutoState state)
			{
				component.FlyEndTime = state.FlyEndTime;
				component.TargetCoordinates = state.TargetCoordinates;
				component.ArcProj = state.ArcProj;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan FlyEndTime;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public MapCoordinates? TargetCoordinates;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool ArcProj;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref ProjectileFixedDistanceComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (ProjectileFixedDistanceComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<ProjectileFixedDistanceComponent>(this, ref target, hookCtx, false, context))
		{
			TimeSpan FlyEndTimeTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(FlyEndTime, ref FlyEndTimeTemp, hookCtx, false, context))
			{
				FlyEndTimeTemp = serialization.CreateCopy<TimeSpan>(FlyEndTime, hookCtx, context, false);
			}
			target.FlyEndTime = FlyEndTimeTemp;
			MapCoordinates? TargetCoordinatesTemp = null;
			if (!serialization.TryCustomCopy<MapCoordinates?>(TargetCoordinates, ref TargetCoordinatesTemp, hookCtx, false, context))
			{
				TargetCoordinatesTemp = serialization.CreateCopy<MapCoordinates?>(TargetCoordinates, hookCtx, context, false);
			}
			target.TargetCoordinates = TargetCoordinatesTemp;
			bool ArcProjTemp = false;
			if (!serialization.TryCustomCopy<bool>(ArcProj, ref ArcProjTemp, hookCtx, false, context))
			{
				ArcProjTemp = ArcProj;
			}
			target.ArcProj = ArcProjTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref ProjectileFixedDistanceComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ProjectileFixedDistanceComponent cast = (ProjectileFixedDistanceComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ProjectileFixedDistanceComponent cast = (ProjectileFixedDistanceComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ProjectileFixedDistanceComponent def = (ProjectileFixedDistanceComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override ProjectileFixedDistanceComponent Instantiate()
	{
		return new ProjectileFixedDistanceComponent();
	}
}
