using System;
using System.Collections.Generic;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;

namespace Content.Shared._RMC14.Vehicle.Weapons;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
public sealed class ShellSelectionComponent : Component, ISerializationGenerated<ShellSelectionComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ShellSelectionComponent_AutoState : IComponentState
	{
		public EntProtoId SelectedShellType;

		public List<ShellTypeInfo> AvailableShells;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ShellSelectionComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<ShellSelectionComponent, ComponentGetState>((ComponentEventRefHandler<ShellSelectionComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<ShellSelectionComponent, ComponentHandleState>((ComponentEventRefHandler<ShellSelectionComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, ShellSelectionComponent component, ref ComponentGetState args)
		{
			//IL_0008: Unknown result type (might be due to invalid IL or missing references)
			//IL_000d: Unknown result type (might be due to invalid IL or missing references)
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new ShellSelectionComponent_AutoState
			{
				SelectedShellType = component.SelectedShellType,
				AvailableShells = component.AvailableShells
			};
		}

		private void OnHandleState(EntityUid uid, ShellSelectionComponent component, ref ComponentHandleState args)
		{
			//IL_0012: Unknown result type (might be due to invalid IL or missing references)
			//IL_0017: Unknown result type (might be due to invalid IL or missing references)
			if (((ComponentHandleState)(ref args)).Current is ShellSelectionComponent_AutoState state)
			{
				component.SelectedShellType = state.SelectedShellType;
				component.AvailableShells = ((state.AvailableShells == null) ? null : new List<ShellTypeInfo>(state.AvailableShells));
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public EntProtoId SelectedShellType = EntProtoId.op_Implicit("PUBGVehicleAmmoBoxTankAPFSDS");

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public List<ShellTypeInfo> AvailableShells = new List<ShellTypeInfo>();

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref ShellSelectionComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0028: Unknown result type (might be due to invalid IL or missing references)
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_0056: Unknown result type (might be due to invalid IL or missing references)
		//IL_0044: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_0065: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (ShellSelectionComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<ShellSelectionComponent>(this, ref target, hookCtx, false, context))
		{
			EntProtoId SelectedShellTypeTemp = default(EntProtoId);
			if (!serialization.TryCustomCopy<EntProtoId>(SelectedShellType, ref SelectedShellTypeTemp, hookCtx, false, context))
			{
				SelectedShellTypeTemp = serialization.CreateCopy<EntProtoId>(SelectedShellType, hookCtx, context, false);
			}
			target.SelectedShellType = SelectedShellTypeTemp;
			List<ShellTypeInfo> AvailableShellsTemp = null;
			if (AvailableShells == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<List<ShellTypeInfo>>(AvailableShells, ref AvailableShellsTemp, hookCtx, true, context))
			{
				AvailableShellsTemp = serialization.CreateCopy<List<ShellTypeInfo>>(AvailableShells, hookCtx, context, false);
			}
			target.AvailableShells = AvailableShellsTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref ShellSelectionComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ShellSelectionComponent cast = (ShellSelectionComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ShellSelectionComponent cast = (ShellSelectionComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ShellSelectionComponent def = (ShellSelectionComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override ShellSelectionComponent Instantiate()
	{
		return new ShellSelectionComponent();
	}
}
