// Decompiled with JetBrains decompiler
// Type: Content.Shared._RMC14.Atmos.ExtinguishFireComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Content.Shared.Physics;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared._RMC14.Atmos;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] {typeof (SharedRMCFlammableSystem)})]
public sealed class ExtinguishFireComponent : 
  Component,
  ISerializationGenerated<ExtinguishFireComponent>,
  ISerializationGenerated
{
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public bool Extinguished;
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public CollisionGroup Collision = CollisionGroup.LargeMobLayer | CollisionGroup.Impassable;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref ExtinguishFireComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (ExtinguishFireComponent) target1;
    if (serialization.TryCustomCopy<ExtinguishFireComponent>(this, ref target, hookCtx, false, context))
      return;
    bool target2 = false;
    if (!serialization.TryCustomCopy<bool>(this.Extinguished, ref target2, hookCtx, false, context))
      target2 = this.Extinguished;
    target.Extinguished = target2;
    CollisionGroup target3 = CollisionGroup.None;
    if (!serialization.TryCustomCopy<CollisionGroup>(this.Collision, ref target3, hookCtx, false, context))
      target3 = this.Collision;
    target.Collision = target3;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref ExtinguishFireComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    ExtinguishFireComponent target1 = (ExtinguishFireComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    ExtinguishFireComponent target1 = (ExtinguishFireComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    ExtinguishFireComponent target1 = (ExtinguishFireComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual ExtinguishFireComponent Component.Instantiate() => new ExtinguishFireComponent();

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class ExtinguishFireComponent_AutoState : IComponentState
  {
    public bool Extinguished;
    public CollisionGroup Collision;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class ExtinguishFireComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<ExtinguishFireComponent, ComponentGetState>(new ComponentEventRefHandler<ExtinguishFireComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<ExtinguishFireComponent, ComponentHandleState>(new ComponentEventRefHandler<ExtinguishFireComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      ExtinguishFireComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new ExtinguishFireComponent.ExtinguishFireComponent_AutoState()
      {
        Extinguished = component.Extinguished,
        Collision = component.Collision
      };
    }

    private void OnHandleState(
      EntityUid uid,
      ExtinguishFireComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is ExtinguishFireComponent.ExtinguishFireComponent_AutoState current))
        return;
      component.Extinguished = current.Extinguished;
      component.Collision = current.Collision;
    }
  }
}
