// Decompiled with JetBrains decompiler
// Type: Content.Shared._RMC14.Xenonids.Projectile.XenoProjectileShotComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Player;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared._RMC14.Xenonids.Projectile;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] {typeof (XenoProjectileSystem)})]
public sealed class XenoProjectileShotComponent : 
  Component,
  ISerializationGenerated<XenoProjectileShotComponent>,
  ISerializationGenerated
{
  public ICommonSession? Shooter;
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public int Id;
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public EntityUid? ShooterEnt;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref XenoProjectileShotComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (XenoProjectileShotComponent) target1;
    if (serialization.TryCustomCopy<XenoProjectileShotComponent>(this, ref target, hookCtx, false, context))
      return;
    int target2 = 0;
    if (!serialization.TryCustomCopy<int>(this.Id, ref target2, hookCtx, false, context))
      target2 = this.Id;
    target.Id = target2;
    EntityUid? target3 = new EntityUid?();
    if (!serialization.TryCustomCopy<EntityUid?>(this.ShooterEnt, ref target3, hookCtx, false, context))
      target3 = serialization.CreateCopy<EntityUid?>(this.ShooterEnt, hookCtx, context);
    target.ShooterEnt = target3;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref XenoProjectileShotComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    XenoProjectileShotComponent target1 = (XenoProjectileShotComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    XenoProjectileShotComponent target1 = (XenoProjectileShotComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    XenoProjectileShotComponent target1 = (XenoProjectileShotComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual XenoProjectileShotComponent Component.Instantiate() => new XenoProjectileShotComponent();

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class XenoProjectileShotComponent_AutoState : IComponentState
  {
    public int Id;
    public NetEntity? ShooterEnt;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class XenoProjectileShotComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<XenoProjectileShotComponent, ComponentGetState>(new ComponentEventRefHandler<XenoProjectileShotComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<XenoProjectileShotComponent, ComponentHandleState>(new ComponentEventRefHandler<XenoProjectileShotComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      XenoProjectileShotComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new XenoProjectileShotComponent.XenoProjectileShotComponent_AutoState()
      {
        Id = component.Id,
        ShooterEnt = this.GetNetEntity(component.ShooterEnt)
      };
    }

    private void OnHandleState(
      EntityUid uid,
      XenoProjectileShotComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is XenoProjectileShotComponent.XenoProjectileShotComponent_AutoState current))
        return;
      component.Id = current.Id;
      component.ShooterEnt = this.EnsureEntity<XenoProjectileShotComponent>(current.ShooterEnt, uid);
    }
  }
}
