// Decompiled with JetBrains decompiler
// Type: Content.Shared._RMC14.Medical.Surgery.Effects.Step.RMCSurgeryStepSpawnEffectComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared._RMC14.Medical.Surgery.Effects.Step;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] {typeof (SharedCMSurgerySystem)})]
public sealed class RMCSurgeryStepSpawnEffectComponent : 
  Component,
  ISerializationGenerated<RMCSurgeryStepSpawnEffectComponent>,
  ISerializationGenerated
{
  [DataField(null, false, 1, true, false, null)]
  [AutoNetworkedField]
  public EntProtoId Entity;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref RMCSurgeryStepSpawnEffectComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (RMCSurgeryStepSpawnEffectComponent) target1;
    if (serialization.TryCustomCopy<RMCSurgeryStepSpawnEffectComponent>(this, ref target, hookCtx, false, context))
      return;
    EntProtoId target2 = new EntProtoId();
    if (!serialization.TryCustomCopy<EntProtoId>(this.Entity, ref target2, hookCtx, false, context))
      target2 = serialization.CreateCopy<EntProtoId>(this.Entity, hookCtx, context);
    target.Entity = target2;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref RMCSurgeryStepSpawnEffectComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RMCSurgeryStepSpawnEffectComponent target1 = (RMCSurgeryStepSpawnEffectComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RMCSurgeryStepSpawnEffectComponent target1 = (RMCSurgeryStepSpawnEffectComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RMCSurgeryStepSpawnEffectComponent target1 = (RMCSurgeryStepSpawnEffectComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual RMCSurgeryStepSpawnEffectComponent Component.Instantiate()
  {
    return new RMCSurgeryStepSpawnEffectComponent();
  }

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class RMCSurgeryStepSpawnEffectComponent_AutoState : IComponentState
  {
    public EntProtoId Entity;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class RMCSurgeryStepSpawnEffectComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<RMCSurgeryStepSpawnEffectComponent, ComponentGetState>(new ComponentEventRefHandler<RMCSurgeryStepSpawnEffectComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<RMCSurgeryStepSpawnEffectComponent, ComponentHandleState>(new ComponentEventRefHandler<RMCSurgeryStepSpawnEffectComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      RMCSurgeryStepSpawnEffectComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new RMCSurgeryStepSpawnEffectComponent.RMCSurgeryStepSpawnEffectComponent_AutoState()
      {
        Entity = component.Entity
      };
    }

    private void OnHandleState(
      EntityUid uid,
      RMCSurgeryStepSpawnEffectComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is RMCSurgeryStepSpawnEffectComponent.RMCSurgeryStepSpawnEffectComponent_AutoState current))
        return;
      component.Entity = current.Entity;
    }
  }
}
