using System;
using System.Numerics;
using CompiledRobustXaml;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML.Proxy;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
[XamlMetadata("resm:Content.Client.Cargo.UI.CargoPalletMenu.xaml?assembly=Content.Client", "Content.Client.Cargo.UI.CargoPalletMenu.xaml", "<controls:FancyWindow xmlns=\"https://spacestation14.io\"\r\n                      xmlns:controls=\"clr-namespace:Content.Client.UserInterface.Controls\"\r\n            SetSize=\"300 150\"\r\n            MinSize=\"300 150\"\r\n                      Title=\"{Loc 'cargo-pallet-console-menu-title'}\">\r\n    <BoxContainer Orientation=\"Vertical\" Margin=\"5\">\r\n        <BoxContainer Orientation=\"Horizontal\">\r\n            <Label Text=\"{Loc 'cargo-pallet-menu-appraisal-label'}\"\r\n                   StyleClasses=\"LabelKeyText\" />\r\n            <Label Name=\"AppraisalLabel\"\r\n                   Text=\"{Loc 'cargo-pallet-menu-no-goods-text'}\" />\r\n        </BoxContainer>\r\n        <BoxContainer Orientation=\"Horizontal\">\r\n            <Label Text=\"{Loc 'cargo-pallet-menu-count-label'}\"\r\n                   StyleClasses=\"LabelKeyText\" />\r\n            <Label Name=\"CountLabel\"\r\n                   Text=\"{Loc 'cargo-pallet-menu-no-goods-text'}\" />\r\n        </BoxContainer>\r\n        <Button Name=\"AppraiseButton\"\r\n                Text=\"{Loc 'cargo-pallet-appraise-button'}\"/>\r\n        <Button Name=\"SellButton\"\r\n                Text=\"{Loc 'cargo-pallet-sell-button'}\"/>\r\n        <TextureButton VerticalExpand=\"True\" />\r\n    </BoxContainer>\r\n</controls:FancyWindow>\r\n")]
public sealed class CargoPalletMenu : FancyWindow
{
	public Action? SellRequested;

	public Action? AppraiseRequested;

	private Label AppraisalLabel => ((Control)this).FindControl<Label>("AppraisalLabel");

	private Label CountLabel => ((Control)this).FindControl<Label>("CountLabel");

	private Button AppraiseButton => ((Control)this).FindControl<Button>("AppraiseButton");

	private Button SellButton => ((Control)this).FindControl<Button>("SellButton");

	public CargoPalletMenu()
	{
		_0021XamlIlPopulateTrampoline(this);
		((BaseButton)SellButton).OnPressed += OnSellPressed;
		((BaseButton)AppraiseButton).OnPressed += OnAppraisePressed;
	}

	public void SetAppraisal(int amount)
	{
		AppraisalLabel.Text = Loc.GetString("cargo-console-menu-points-amount", new(string, object)[1] { ("amount", amount.ToString()) });
	}

	public void SetCount(int count)
	{
		CountLabel.Text = count.ToString();
	}

	public void SetEnabled(bool enabled)
	{
		((BaseButton)AppraiseButton).Disabled = !enabled;
		((BaseButton)SellButton).Disabled = !enabled;
	}

	private void OnSellPressed(ButtonEventArgs obj)
	{
		SellRequested?.Invoke();
	}

	private void OnAppraisePressed(ButtonEventArgs obj)
	{
		AppraiseRequested?.Invoke();
	}

	public static void Populate_003AContent_002EClient_002ECargo_002EUI_002ECargoPalletMenu_002Examl(IServiceProvider P_0, FancyWindow P_1)
	{
		//IL_0056: Unknown result type (might be due to invalid IL or missing references)
		//IL_005b: Unknown result type (might be due to invalid IL or missing references)
		//IL_006c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0071: Unknown result type (might be due to invalid IL or missing references)
		//IL_0072: Unknown result type (might be due to invalid IL or missing references)
		//IL_007d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0092: Unknown result type (might be due to invalid IL or missing references)
		//IL_009c: Unknown result type (might be due to invalid IL or missing references)
		//IL_009d: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a3: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ae: Unknown result type (might be due to invalid IL or missing references)
		//IL_00af: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b4: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00bb: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ec: Expected O, but got Unknown
		//IL_00fa: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ff: Unknown result type (might be due to invalid IL or missing references)
		//IL_0100: Unknown result type (might be due to invalid IL or missing references)
		//IL_0101: Unknown result type (might be due to invalid IL or missing references)
		//IL_0110: Expected O, but got Unknown
		//IL_012c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0131: Unknown result type (might be due to invalid IL or missing references)
		//IL_0146: Expected O, but got Unknown
		//IL_0158: Expected O, but got Unknown
		//IL_0166: Unknown result type (might be due to invalid IL or missing references)
		//IL_0167: Unknown result type (might be due to invalid IL or missing references)
		//IL_016c: Unknown result type (might be due to invalid IL or missing references)
		//IL_016d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0178: Unknown result type (might be due to invalid IL or missing references)
		//IL_0179: Unknown result type (might be due to invalid IL or missing references)
		//IL_017e: Unknown result type (might be due to invalid IL or missing references)
		//IL_017f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0185: Unknown result type (might be due to invalid IL or missing references)
		//IL_018a: Unknown result type (might be due to invalid IL or missing references)
		//IL_01b6: Expected O, but got Unknown
		//IL_01c4: Unknown result type (might be due to invalid IL or missing references)
		//IL_01c9: Unknown result type (might be due to invalid IL or missing references)
		//IL_01ca: Unknown result type (might be due to invalid IL or missing references)
		//IL_01cb: Unknown result type (might be due to invalid IL or missing references)
		//IL_01da: Expected O, but got Unknown
		//IL_01f6: Unknown result type (might be due to invalid IL or missing references)
		//IL_01fb: Unknown result type (might be due to invalid IL or missing references)
		//IL_0210: Expected O, but got Unknown
		//IL_0222: Expected O, but got Unknown
		//IL_0230: Unknown result type (might be due to invalid IL or missing references)
		//IL_0231: Unknown result type (might be due to invalid IL or missing references)
		//IL_0236: Unknown result type (might be due to invalid IL or missing references)
		//IL_0237: Unknown result type (might be due to invalid IL or missing references)
		//IL_0238: Unknown result type (might be due to invalid IL or missing references)
		//IL_0247: Expected O, but got Unknown
		//IL_0263: Unknown result type (might be due to invalid IL or missing references)
		//IL_0268: Unknown result type (might be due to invalid IL or missing references)
		//IL_027d: Expected O, but got Unknown
		//IL_028b: Unknown result type (might be due to invalid IL or missing references)
		//IL_028c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0291: Unknown result type (might be due to invalid IL or missing references)
		//IL_0292: Unknown result type (might be due to invalid IL or missing references)
		//IL_0293: Unknown result type (might be due to invalid IL or missing references)
		//IL_02a2: Expected O, but got Unknown
		//IL_02be: Unknown result type (might be due to invalid IL or missing references)
		//IL_02c3: Unknown result type (might be due to invalid IL or missing references)
		//IL_02d8: Expected O, but got Unknown
		//IL_02e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_02eb: Unknown result type (might be due to invalid IL or missing references)
		//IL_02fa: Expected O, but got Unknown
		//IL_030c: Expected O, but got Unknown
		XamlIlContext.Context<FancyWindow> context = new XamlIlContext.Context<FancyWindow>(P_0, null, "resm:Content.Client.Cargo.UI.CargoPalletMenu.xaml?assembly=Content.Client");
		context.RootObject = P_1;
		context.IntermediateRoot = P_1;
		((Control)P_1).SetSize = new Vector2(300f, 150f);
		((Control)P_1).MinSize = new Vector2(300f, 150f);
		P_1.Title = (string)new LocExtension("cargo-pallet-console-menu-title").ProvideValue();
		BoxContainer val = new BoxContainer();
		val.Orientation = (LayoutOrientation)1;
		((Control)val).Margin = new Thickness(5f, 5f, 5f, 5f);
		BoxContainer val2 = new BoxContainer();
		val2.Orientation = (LayoutOrientation)0;
		Label val3 = new Label();
		val3.Text = (string)new LocExtension("cargo-pallet-menu-appraisal-label").ProvideValue();
		string item = "LabelKeyText";
		((Control)val3).StyleClasses.Add(item);
		Control item2 = (Control)val3;
		((Control)val2).XamlChildren.Add(item2);
		Label val4 = new Label();
		((Control)val4).Name = "AppraisalLabel";
		item2 = (Control)val4;
		context.RobustNameScope.Register("AppraisalLabel", item2);
		val4.Text = (string)new LocExtension("cargo-pallet-menu-no-goods-text").ProvideValue();
		item2 = (Control)val4;
		((Control)val2).XamlChildren.Add(item2);
		item2 = (Control)val2;
		((Control)val).XamlChildren.Add(item2);
		BoxContainer val5 = new BoxContainer();
		val5.Orientation = (LayoutOrientation)0;
		Label val6 = new Label();
		val6.Text = (string)new LocExtension("cargo-pallet-menu-count-label").ProvideValue();
		item = "LabelKeyText";
		((Control)val6).StyleClasses.Add(item);
		item2 = (Control)val6;
		((Control)val5).XamlChildren.Add(item2);
		Label val7 = new Label();
		((Control)val7).Name = "CountLabel";
		item2 = (Control)val7;
		context.RobustNameScope.Register("CountLabel", item2);
		val7.Text = (string)new LocExtension("cargo-pallet-menu-no-goods-text").ProvideValue();
		item2 = (Control)val7;
		((Control)val5).XamlChildren.Add(item2);
		item2 = (Control)val5;
		((Control)val).XamlChildren.Add(item2);
		Button val8 = new Button();
		((Control)val8).Name = "AppraiseButton";
		item2 = (Control)val8;
		context.RobustNameScope.Register("AppraiseButton", item2);
		val8.Text = (string)new LocExtension("cargo-pallet-appraise-button").ProvideValue();
		item2 = (Control)val8;
		((Control)val).XamlChildren.Add(item2);
		Button val9 = new Button();
		((Control)val9).Name = "SellButton";
		item2 = (Control)val9;
		context.RobustNameScope.Register("SellButton", item2);
		val9.Text = (string)new LocExtension("cargo-pallet-sell-button").ProvideValue();
		item2 = (Control)val9;
		((Control)val).XamlChildren.Add(item2);
		item2 = (Control)new TextureButton
		{
			VerticalExpand = true
		};
		((Control)val).XamlChildren.Add(item2);
		item2 = (Control)val;
		((Control)P_1).XamlChildren.Add(item2);
		if ((item2 = (Control)(object)((P_1 is Control) ? P_1 : null)) != null)
		{
			context.RobustNameScope.Absorb(item2.NameScope);
			item2.NameScope = context.RobustNameScope;
		}
		context.RobustNameScope.Complete();
	}

	private static void _0021XamlIlPopulateTrampoline(CargoPalletMenu P_0)
	{
		if (!IoCManager.Resolve<IXamlProxyHelper>().Populate(typeof(CargoPalletMenu), (object)P_0))
		{
			Populate_003AContent_002EClient_002ECargo_002EUI_002ECargoPalletMenu_002Examl(null, P_0);
		}
	}
}
