using System;
using System.Numerics;
using CompiledRobustXaml;
using Content.Client.Paper.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML.Proxy;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client.Tips;

[GenerateTypedNameReferences]
[XamlMetadata("resm:Content.Client.Tips.TippyUI.xaml?assembly=Content.Client", "Content.Client.Tips.TippyUI.xaml", "<tips:TippyUI xmlns=\"https://spacestation14.io\"\r\n               xmlns:tips=\"clr-namespace:Content.Client.Tips\"\r\n               MinSize=\"64 64\"\r\n               Visible=\"False\">\r\n    <PanelContainer Name=\"LabelPanel\" Access=\"Public\" Visible=\"False\" MaxWidth=\"300\" MaxHeight=\"200\">\r\n        <ScrollContainer Name=\"ScrollingContents\" HorizontalAlignment=\"Stretch\" VerticalAlignment=\"Stretch\" HorizontalExpand=\"True\" VerticalExpand=\"True\" HScrollEnabled=\"False\" ReturnMeasure=\"True\">\r\n            <RichTextLabel Name=\"Label\" Access=\"Public\"/>\r\n        </ScrollContainer>\r\n    </PanelContainer>\r\n    <SpriteView Name=\"Entity\" Access=\"Public\" MinSize=\"128 128\"/>\r\n</tips:TippyUI>\r\n")]
public sealed class TippyUI : UIWidget
{
	public enum TippyState : byte
	{
		Hidden,
		Revealing,
		Speaking,
		Hiding
	}

	public TippyState State;

	public bool ModifyLayers = true;

	public PanelContainer LabelPanel => ((Control)this).FindControl<PanelContainer>("LabelPanel");

	private ScrollContainer ScrollingContents => ((Control)this).FindControl<ScrollContainer>("ScrollingContents");

	public RichTextLabel Label => ((Control)this).FindControl<RichTextLabel>("Label");

	public SpriteView Entity => ((Control)this).FindControl<SpriteView>("Entity");

	public TippyUI()
	{
		_0021XamlIlPopulateTrampoline(this);
	}

	public void InitLabel(PaperVisualsComponent? visuals, IResourceCache resCache)
	{
		//IL_000b: Unknown result type (might be due to invalid IL or missing references)
		//IL_002a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0053: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_005a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0061: Unknown result type (might be due to invalid IL or missing references)
		//IL_0066: Unknown result type (might be due to invalid IL or missing references)
		//IL_0072: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Unknown result type (might be due to invalid IL or missing references)
		//IL_007f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0085: Unknown result type (might be due to invalid IL or missing references)
		//IL_0086: Unknown result type (might be due to invalid IL or missing references)
		//IL_0091: Unknown result type (might be due to invalid IL or missing references)
		//IL_0092: Unknown result type (might be due to invalid IL or missing references)
		//IL_009d: Unknown result type (might be due to invalid IL or missing references)
		//IL_009e: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00aa: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ba: Expected O, but got Unknown
		if (visuals != null)
		{
			((Control)Label).ModulateSelfOverride = visuals.FontAccentColor;
			if (visuals.BackgroundImagePath != null)
			{
				((Control)LabelPanel).ModulateSelfOverride = visuals.BackgroundModulate;
				TextureResource resource = resCache.GetResource<TextureResource>(visuals.BackgroundImagePath, true);
				StretchMode mode = (StretchMode)(visuals.BackgroundImageTile ? 1 : 0);
				Box2 backgroundPatchMargin = visuals.BackgroundPatchMargin;
				LabelPanel.PanelOverride = (StyleBox)new StyleBoxTexture
				{
					Texture = TextureResource.op_Implicit(resource),
					TextureScale = visuals.BackgroundScale,
					Mode = mode,
					PatchMarginLeft = backgroundPatchMargin.Left,
					PatchMarginBottom = backgroundPatchMargin.Bottom,
					PatchMarginRight = backgroundPatchMargin.Right,
					PatchMarginTop = backgroundPatchMargin.Top
				};
			}
		}
	}

	public static void Populate_003AContent_002EClient_002ETips_002ETippyUI_002Examl(IServiceProvider P_0, TippyUI P_1)
	{
		//IL_0047: Unknown result type (might be due to invalid IL or missing references)
		//IL_004c: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		//IL_004e: Unknown result type (might be due to invalid IL or missing references)
		//IL_005d: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_0084: Unknown result type (might be due to invalid IL or missing references)
		//IL_008f: Unknown result type (might be due to invalid IL or missing references)
		//IL_009a: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00aa: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ab: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Unknown result type (might be due to invalid IL or missing references)
		//IL_00bb: Expected O, but got Unknown
		//IL_00d2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00dd: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e8: Unknown result type (might be due to invalid IL or missing references)
		//IL_00f3: Unknown result type (might be due to invalid IL or missing references)
		//IL_00fe: Unknown result type (might be due to invalid IL or missing references)
		//IL_0109: Unknown result type (might be due to invalid IL or missing references)
		//IL_0114: Unknown result type (might be due to invalid IL or missing references)
		//IL_0119: Unknown result type (might be due to invalid IL or missing references)
		//IL_011a: Unknown result type (might be due to invalid IL or missing references)
		//IL_011b: Unknown result type (might be due to invalid IL or missing references)
		//IL_012a: Expected O, but got Unknown
		//IL_0154: Expected O, but got Unknown
		//IL_0166: Expected O, but got Unknown
		//IL_0178: Expected O, but got Unknown
		//IL_0186: Unknown result type (might be due to invalid IL or missing references)
		//IL_018b: Unknown result type (might be due to invalid IL or missing references)
		//IL_018c: Unknown result type (might be due to invalid IL or missing references)
		//IL_018d: Unknown result type (might be due to invalid IL or missing references)
		//IL_019c: Expected O, but got Unknown
		//IL_01b3: Unknown result type (might be due to invalid IL or missing references)
		//IL_01db: Expected O, but got Unknown
		XamlIlContext.Context<TippyUI> context = new XamlIlContext.Context<TippyUI>(P_0, null, "resm:Content.Client.Tips.TippyUI.xaml?assembly=Content.Client");
		context.RootObject = P_1;
		context.IntermediateRoot = P_1;
		((Control)P_1).MinSize = new Vector2(64f, 64f);
		((Control)P_1).Visible = false;
		PanelContainer val = new PanelContainer();
		((Control)val).Name = "LabelPanel";
		Control val2 = (Control)val;
		context.RobustNameScope.Register("LabelPanel", val2);
		((Control)val).Access = (AccessLevel)0;
		((Control)val).Visible = false;
		((Control)val).MaxWidth = 300f;
		((Control)val).MaxHeight = 200f;
		ScrollContainer val3 = new ScrollContainer();
		((Control)val3).Name = "ScrollingContents";
		val2 = (Control)val3;
		context.RobustNameScope.Register("ScrollingContents", val2);
		((Control)val3).HorizontalAlignment = (HAlignment)0;
		((Control)val3).VerticalAlignment = (VAlignment)0;
		((Control)val3).HorizontalExpand = true;
		((Control)val3).VerticalExpand = true;
		val3.HScrollEnabled = false;
		val3.ReturnMeasure = true;
		RichTextLabel val4 = new RichTextLabel();
		((Control)val4).Name = "Label";
		val2 = (Control)val4;
		context.RobustNameScope.Register("Label", val2);
		((Control)val4).Access = (AccessLevel)0;
		val2 = (Control)val4;
		((Control)val3).XamlChildren.Add(val2);
		val2 = (Control)val3;
		((Control)val).XamlChildren.Add(val2);
		val2 = (Control)val;
		((Control)P_1).XamlChildren.Add(val2);
		SpriteView val5 = new SpriteView();
		((Control)val5).Name = "Entity";
		val2 = (Control)val5;
		context.RobustNameScope.Register("Entity", val2);
		((Control)val5).Access = (AccessLevel)0;
		((Control)val5).MinSize = new Vector2(128f, 128f);
		val2 = (Control)val5;
		((Control)P_1).XamlChildren.Add(val2);
		if ((val2 = (Control)(object)((P_1 is Control) ? P_1 : null)) != null)
		{
			context.RobustNameScope.Absorb(val2.NameScope);
			val2.NameScope = context.RobustNameScope;
		}
		context.RobustNameScope.Complete();
	}

	private static void _0021XamlIlPopulateTrampoline(TippyUI P_0)
	{
		if (!IoCManager.Resolve<IXamlProxyHelper>().Populate(typeof(TippyUI), (object)P_0))
		{
			Populate_003AContent_002EClient_002ETips_002ETippyUI_002Examl(null, P_0);
		}
	}
}
