using System;
using System.ComponentModel;
using Content.Shared.FixedPoint;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.TypeSerializers.Implementations.Custom;

namespace Content.Shared._RMC14.Xenonids.Heal;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[AutoGenerateComponentPause]
[Access(new Type[] { typeof(SharedXenoHealSystem) })]
public sealed class XenoHealComponent : Component, ISerializationGenerated<XenoHealComponent>, ISerializationGenerated
{
	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoHealComponent_AutoPauseSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<XenoHealComponent, EntityUnpausedEvent>((ComponentEventRefHandler<XenoHealComponent, EntityUnpausedEvent>)OnEntityUnpaused, (Type[])null, (Type[])null);
		}

		private void OnEntityUnpaused(EntityUid uid, XenoHealComponent component, ref EntityUnpausedEvent args)
		{
			//IL_0018: Unknown result type (might be due to invalid IL or missing references)
			component.NextHeal += args.PausedTime;
			((EntitySystem)this).Dirty(uid, (IComponent)(object)component, (MetaDataComponent)null);
		}
	}

	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoHealComponent_AutoState : IComponentState
	{
		public EntProtoId? HealEffect;

		public int Radius;

		public FixedPoint2 Percentage;

		public TimeSpan Duration;

		public TimeSpan TimeBetweenHeals;

		public TimeSpan NextHeal;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoHealComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<XenoHealComponent, ComponentGetState>((ComponentEventRefHandler<XenoHealComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<XenoHealComponent, ComponentHandleState>((ComponentEventRefHandler<XenoHealComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, XenoHealComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new XenoHealComponent_AutoState
			{
				HealEffect = component.HealEffect,
				Radius = component.Radius,
				Percentage = component.Percentage,
				Duration = component.Duration,
				TimeBetweenHeals = component.TimeBetweenHeals,
				NextHeal = component.NextHeal
			};
		}

		private void OnHandleState(EntityUid uid, XenoHealComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is XenoHealComponent_AutoState state)
			{
				component.HealEffect = state.HealEffect;
				component.Radius = state.Radius;
				component.Percentage = state.Percentage;
				component.Duration = state.Duration;
				component.TimeBetweenHeals = state.TimeBetweenHeals;
				component.NextHeal = state.NextHeal;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public EntProtoId? HealEffect = EntProtoId.op_Implicit("RMCEffectHealQueen");

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public int Radius = 4;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public FixedPoint2 Percentage = 0.3;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan Duration = TimeSpan.FromSeconds(20L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan TimeBetweenHeals = TimeSpan.FromSeconds(2L);

	[DataField(null, false, 1, false, false, typeof(TimeOffsetSerializer))]
	[AutoNetworkedField]
	[AutoPausedField]
	public TimeSpan NextHeal;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref XenoHealComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (XenoHealComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<XenoHealComponent>(this, ref target, hookCtx, false, context))
		{
			EntProtoId? HealEffectTemp = null;
			if (!serialization.TryCustomCopy<EntProtoId?>(HealEffect, ref HealEffectTemp, hookCtx, false, context))
			{
				HealEffectTemp = serialization.CreateCopy<EntProtoId?>(HealEffect, hookCtx, context, false);
			}
			target.HealEffect = HealEffectTemp;
			int RadiusTemp = 0;
			if (!serialization.TryCustomCopy<int>(Radius, ref RadiusTemp, hookCtx, false, context))
			{
				RadiusTemp = Radius;
			}
			target.Radius = RadiusTemp;
			FixedPoint2 PercentageTemp = default(FixedPoint2);
			if (!serialization.TryCustomCopy<FixedPoint2>(Percentage, ref PercentageTemp, hookCtx, false, context))
			{
				PercentageTemp = serialization.CreateCopy<FixedPoint2>(Percentage, hookCtx, context, false);
			}
			target.Percentage = PercentageTemp;
			TimeSpan DurationTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(Duration, ref DurationTemp, hookCtx, false, context))
			{
				DurationTemp = serialization.CreateCopy<TimeSpan>(Duration, hookCtx, context, false);
			}
			target.Duration = DurationTemp;
			TimeSpan TimeBetweenHealsTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(TimeBetweenHeals, ref TimeBetweenHealsTemp, hookCtx, false, context))
			{
				TimeBetweenHealsTemp = serialization.CreateCopy<TimeSpan>(TimeBetweenHeals, hookCtx, context, false);
			}
			target.TimeBetweenHeals = TimeBetweenHealsTemp;
			TimeSpan NextHealTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(NextHeal, ref NextHealTemp, hookCtx, false, context))
			{
				NextHealTemp = serialization.CreateCopy<TimeSpan>(NextHeal, hookCtx, context, false);
			}
			target.NextHeal = NextHealTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref XenoHealComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoHealComponent cast = (XenoHealComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoHealComponent cast = (XenoHealComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoHealComponent def = (XenoHealComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override XenoHealComponent Instantiate()
	{
		return new XenoHealComponent();
	}
}
