using System;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Localization;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.Xenonids.Strain;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] { typeof(XenoStrainSystem) })]
public sealed class XenoStrainComponent : Component, ISerializationGenerated<XenoStrainComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoStrainComponent_AutoState : IComponentState
	{
		public LocId Name;

		public LocId? Description;

		public LocId? Popup;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoStrainComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<XenoStrainComponent, ComponentGetState>((ComponentEventRefHandler<XenoStrainComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<XenoStrainComponent, ComponentHandleState>((ComponentEventRefHandler<XenoStrainComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, XenoStrainComponent component, ref ComponentGetState args)
		{
			//IL_0008: Unknown result type (might be due to invalid IL or missing references)
			//IL_000d: Unknown result type (might be due to invalid IL or missing references)
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new XenoStrainComponent_AutoState
			{
				Name = component.Name,
				Description = component.Description,
				Popup = component.Popup
			};
		}

		private void OnHandleState(EntityUid uid, XenoStrainComponent component, ref ComponentHandleState args)
		{
			//IL_0012: Unknown result type (might be due to invalid IL or missing references)
			//IL_0017: Unknown result type (might be due to invalid IL or missing references)
			if (((ComponentHandleState)(ref args)).Current is XenoStrainComponent_AutoState state)
			{
				component.Name = state.Name;
				component.Description = state.Description;
				component.Popup = state.Popup;
			}
		}
	}

	[DataField(null, false, 1, true, false, null)]
	[AutoNetworkedField]
	public LocId Name = LocId.op_Implicit(string.Empty);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? Description;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? Popup;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref XenoStrainComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0028: Unknown result type (might be due to invalid IL or missing references)
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_0056: Unknown result type (might be due to invalid IL or missing references)
		//IL_0044: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (XenoStrainComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<XenoStrainComponent>(this, ref target, hookCtx, false, context))
		{
			LocId NameTemp = default(LocId);
			if (!serialization.TryCustomCopy<LocId>(Name, ref NameTemp, hookCtx, false, context))
			{
				NameTemp = serialization.CreateCopy<LocId>(Name, hookCtx, context, false);
			}
			target.Name = NameTemp;
			LocId? DescriptionTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(Description, ref DescriptionTemp, hookCtx, false, context))
			{
				DescriptionTemp = serialization.CreateCopy<LocId?>(Description, hookCtx, context, false);
			}
			target.Description = DescriptionTemp;
			LocId? PopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(Popup, ref PopupTemp, hookCtx, false, context))
			{
				PopupTemp = serialization.CreateCopy<LocId?>(Popup, hookCtx, context, false);
			}
			target.Popup = PopupTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref XenoStrainComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoStrainComponent cast = (XenoStrainComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoStrainComponent cast = (XenoStrainComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoStrainComponent def = (XenoStrainComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override XenoStrainComponent Instantiate()
	{
		return new XenoStrainComponent();
	}
}
