// Decompiled with JetBrains decompiler
// Type: Content.Client.StationRecords.GeneralRecord
// Assembly: Content.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B4469588-B038-4783-B6EC-1EFF6592A364
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Client.dll

using CompiledRobustXaml;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML.Proxy;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using System;
using System.Runtime.InteropServices;

#nullable enable
namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
[XamlMetadata("resm:Content.Client.StationRecords.GeneralRecord.xaml?assembly=Content.Client", "Content.Client.StationRecords.GeneralRecord.xaml", "<Control xmlns=\"https://spacestation14.io\">\r\n    <BoxContainer Orientation=\"Vertical\" Margin=\"5\">\r\n        <Label Name=\"RecordName\" StyleClasses=\"LabelBig\"/>\r\n        <Label Name=\"Age\"/>\r\n        <Label Name=\"Title\"/>\r\n        <Label Name=\"Job\"/>\r\n        <Label Name=\"Species\"/>\r\n        <Label Name=\"Gender\"/>\r\n        <Label Name=\"Fingerprint\"/>\r\n        <Label Name=\"Dna\"/>\r\n        <Button Visible=\"False\" Name=\"DeleteButton\" Text=\"{Loc 'general-station-record-console-delete'}\"/>\r\n    </BoxContainer>\r\n</Control>\r\n")]
public sealed class GeneralRecord : Control
{
  public Action<uint>? OnDeletePressed;

  public GeneralRecord(GeneralStationRecord record, bool canDelete, uint? id)
  {
    GeneralRecord generalRecord = this;
    GeneralRecord.\u0021XamlIlPopulateTrampoline(this);
    this.RecordName.Text = record.Name;
    this.Age.Text = Loc.GetString("general-station-record-console-record-age", new (string, object)[1]
    {
      ("age", (object) record.Age.ToString())
    });
    this.Title.Text = Loc.GetString("general-station-record-console-record-title", new (string, object)[1]
    {
      ("job", (object) Loc.GetString(record.JobTitle))
    });
    this.Species.Text = Loc.GetString("general-station-record-console-record-species", new (string, object)[1]
    {
      ("species", (object) record.Species)
    });
    this.Gender.Text = Loc.GetString("general-station-record-console-record-gender", new (string, object)[1]
    {
      ("gender", (object) record.Gender.ToString())
    });
    this.Fingerprint.Text = Loc.GetString("general-station-record-console-record-fingerprint", new (string, object)[1]
    {
      ("fingerprint", (object) (record.Fingerprint ?? Loc.GetString("generic-not-available-shorthand")))
    });
    this.Dna.Text = Loc.GetString("general-station-record-console-record-dna", new (string, object)[1]
    {
      ("dna", (object) (record.DNA ?? Loc.GetString("generic-not-available-shorthand")))
    });
    if (!canDelete || !id.HasValue)
      return;
    ((Control) this.DeleteButton).Visible = true;
    ((BaseButton) this.DeleteButton).OnPressed += (Action<BaseButton.ButtonEventArgs>) (_ =>
    {
      Action<uint> onDeletePressed = generalRecord.OnDeletePressed;
      if (onDeletePressed == null)
        return;
      onDeletePressed(id.Value);
    });
  }

  private 
  #nullable disable
  Label RecordName => this.FindControl<Label>(nameof (RecordName));

  private Label Age => this.FindControl<Label>(nameof (Age));

  private Label Title => this.FindControl<Label>(nameof (Title));

  private Label Job => this.FindControl<Label>(nameof (Job));

  private Label Species => this.FindControl<Label>(nameof (Species));

  private Label Gender => this.FindControl<Label>(nameof (Gender));

  private Label Fingerprint => this.FindControl<Label>(nameof (Fingerprint));

  private Label Dna => this.FindControl<Label>(nameof (Dna));

  private Button DeleteButton => this.FindControl<Button>(nameof (DeleteButton));

  public static void Populate\u003AContent\u002EClient\u002EStationRecords\u002EGeneralRecord\u002Examl(
    [In] IServiceProvider obj0,
    [In] Control obj1)
  {
    XamlIlContext.Context<Control> context = new XamlIlContext.Context<Control>(obj0, (object[]) null, "resm:Content.Client.StationRecords.GeneralRecord.xaml?assembly=Content.Client");
    context.RootObject = obj1;
    context.IntermediateRoot = (object) obj1;
    Control control1 = obj1;
    BoxContainer boxContainer = new BoxContainer();
    boxContainer.Orientation = (BoxContainer.LayoutOrientation) 1;
    ((Control) boxContainer).Margin = new Thickness(5f, 5f, 5f, 5f);
    Label label1 = new Label();
    ((Control) label1).Name = "RecordName";
    Control control2 = (Control) label1;
    context.RobustNameScope.Register("RecordName", control2);
    ((Control) label1).StyleClasses.Add("LabelBig");
    ((Control) boxContainer).XamlChildren.Add((Control) label1);
    Label label2 = new Label();
    ((Control) label2).Name = "Age";
    Control control3 = (Control) label2;
    context.RobustNameScope.Register("Age", control3);
    ((Control) boxContainer).XamlChildren.Add((Control) label2);
    Label label3 = new Label();
    ((Control) label3).Name = "Title";
    Control control4 = (Control) label3;
    context.RobustNameScope.Register("Title", control4);
    ((Control) boxContainer).XamlChildren.Add((Control) label3);
    Label label4 = new Label();
    ((Control) label4).Name = "Job";
    Control control5 = (Control) label4;
    context.RobustNameScope.Register("Job", control5);
    ((Control) boxContainer).XamlChildren.Add((Control) label4);
    Label label5 = new Label();
    ((Control) label5).Name = "Species";
    Control control6 = (Control) label5;
    context.RobustNameScope.Register("Species", control6);
    ((Control) boxContainer).XamlChildren.Add((Control) label5);
    Label label6 = new Label();
    ((Control) label6).Name = "Gender";
    Control control7 = (Control) label6;
    context.RobustNameScope.Register("Gender", control7);
    ((Control) boxContainer).XamlChildren.Add((Control) label6);
    Label label7 = new Label();
    ((Control) label7).Name = "Fingerprint";
    Control control8 = (Control) label7;
    context.RobustNameScope.Register("Fingerprint", control8);
    ((Control) boxContainer).XamlChildren.Add((Control) label7);
    Label label8 = new Label();
    ((Control) label8).Name = "Dna";
    Control control9 = (Control) label8;
    context.RobustNameScope.Register("Dna", control9);
    ((Control) boxContainer).XamlChildren.Add((Control) label8);
    Button button = new Button();
    ((Control) button).Visible = false;
    ((Control) button).Name = "DeleteButton";
    Control control10 = (Control) button;
    context.RobustNameScope.Register("DeleteButton", control10);
    button.Text = (string) new LocExtension("general-station-record-console-delete").ProvideValue();
    ((Control) boxContainer).XamlChildren.Add((Control) button);
    control1.XamlChildren.Add((Control) boxContainer);
    if (control1 is Control control11)
    {
      context.RobustNameScope.Absorb(control11.NameScope);
      control11.NameScope = context.RobustNameScope;
    }
    context.RobustNameScope.Complete();
  }

  private static void \u0021XamlIlPopulateTrampoline([In] GeneralRecord obj0)
  {
    if (IoCManager.Resolve<IXamlProxyHelper>().Populate(typeof (GeneralRecord), (object) obj0))
      return;
    GeneralRecord.Populate\u003AContent\u002EClient\u002EStationRecords\u002EGeneralRecord\u002Examl((IServiceProvider) null, (Control) obj0);
  }
}
