using System;
using System.Collections.Generic;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Map;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;

namespace Content.Shared._RMC14.Dropship.Weapon;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] { typeof(SharedDropshipWeaponSystem) })]
public sealed class ActiveFlareSignalComponent : Component, ISerializationGenerated<ActiveFlareSignalComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ActiveFlareSignalComponent_AutoState : IComponentState
	{
		public string? Abbreviation;

		public Queue<NetCoordinates> LastCoordinates;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ActiveFlareSignalComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<ActiveFlareSignalComponent, ComponentGetState>((ComponentEventRefHandler<ActiveFlareSignalComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<ActiveFlareSignalComponent, ComponentHandleState>((ComponentEventRefHandler<ActiveFlareSignalComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, ActiveFlareSignalComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new ActiveFlareSignalComponent_AutoState
			{
				Abbreviation = component.Abbreviation,
				LastCoordinates = component.LastCoordinates
			};
		}

		private void OnHandleState(EntityUid uid, ActiveFlareSignalComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is ActiveFlareSignalComponent_AutoState state)
			{
				component.Abbreviation = state.Abbreviation;
				component.LastCoordinates = state.LastCoordinates;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public string? Abbreviation;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public Queue<NetCoordinates> LastCoordinates = new Queue<NetCoordinates>();

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref ActiveFlareSignalComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (ActiveFlareSignalComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<ActiveFlareSignalComponent>(this, ref target, hookCtx, false, context))
		{
			string AbbreviationTemp = null;
			if (!serialization.TryCustomCopy<string>(Abbreviation, ref AbbreviationTemp, hookCtx, false, context))
			{
				AbbreviationTemp = Abbreviation;
			}
			target.Abbreviation = AbbreviationTemp;
			Queue<NetCoordinates> LastCoordinatesTemp = null;
			if (LastCoordinates == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<Queue<NetCoordinates>>(LastCoordinates, ref LastCoordinatesTemp, hookCtx, true, context))
			{
				LastCoordinatesTemp = serialization.CreateCopy<Queue<NetCoordinates>>(LastCoordinates, hookCtx, context, false);
			}
			target.LastCoordinates = LastCoordinatesTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref ActiveFlareSignalComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ActiveFlareSignalComponent cast = (ActiveFlareSignalComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ActiveFlareSignalComponent cast = (ActiveFlareSignalComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ActiveFlareSignalComponent def = (ActiveFlareSignalComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override ActiveFlareSignalComponent Instantiate()
	{
		return new ActiveFlareSignalComponent();
	}
}
