// Decompiled with JetBrains decompiler
// Type: Content.Client.Administration.UI.BanList.Bans.BanListHeader
// Assembly: Content.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B4469588-B038-4783-B6EC-1EFF6592A364
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Client.dll

using CompiledRobustXaml;
using Content.Client.Administration.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML.Proxy;
using Robust.Shared.IoC;
using System;
using System.Runtime.InteropServices;

#nullable disable
namespace Content.Client.Administration.UI.BanList.Bans;

[GenerateTypedNameReferences]
[XamlMetadata("resm:Content.Client.Administration.UI.BanList.Bans.BanListHeader.xaml?assembly=Content.Client", "Content.Client.Administration.UI.BanList.Bans.BanListHeader.xaml", "<ContainerButton\r\n    xmlns=\"https://spacestation14.io\"\r\n    xmlns:cc=\"clr-namespace:Content.Client.Administration.UI.CustomControls\">\r\n    <PanelContainer Name=\"BackgroundPanel\" Access=\"Public\">\r\n        <BoxContainer\r\n            Orientation=\"Horizontal\"\r\n            HorizontalExpand=\"True\"\r\n            SeparationOverride=\"4\">\r\n            <Label Text=\"{Loc ban-list-header-ids}\"\r\n                   SizeFlagsStretchRatio=\"1\"\r\n                   HorizontalExpand=\"True\"/>\r\n            <cc:VSeparator/>\r\n            <Label Text=\"{Loc ban-list-header-reason}\"\r\n                   SizeFlagsStretchRatio=\"6\"\r\n                   HorizontalExpand=\"True\"/>\r\n            <cc:VSeparator/>\r\n            <Label Text=\"{Loc ban-list-header-time}\"\r\n                   SizeFlagsStretchRatio=\"2\"\r\n                   HorizontalExpand=\"True\"/>\r\n            <cc:VSeparator/>\r\n            <Label Text=\"{Loc ban-list-header-expires}\"\r\n                   SizeFlagsStretchRatio=\"4\"\r\n                   HorizontalExpand=\"True\"/>\r\n            <cc:VSeparator/>\r\n            <Label Text=\"{Loc ban-list-header-banning-admin}\"\r\n                   SizeFlagsStretchRatio=\"2\"\r\n                   HorizontalExpand=\"True\"/>\r\n        </BoxContainer>\r\n    </PanelContainer>\r\n</ContainerButton>\r\n")]
public sealed class BanListHeader : ContainerButton
{
  public BanListHeader() => BanListHeader.\u0021XamlIlPopulateTrampoline(this);

  public PanelContainer BackgroundPanel
  {
    get => ((Control) this).FindControl<PanelContainer>(nameof (BackgroundPanel));
  }

  public static void Populate\u003AContent\u002EClient\u002EAdministration\u002EUI\u002EBanList\u002EBans\u002EBanListHeader\u002Examl(
    [In] IServiceProvider obj0,
    [In] ContainerButton obj1)
  {
    XamlIlContext.Context<ContainerButton> context = new XamlIlContext.Context<ContainerButton>(obj0, (object[]) null, "resm:Content.Client.Administration.UI.BanList.Bans.BanListHeader.xaml?assembly=Content.Client");
    context.RootObject = obj1;
    context.IntermediateRoot = (object) obj1;
    ContainerButton containerButton = obj1;
    PanelContainer panelContainer = new PanelContainer();
    ((Control) panelContainer).Name = "BackgroundPanel";
    Control control1 = (Control) panelContainer;
    context.RobustNameScope.Register("BackgroundPanel", control1);
    ((Control) panelContainer).Access = new AccessLevel?((AccessLevel) 0);
    BoxContainer boxContainer = new BoxContainer();
    boxContainer.Orientation = (BoxContainer.LayoutOrientation) 0;
    ((Control) boxContainer).HorizontalExpand = true;
    boxContainer.SeparationOverride = new int?(4);
    Label label1 = new Label();
    label1.Text = (string) new LocExtension("ban-list-header-ids").ProvideValue();
    ((Control) label1).SizeFlagsStretchRatio = 1f;
    ((Control) label1).HorizontalExpand = true;
    ((Control) boxContainer).XamlChildren.Add((Control) label1);
    ((Control) boxContainer).XamlChildren.Add((Control) new VSeparator());
    Label label2 = new Label();
    label2.Text = (string) new LocExtension("ban-list-header-reason").ProvideValue();
    ((Control) label2).SizeFlagsStretchRatio = 6f;
    ((Control) label2).HorizontalExpand = true;
    ((Control) boxContainer).XamlChildren.Add((Control) label2);
    ((Control) boxContainer).XamlChildren.Add((Control) new VSeparator());
    Label label3 = new Label();
    label3.Text = (string) new LocExtension("ban-list-header-time").ProvideValue();
    ((Control) label3).SizeFlagsStretchRatio = 2f;
    ((Control) label3).HorizontalExpand = true;
    ((Control) boxContainer).XamlChildren.Add((Control) label3);
    ((Control) boxContainer).XamlChildren.Add((Control) new VSeparator());
    Label label4 = new Label();
    label4.Text = (string) new LocExtension("ban-list-header-expires").ProvideValue();
    ((Control) label4).SizeFlagsStretchRatio = 4f;
    ((Control) label4).HorizontalExpand = true;
    ((Control) boxContainer).XamlChildren.Add((Control) label4);
    ((Control) boxContainer).XamlChildren.Add((Control) new VSeparator());
    Label label5 = new Label();
    label5.Text = (string) new LocExtension("ban-list-header-banning-admin").ProvideValue();
    ((Control) label5).SizeFlagsStretchRatio = 2f;
    ((Control) label5).HorizontalExpand = true;
    ((Control) boxContainer).XamlChildren.Add((Control) label5);
    ((Control) panelContainer).XamlChildren.Add((Control) boxContainer);
    ((Control) containerButton).XamlChildren.Add((Control) panelContainer);
    if (containerButton is Control control2)
    {
      context.RobustNameScope.Absorb(control2.NameScope);
      control2.NameScope = context.RobustNameScope;
    }
    context.RobustNameScope.Complete();
  }

  private static void \u0021XamlIlPopulateTrampoline([In] BanListHeader obj0)
  {
    if (IoCManager.Resolve<IXamlProxyHelper>().Populate(typeof (BanListHeader), (object) obj0))
      return;
    BanListHeader.Populate\u003AContent\u002EClient\u002EAdministration\u002EUI\u002EBanList\u002EBans\u002EBanListHeader\u002Examl((IServiceProvider) null, (ContainerButton) obj0);
  }
}
