using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Permissions;

[assembly: Extension]
[assembly: InternalsVisibleTo("Robust.Server")]
[assembly: InternalsVisibleTo("Robust.Client")]
[assembly: InternalsVisibleTo("Robust.Lite")]
[assembly: InternalsVisibleTo("Robust.UnitTesting")]
[assembly: InternalsVisibleTo("OpenToolkit.GraphicsLibraryFramework")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("Robust.Benchmarks")]
[assembly: InternalsVisibleTo("Robust.Client.WebView")]
[assembly: InternalsVisibleTo("Robust.Packaging")]
[assembly: InternalsVisibleTo("Robust.Shared.Tests")]
[assembly: InternalsVisibleTo("Robust.Server.IntegrationTests")]
[assembly: InternalsVisibleTo("Robust.Server.Testing")]
[assembly: InternalsVisibleTo("Robust.Shared.Testing")]
[assembly: InternalsVisibleTo("Robust.Client.IntegrationTests")]
[assembly: InternalsVisibleTo("Robust.Shared.IntegrationTests")]
[assembly: AssemblyCompany("Robust.Shared")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("272.0.0.0")]
[assembly: AssemblyInformationalVersion("272.0.0+f509405022cf75c3a906b2e1bd0a3e8e7eafe3bc")]
[assembly: AssemblyProduct("Robust.Shared")]
[assembly: AssemblyTitle("Robust.Shared")]
[assembly: AssemblyVersion("272.0.0.0")]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
