using System;
using System.ComponentModel;
using Content.Shared.DoAfter;
using Robust.Shared.Analyzers;
using Robust.Shared.Audio;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;
using Robust.Shared.ViewVariables;

namespace Content.Shared.Burial.Components;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
public sealed class GraveComponent : Component, ISerializationGenerated<GraveComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class GraveComponent_AutoState : IComponentState
	{
		public bool ActiveShovelDigging;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class GraveComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<GraveComponent, ComponentGetState>((ComponentEventRefHandler<GraveComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<GraveComponent, ComponentHandleState>((ComponentEventRefHandler<GraveComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, GraveComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new GraveComponent_AutoState
			{
				ActiveShovelDigging = component.ActiveShovelDigging
			};
		}

		private void OnHandleState(EntityUid uid, GraveComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is GraveComponent_AutoState state)
			{
				component.ActiveShovelDigging = state.ActiveShovelDigging;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	public TimeSpan DigDelay = TimeSpan.FromSeconds(15L);

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	public float DigOutByHandModifier = 0.1f;

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	public SoundPathSpecifier DigSound = new SoundPathSpecifier("/Audio/Items/shovel_dig.ogg", (AudioParams?)null)
	{
		Params = ((AudioParams)(ref AudioParams.Default)).WithLoop(true)
	};

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	public bool DiggingComplete;

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	public EntityUid? Stream;

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	[AutoNetworkedField]
	public bool ActiveShovelDigging;

	[DataField(null, false, 1, false, false, null)]
	[ViewVariables(/*Could not decode attribute arguments.*/)]
	public DoAfterId? HandDiggingDoAfter;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref GraveComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_008e: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (GraveComponent)(object)definitionCast;
		if (serialization.TryCustomCopy<GraveComponent>(this, ref target, hookCtx, false, context))
		{
			return;
		}
		TimeSpan DigDelayTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(DigDelay, ref DigDelayTemp, hookCtx, false, context))
		{
			DigDelayTemp = serialization.CreateCopy<TimeSpan>(DigDelay, hookCtx, context, false);
		}
		target.DigDelay = DigDelayTemp;
		float DigOutByHandModifierTemp = 0f;
		if (!serialization.TryCustomCopy<float>(DigOutByHandModifier, ref DigOutByHandModifierTemp, hookCtx, false, context))
		{
			DigOutByHandModifierTemp = DigOutByHandModifier;
		}
		target.DigOutByHandModifier = DigOutByHandModifierTemp;
		SoundPathSpecifier DigSoundTemp = null;
		if (DigSound == null)
		{
			throw new NullNotAllowedException();
		}
		if (!serialization.TryCustomCopy<SoundPathSpecifier>(DigSound, ref DigSoundTemp, hookCtx, false, context))
		{
			if (DigSound == null)
			{
				DigSoundTemp = null;
			}
			else
			{
				serialization.CopyTo<SoundPathSpecifier>(DigSound, ref DigSoundTemp, hookCtx, context, true);
			}
		}
		target.DigSound = DigSoundTemp;
		bool DiggingCompleteTemp = false;
		if (!serialization.TryCustomCopy<bool>(DiggingComplete, ref DiggingCompleteTemp, hookCtx, false, context))
		{
			DiggingCompleteTemp = DiggingComplete;
		}
		target.DiggingComplete = DiggingCompleteTemp;
		EntityUid? StreamTemp = null;
		if (!serialization.TryCustomCopy<EntityUid?>(Stream, ref StreamTemp, hookCtx, false, context))
		{
			StreamTemp = serialization.CreateCopy<EntityUid?>(Stream, hookCtx, context, false);
		}
		target.Stream = StreamTemp;
		bool ActiveShovelDiggingTemp = false;
		if (!serialization.TryCustomCopy<bool>(ActiveShovelDigging, ref ActiveShovelDiggingTemp, hookCtx, false, context))
		{
			ActiveShovelDiggingTemp = ActiveShovelDigging;
		}
		target.ActiveShovelDigging = ActiveShovelDiggingTemp;
		DoAfterId? HandDiggingDoAfterTemp = null;
		if (!serialization.TryCustomCopy<DoAfterId?>(HandDiggingDoAfter, ref HandDiggingDoAfterTemp, hookCtx, false, context))
		{
			HandDiggingDoAfterTemp = serialization.CreateCopy<DoAfterId?>(HandDiggingDoAfter, hookCtx, context, false);
		}
		target.HandDiggingDoAfter = HandDiggingDoAfterTemp;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref GraveComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		GraveComponent cast = (GraveComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		GraveComponent cast = (GraveComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		GraveComponent def = (GraveComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override GraveComponent Instantiate()
	{
		return new GraveComponent();
	}
}
