using System;
using System.ComponentModel;
using Content.Shared.Damage;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;

namespace Content.Shared._RMC14.Projectiles.Aimed;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
public sealed class AimedShotEffectComponent : Component, ISerializationGenerated<AimedShotEffectComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class AimedShotEffectComponent_AutoState : IComponentState
	{
		public float ExtraHits;

		public int FireStacksOnHit;

		public TimeSpan BlindDuration;

		public TimeSpan SlowDuration;

		public TimeSpan SuperSlowDuration;

		public DamageSpecifier CurrentHealthDamage;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class AimedShotEffectComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<AimedShotEffectComponent, ComponentGetState>((ComponentEventRefHandler<AimedShotEffectComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<AimedShotEffectComponent, ComponentHandleState>((ComponentEventRefHandler<AimedShotEffectComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, AimedShotEffectComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new AimedShotEffectComponent_AutoState
			{
				ExtraHits = component.ExtraHits,
				FireStacksOnHit = component.FireStacksOnHit,
				BlindDuration = component.BlindDuration,
				SlowDuration = component.SlowDuration,
				SuperSlowDuration = component.SuperSlowDuration,
				CurrentHealthDamage = component.CurrentHealthDamage
			};
		}

		private void OnHandleState(EntityUid uid, AimedShotEffectComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is AimedShotEffectComponent_AutoState state)
			{
				component.ExtraHits = state.ExtraHits;
				component.FireStacksOnHit = state.FireStacksOnHit;
				component.BlindDuration = state.BlindDuration;
				component.SlowDuration = state.SlowDuration;
				component.SuperSlowDuration = state.SuperSlowDuration;
				component.CurrentHealthDamage = state.CurrentHealthDamage;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public float ExtraHits;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public int FireStacksOnHit;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan BlindDuration;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan SlowDuration;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan SuperSlowDuration;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public DamageSpecifier CurrentHealthDamage = new DamageSpecifier();

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref AimedShotEffectComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0122: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (AimedShotEffectComponent)(object)definitionCast;
		if (serialization.TryCustomCopy<AimedShotEffectComponent>(this, ref target, hookCtx, false, context))
		{
			return;
		}
		float ExtraHitsTemp = 0f;
		if (!serialization.TryCustomCopy<float>(ExtraHits, ref ExtraHitsTemp, hookCtx, false, context))
		{
			ExtraHitsTemp = ExtraHits;
		}
		target.ExtraHits = ExtraHitsTemp;
		int FireStacksOnHitTemp = 0;
		if (!serialization.TryCustomCopy<int>(FireStacksOnHit, ref FireStacksOnHitTemp, hookCtx, false, context))
		{
			FireStacksOnHitTemp = FireStacksOnHit;
		}
		target.FireStacksOnHit = FireStacksOnHitTemp;
		TimeSpan BlindDurationTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(BlindDuration, ref BlindDurationTemp, hookCtx, false, context))
		{
			BlindDurationTemp = serialization.CreateCopy<TimeSpan>(BlindDuration, hookCtx, context, false);
		}
		target.BlindDuration = BlindDurationTemp;
		TimeSpan SlowDurationTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(SlowDuration, ref SlowDurationTemp, hookCtx, false, context))
		{
			SlowDurationTemp = serialization.CreateCopy<TimeSpan>(SlowDuration, hookCtx, context, false);
		}
		target.SlowDuration = SlowDurationTemp;
		TimeSpan SuperSlowDurationTemp = default(TimeSpan);
		if (!serialization.TryCustomCopy<TimeSpan>(SuperSlowDuration, ref SuperSlowDurationTemp, hookCtx, false, context))
		{
			SuperSlowDurationTemp = serialization.CreateCopy<TimeSpan>(SuperSlowDuration, hookCtx, context, false);
		}
		target.SuperSlowDuration = SuperSlowDurationTemp;
		DamageSpecifier CurrentHealthDamageTemp = null;
		if (CurrentHealthDamage == null)
		{
			throw new NullNotAllowedException();
		}
		if (!serialization.TryCustomCopy<DamageSpecifier>(CurrentHealthDamage, ref CurrentHealthDamageTemp, hookCtx, false, context))
		{
			if (CurrentHealthDamage == null)
			{
				CurrentHealthDamageTemp = null;
			}
			else
			{
				serialization.CopyTo<DamageSpecifier>(CurrentHealthDamage, ref CurrentHealthDamageTemp, hookCtx, context, true);
			}
		}
		target.CurrentHealthDamage = CurrentHealthDamageTemp;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref AimedShotEffectComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		AimedShotEffectComponent cast = (AimedShotEffectComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		AimedShotEffectComponent cast = (AimedShotEffectComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		AimedShotEffectComponent def = (AimedShotEffectComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override AimedShotEffectComponent Instantiate()
	{
		return new AimedShotEffectComponent();
	}
}
