using System;
using System.Collections.Generic;
using System.ComponentModel;
using Content.Shared._RMC14.Marines.Skills;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Robust.Shared.Analyzers;
using Robust.Shared.Audio;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;
using Robust.Shared.Timing;

namespace Content.Shared._RMC14.Medical.Wounds;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, true)]
[Access(new Type[] { typeof(SharedWoundsSystem) })]
public sealed class WoundTreaterComponent : Component, ISerializationGenerated<WoundTreaterComponent>, ISerializationGenerated, IComponentDelta, IComponent, ISerializationGenerated<IComponent>, ISerializationGenerated<IComponentDelta>
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class WoundTreaterComponent_AutoState : IComponentState
	{
		public WoundType Wound;

		public bool Treats;

		public bool Consumable;

		public ProtoId<DamageGroupPrototype> Group;

		public TimeSpan ScalingDoAfter;

		public EntProtoId<SkillDefinitionComponent> DoAfterSkill;

		public float[] DoAfterSkillMultipliers;

		public float SelfTargetDoAfterMultiplier;

		public FixedPoint2? Damage;

		public FixedPoint2? UnskilledDamage;

		public bool CanUseUnskilled;

		public Dictionary<EntProtoId<SkillDefinitionComponent>, int> Skills;

		public SoundSpecifier? TreatBeginSound;

		public SoundSpecifier? TreatEndSound;

		public LocId? UserPopup;

		public LocId? TargetPopup;

		public LocId? OthersPopup;

		public LocId? TargetStartPopup;

		public LocId? UserFinishPopup;

		public LocId? TargetFinishPopup;

		public LocId? OthersFinishPopup;

		public LocId? NoneSelfPopup;

		public LocId? NoneOtherPopup;

		public LocId? NoWoundsOnUserPopup;

		public LocId? NoWoundsOnTargetPopup;

		public ushort? CurrentDoAfter;

		public WoundTreaterComponent_AutoState ShallowClone()
		{
			//IL_002b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0030: Unknown result type (might be due to invalid IL or missing references)
			//IL_0043: Unknown result type (might be due to invalid IL or missing references)
			//IL_0048: Unknown result type (might be due to invalid IL or missing references)
			return new WoundTreaterComponent_AutoState
			{
				Wound = Wound,
				Treats = Treats,
				Consumable = Consumable,
				Group = Group,
				ScalingDoAfter = ScalingDoAfter,
				DoAfterSkill = DoAfterSkill,
				DoAfterSkillMultipliers = DoAfterSkillMultipliers,
				SelfTargetDoAfterMultiplier = SelfTargetDoAfterMultiplier,
				Damage = Damage,
				UnskilledDamage = UnskilledDamage,
				CanUseUnskilled = CanUseUnskilled,
				Skills = Skills,
				TreatBeginSound = TreatBeginSound,
				TreatEndSound = TreatEndSound,
				UserPopup = UserPopup,
				TargetPopup = TargetPopup,
				OthersPopup = OthersPopup,
				TargetStartPopup = TargetStartPopup,
				UserFinishPopup = UserFinishPopup,
				TargetFinishPopup = TargetFinishPopup,
				OthersFinishPopup = OthersFinishPopup,
				NoneSelfPopup = NoneSelfPopup,
				NoneOtherPopup = NoneOtherPopup,
				NoWoundsOnUserPopup = NoWoundsOnUserPopup,
				NoWoundsOnTargetPopup = NoWoundsOnTargetPopup,
				CurrentDoAfter = CurrentDoAfter
			};
		}
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class WoundTreaterComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			base.EntityManager.ComponentFactory.RegisterNetworkedFields<WoundTreaterComponent>(new string[26]
			{
				"Wound", "Treats", "Consumable", "Group", "ScalingDoAfter", "DoAfterSkill", "DoAfterSkillMultipliers", "SelfTargetDoAfterMultiplier", "Damage", "UnskilledDamage",
				"CanUseUnskilled", "Skills", "TreatBeginSound", "TreatEndSound", "UserPopup", "TargetPopup", "OthersPopup", "TargetStartPopup", "UserFinishPopup", "TargetFinishPopup",
				"OthersFinishPopup", "NoneSelfPopup", "NoneOtherPopup", "NoWoundsOnUserPopup", "NoWoundsOnTargetPopup", "CurrentDoAfter"
			});
			((EntitySystem)this).SubscribeLocalEvent<WoundTreaterComponent, ComponentGetState>((ComponentEventRefHandler<WoundTreaterComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<WoundTreaterComponent, ComponentHandleState>((ComponentEventRefHandler<WoundTreaterComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, WoundTreaterComponent component, ref ComponentGetState args)
		{
			//IL_044b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0450: Unknown result type (might be due to invalid IL or missing references)
			//IL_0463: Unknown result type (might be due to invalid IL or missing references)
			//IL_0468: Unknown result type (might be due to invalid IL or missing references)
			//IL_0009: Unknown result type (might be due to invalid IL or missing references)
			//IL_000f: Unknown result type (might be due to invalid IL or missing references)
			//IL_001f: Unknown result type (might be due to invalid IL or missing references)
			//IL_0025: Unknown result type (might be due to invalid IL or missing references)
			//IL_003c: Unknown result type (might be due to invalid IL or missing references)
			//IL_022f: Unknown result type (might be due to invalid IL or missing references)
			//IL_0234: Unknown result type (might be due to invalid IL or missing references)
			//IL_01ff: Unknown result type (might be due to invalid IL or missing references)
			//IL_0204: Unknown result type (might be due to invalid IL or missing references)
			if (component != null && ((ComponentGetState)(ref args)).FromTick > ((Component)component).CreationTick && ((IComponentDelta)component).LastFieldUpdate >= ((ComponentGetState)(ref args)).FromTick)
			{
				switch (base.EntityManager.GetModifiedFields((IComponentDelta)(object)component, ((ComponentGetState)(ref args)).FromTick))
				{
				case 1u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new Wound_FieldComponentState
					{
						Wound = component.Wound
					};
					return;
				case 2u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new Treats_FieldComponentState
					{
						Treats = component.Treats
					};
					return;
				case 4u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new Consumable_FieldComponentState
					{
						Consumable = component.Consumable
					};
					return;
				case 8u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new Group_FieldComponentState
					{
						Group = component.Group
					};
					return;
				case 16u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new ScalingDoAfter_FieldComponentState
					{
						ScalingDoAfter = component.ScalingDoAfter
					};
					return;
				case 32u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new DoAfterSkill_FieldComponentState
					{
						DoAfterSkill = component.DoAfterSkill
					};
					return;
				case 64u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new DoAfterSkillMultipliers_FieldComponentState
					{
						DoAfterSkillMultipliers = component.DoAfterSkillMultipliers
					};
					return;
				case 128u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new SelfTargetDoAfterMultiplier_FieldComponentState
					{
						SelfTargetDoAfterMultiplier = component.SelfTargetDoAfterMultiplier
					};
					return;
				case 256u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new Damage_FieldComponentState
					{
						Damage = component.Damage
					};
					return;
				case 512u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new UnskilledDamage_FieldComponentState
					{
						UnskilledDamage = component.UnskilledDamage
					};
					return;
				case 1024u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new CanUseUnskilled_FieldComponentState
					{
						CanUseUnskilled = component.CanUseUnskilled
					};
					return;
				case 2048u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new Skills_FieldComponentState
					{
						Skills = component.Skills
					};
					return;
				case 4096u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new TreatBeginSound_FieldComponentState
					{
						TreatBeginSound = component.TreatBeginSound
					};
					return;
				case 8192u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new TreatEndSound_FieldComponentState
					{
						TreatEndSound = component.TreatEndSound
					};
					return;
				case 16384u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new UserPopup_FieldComponentState
					{
						UserPopup = component.UserPopup
					};
					return;
				case 32768u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new TargetPopup_FieldComponentState
					{
						TargetPopup = component.TargetPopup
					};
					return;
				case 65536u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new OthersPopup_FieldComponentState
					{
						OthersPopup = component.OthersPopup
					};
					return;
				case 131072u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new TargetStartPopup_FieldComponentState
					{
						TargetStartPopup = component.TargetStartPopup
					};
					return;
				case 262144u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new UserFinishPopup_FieldComponentState
					{
						UserFinishPopup = component.UserFinishPopup
					};
					return;
				case 524288u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new TargetFinishPopup_FieldComponentState
					{
						TargetFinishPopup = component.TargetFinishPopup
					};
					return;
				case 1048576u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new OthersFinishPopup_FieldComponentState
					{
						OthersFinishPopup = component.OthersFinishPopup
					};
					return;
				case 2097152u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new NoneSelfPopup_FieldComponentState
					{
						NoneSelfPopup = component.NoneSelfPopup
					};
					return;
				case 4194304u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new NoneOtherPopup_FieldComponentState
					{
						NoneOtherPopup = component.NoneOtherPopup
					};
					return;
				case 8388608u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new NoWoundsOnUserPopup_FieldComponentState
					{
						NoWoundsOnUserPopup = component.NoWoundsOnUserPopup
					};
					return;
				case 16777216u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new NoWoundsOnTargetPopup_FieldComponentState
					{
						NoWoundsOnTargetPopup = component.NoWoundsOnTargetPopup
					};
					return;
				case 33554432u:
					((ComponentGetState)(ref args)).State = (IComponentState)(object)new CurrentDoAfter_FieldComponentState
					{
						CurrentDoAfter = component.CurrentDoAfter
					};
					return;
				}
			}
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new WoundTreaterComponent_AutoState
			{
				Wound = component.Wound,
				Treats = component.Treats,
				Consumable = component.Consumable,
				Group = component.Group,
				ScalingDoAfter = component.ScalingDoAfter,
				DoAfterSkill = component.DoAfterSkill,
				DoAfterSkillMultipliers = component.DoAfterSkillMultipliers,
				SelfTargetDoAfterMultiplier = component.SelfTargetDoAfterMultiplier,
				Damage = component.Damage,
				UnskilledDamage = component.UnskilledDamage,
				CanUseUnskilled = component.CanUseUnskilled,
				Skills = component.Skills,
				TreatBeginSound = component.TreatBeginSound,
				TreatEndSound = component.TreatEndSound,
				UserPopup = component.UserPopup,
				TargetPopup = component.TargetPopup,
				OthersPopup = component.OthersPopup,
				TargetStartPopup = component.TargetStartPopup,
				UserFinishPopup = component.UserFinishPopup,
				TargetFinishPopup = component.TargetFinishPopup,
				OthersFinishPopup = component.OthersFinishPopup,
				NoneSelfPopup = component.NoneSelfPopup,
				NoneOtherPopup = component.NoneOtherPopup,
				NoWoundsOnUserPopup = component.NoWoundsOnUserPopup,
				NoWoundsOnTargetPopup = component.NoWoundsOnTargetPopup,
				CurrentDoAfter = component.CurrentDoAfter
			};
		}

		private void OnHandleState(EntityUid uid, WoundTreaterComponent component, ref ComponentHandleState args)
		{
			//IL_01da: Unknown result type (might be due to invalid IL or missing references)
			//IL_01df: Unknown result type (might be due to invalid IL or missing references)
			//IL_01f6: Unknown result type (might be due to invalid IL or missing references)
			//IL_01fb: Unknown result type (might be due to invalid IL or missing references)
			//IL_0359: Unknown result type (might be due to invalid IL or missing references)
			//IL_035e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0373: Unknown result type (might be due to invalid IL or missing references)
			//IL_0378: Unknown result type (might be due to invalid IL or missing references)
			IComponentState current = ((ComponentHandleState)(ref args)).Current;
			if (!(current is Wound_FieldComponentState Wound_FieldComponentState_State))
			{
				if (!(current is Treats_FieldComponentState Treats_FieldComponentState_State))
				{
					if (!(current is Consumable_FieldComponentState Consumable_FieldComponentState_State))
					{
						if (!(current is Group_FieldComponentState Group_FieldComponentState_State))
						{
							if (!(current is ScalingDoAfter_FieldComponentState ScalingDoAfter_FieldComponentState_State))
							{
								if (!(current is DoAfterSkill_FieldComponentState DoAfterSkill_FieldComponentState_State))
								{
									if (!(current is DoAfterSkillMultipliers_FieldComponentState DoAfterSkillMultipliers_FieldComponentState_State))
									{
										if (!(current is SelfTargetDoAfterMultiplier_FieldComponentState SelfTargetDoAfterMultiplier_FieldComponentState_State))
										{
											if (!(current is Damage_FieldComponentState Damage_FieldComponentState_State))
											{
												if (!(current is UnskilledDamage_FieldComponentState UnskilledDamage_FieldComponentState_State))
												{
													if (!(current is CanUseUnskilled_FieldComponentState CanUseUnskilled_FieldComponentState_State))
													{
														if (!(current is Skills_FieldComponentState Skills_FieldComponentState_State))
														{
															if (!(current is TreatBeginSound_FieldComponentState TreatBeginSound_FieldComponentState_State))
															{
																if (!(current is TreatEndSound_FieldComponentState TreatEndSound_FieldComponentState_State))
																{
																	if (!(current is UserPopup_FieldComponentState UserPopup_FieldComponentState_State))
																	{
																		if (!(current is TargetPopup_FieldComponentState TargetPopup_FieldComponentState_State))
																		{
																			if (!(current is OthersPopup_FieldComponentState OthersPopup_FieldComponentState_State))
																			{
																				if (!(current is TargetStartPopup_FieldComponentState TargetStartPopup_FieldComponentState_State))
																				{
																					if (!(current is UserFinishPopup_FieldComponentState UserFinishPopup_FieldComponentState_State))
																					{
																						if (!(current is TargetFinishPopup_FieldComponentState TargetFinishPopup_FieldComponentState_State))
																						{
																							if (!(current is OthersFinishPopup_FieldComponentState OthersFinishPopup_FieldComponentState_State))
																							{
																								if (!(current is NoneSelfPopup_FieldComponentState NoneSelfPopup_FieldComponentState_State))
																								{
																									if (!(current is NoneOtherPopup_FieldComponentState NoneOtherPopup_FieldComponentState_State))
																									{
																										if (!(current is NoWoundsOnUserPopup_FieldComponentState NoWoundsOnUserPopup_FieldComponentState_State))
																										{
																											if (!(current is NoWoundsOnTargetPopup_FieldComponentState NoWoundsOnTargetPopup_FieldComponentState_State))
																											{
																												if (!(current is CurrentDoAfter_FieldComponentState CurrentDoAfter_FieldComponentState_State))
																												{
																													if (current is WoundTreaterComponent_AutoState state)
																													{
																														component.Wound = state.Wound;
																														component.Treats = state.Treats;
																														component.Consumable = state.Consumable;
																														component.Group = state.Group;
																														component.ScalingDoAfter = state.ScalingDoAfter;
																														component.DoAfterSkill = state.DoAfterSkill;
																														component.DoAfterSkillMultipliers = state.DoAfterSkillMultipliers;
																														component.SelfTargetDoAfterMultiplier = state.SelfTargetDoAfterMultiplier;
																														component.Damage = state.Damage;
																														component.UnskilledDamage = state.UnskilledDamage;
																														component.CanUseUnskilled = state.CanUseUnskilled;
																														component.Skills = ((state.Skills == null) ? null : new Dictionary<EntProtoId<SkillDefinitionComponent>, int>(state.Skills));
																														component.TreatBeginSound = state.TreatBeginSound;
																														component.TreatEndSound = state.TreatEndSound;
																														component.UserPopup = state.UserPopup;
																														component.TargetPopup = state.TargetPopup;
																														component.OthersPopup = state.OthersPopup;
																														component.TargetStartPopup = state.TargetStartPopup;
																														component.UserFinishPopup = state.UserFinishPopup;
																														component.TargetFinishPopup = state.TargetFinishPopup;
																														component.OthersFinishPopup = state.OthersFinishPopup;
																														component.NoneSelfPopup = state.NoneSelfPopup;
																														component.NoneOtherPopup = state.NoneOtherPopup;
																														component.NoWoundsOnUserPopup = state.NoWoundsOnUserPopup;
																														component.NoWoundsOnTargetPopup = state.NoWoundsOnTargetPopup;
																														component.CurrentDoAfter = state.CurrentDoAfter;
																													}
																												}
																												else
																												{
																													component.CurrentDoAfter = CurrentDoAfter_FieldComponentState_State.CurrentDoAfter;
																												}
																											}
																											else
																											{
																												component.NoWoundsOnTargetPopup = NoWoundsOnTargetPopup_FieldComponentState_State.NoWoundsOnTargetPopup;
																											}
																										}
																										else
																										{
																											component.NoWoundsOnUserPopup = NoWoundsOnUserPopup_FieldComponentState_State.NoWoundsOnUserPopup;
																										}
																									}
																									else
																									{
																										component.NoneOtherPopup = NoneOtherPopup_FieldComponentState_State.NoneOtherPopup;
																									}
																								}
																								else
																								{
																									component.NoneSelfPopup = NoneSelfPopup_FieldComponentState_State.NoneSelfPopup;
																								}
																							}
																							else
																							{
																								component.OthersFinishPopup = OthersFinishPopup_FieldComponentState_State.OthersFinishPopup;
																							}
																						}
																						else
																						{
																							component.TargetFinishPopup = TargetFinishPopup_FieldComponentState_State.TargetFinishPopup;
																						}
																					}
																					else
																					{
																						component.UserFinishPopup = UserFinishPopup_FieldComponentState_State.UserFinishPopup;
																					}
																				}
																				else
																				{
																					component.TargetStartPopup = TargetStartPopup_FieldComponentState_State.TargetStartPopup;
																				}
																			}
																			else
																			{
																				component.OthersPopup = OthersPopup_FieldComponentState_State.OthersPopup;
																			}
																		}
																		else
																		{
																			component.TargetPopup = TargetPopup_FieldComponentState_State.TargetPopup;
																		}
																	}
																	else
																	{
																		component.UserPopup = UserPopup_FieldComponentState_State.UserPopup;
																	}
																}
																else
																{
																	component.TreatEndSound = TreatEndSound_FieldComponentState_State.TreatEndSound;
																}
															}
															else
															{
																component.TreatBeginSound = TreatBeginSound_FieldComponentState_State.TreatBeginSound;
															}
														}
														else
														{
															Dictionary<EntProtoId<SkillDefinitionComponent>, int> SkillsValue = Skills_FieldComponentState_State.Skills;
															if (SkillsValue == null)
															{
																component.Skills = null;
															}
															else
															{
																component.Skills = new Dictionary<EntProtoId<SkillDefinitionComponent>, int>(SkillsValue);
															}
														}
													}
													else
													{
														component.CanUseUnskilled = CanUseUnskilled_FieldComponentState_State.CanUseUnskilled;
													}
												}
												else
												{
													component.UnskilledDamage = UnskilledDamage_FieldComponentState_State.UnskilledDamage;
												}
											}
											else
											{
												component.Damage = Damage_FieldComponentState_State.Damage;
											}
										}
										else
										{
											component.SelfTargetDoAfterMultiplier = SelfTargetDoAfterMultiplier_FieldComponentState_State.SelfTargetDoAfterMultiplier;
										}
									}
									else
									{
										component.DoAfterSkillMultipliers = DoAfterSkillMultipliers_FieldComponentState_State.DoAfterSkillMultipliers;
									}
								}
								else
								{
									component.DoAfterSkill = DoAfterSkill_FieldComponentState_State.DoAfterSkill;
								}
							}
							else
							{
								component.ScalingDoAfter = ScalingDoAfter_FieldComponentState_State.ScalingDoAfter;
							}
						}
						else
						{
							component.Group = Group_FieldComponentState_State.Group;
						}
					}
					else
					{
						component.Consumable = Consumable_FieldComponentState_State.Consumable;
					}
				}
				else
				{
					component.Treats = Treats_FieldComponentState_State.Treats;
				}
			}
			else
			{
				component.Wound = Wound_FieldComponentState_State.Wound;
			}
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class Wound_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public WoundType Wound;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.Wound = Wound;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class Treats_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public bool Treats;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.Treats = Treats;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class Consumable_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public bool Consumable;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.Consumable = Consumable;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class Group_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public ProtoId<DamageGroupPrototype> Group;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			//IL_0002: Unknown result type (might be due to invalid IL or missing references)
			//IL_0007: Unknown result type (might be due to invalid IL or missing references)
			fullState.Group = Group;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class ScalingDoAfter_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public TimeSpan ScalingDoAfter;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.ScalingDoAfter = ScalingDoAfter;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class DoAfterSkill_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public EntProtoId<SkillDefinitionComponent> DoAfterSkill;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			//IL_0002: Unknown result type (might be due to invalid IL or missing references)
			//IL_0007: Unknown result type (might be due to invalid IL or missing references)
			fullState.DoAfterSkill = DoAfterSkill;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class DoAfterSkillMultipliers_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public float[] DoAfterSkillMultipliers;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.DoAfterSkillMultipliers = DoAfterSkillMultipliers;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class SelfTargetDoAfterMultiplier_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public float SelfTargetDoAfterMultiplier;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.SelfTargetDoAfterMultiplier = SelfTargetDoAfterMultiplier;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class Damage_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public FixedPoint2? Damage;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.Damage = Damage;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class UnskilledDamage_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public FixedPoint2? UnskilledDamage;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.UnskilledDamage = UnskilledDamage;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class CanUseUnskilled_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public bool CanUseUnskilled;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.CanUseUnskilled = CanUseUnskilled;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class Skills_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public Dictionary<EntProtoId<SkillDefinitionComponent>, int> Skills;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.Skills = ((Skills == null) ? null : new Dictionary<EntProtoId<SkillDefinitionComponent>, int>(Skills));
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class TreatBeginSound_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public SoundSpecifier? TreatBeginSound;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.TreatBeginSound = TreatBeginSound;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class TreatEndSound_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public SoundSpecifier? TreatEndSound;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.TreatEndSound = TreatEndSound;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class UserPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? UserPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.UserPopup = UserPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class TargetPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? TargetPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.TargetPopup = TargetPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class OthersPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? OthersPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.OthersPopup = OthersPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class TargetStartPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? TargetStartPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.TargetStartPopup = TargetStartPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class UserFinishPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? UserFinishPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.UserFinishPopup = UserFinishPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class TargetFinishPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? TargetFinishPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.TargetFinishPopup = TargetFinishPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class OthersFinishPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? OthersFinishPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.OthersFinishPopup = OthersFinishPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class NoneSelfPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? NoneSelfPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.NoneSelfPopup = NoneSelfPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class NoneOtherPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? NoneOtherPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.NoneOtherPopup = NoneOtherPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class NoWoundsOnUserPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? NoWoundsOnUserPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.NoWoundsOnUserPopup = NoWoundsOnUserPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class NoWoundsOnTargetPopup_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public LocId? NoWoundsOnTargetPopup;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.NoWoundsOnTargetPopup = NoWoundsOnTargetPopup;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[Serializable]
	[NetSerializable]
	public sealed class CurrentDoAfter_FieldComponentState : IComponentDeltaState<WoundTreaterComponent_AutoState>, IComponentDeltaState, IComponentState
	{
		public ushort? CurrentDoAfter;

		public void ApplyToFullState(WoundTreaterComponent_AutoState fullState)
		{
			fullState.CurrentDoAfter = CurrentDoAfter;
		}

		public WoundTreaterComponent_AutoState CreateNewFullState(WoundTreaterComponent_AutoState fullState)
		{
			WoundTreaterComponent_AutoState newState = fullState.ShallowClone();
			ApplyToFullState(newState);
			return newState;
		}
	}

	[DataField(null, false, 1, true, false, null)]
	[AutoNetworkedField]
	public WoundType Wound;

	[DataField(null, false, 1, true, false, null)]
	[AutoNetworkedField]
	public bool Treats;

	[DataField(null, false, 1, true, false, null)]
	[AutoNetworkedField]
	public bool Consumable;

	[DataField(null, false, 1, true, false, null)]
	[AutoNetworkedField]
	public ProtoId<DamageGroupPrototype> Group;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan ScalingDoAfter;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public EntProtoId<SkillDefinitionComponent> DoAfterSkill = EntProtoId<SkillDefinitionComponent>.op_Implicit("RMCSkillMedical");

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public float[] DoAfterSkillMultipliers = new float[5] { 1f, 1f, 1f, 0.75f, 0.5f };

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public float SelfTargetDoAfterMultiplier = 1.5f;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public FixedPoint2? Damage;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public FixedPoint2? UnskilledDamage;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool CanUseUnskilled;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public Dictionary<EntProtoId<SkillDefinitionComponent>, int> Skills = new Dictionary<EntProtoId<SkillDefinitionComponent>, int>();

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public SoundSpecifier? TreatBeginSound;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public SoundSpecifier? TreatEndSound;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? UserPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? TargetPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? OthersPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? TargetStartPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? UserFinishPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? TargetFinishPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? OthersFinishPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? NoneSelfPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? NoneOtherPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? NoWoundsOnUserPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId? NoWoundsOnTargetPopup;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public ushort? CurrentDoAfter;

	public GameTick LastFieldUpdate { get; set; } = GameTick.Zero;

	public GameTick[] LastModifiedFields { get; set; } = Array.Empty<GameTick>();

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref WoundTreaterComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0097: Unknown result type (might be due to invalid IL or missing references)
		//IL_009f: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c7: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b3: Unknown result type (might be due to invalid IL or missing references)
		//IL_00bc: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c1: Unknown result type (might be due to invalid IL or missing references)
		//IL_0105: Unknown result type (might be due to invalid IL or missing references)
		//IL_010d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0133: Unknown result type (might be due to invalid IL or missing references)
		//IL_0135: Unknown result type (might be due to invalid IL or missing references)
		//IL_0121: Unknown result type (might be due to invalid IL or missing references)
		//IL_012a: Unknown result type (might be due to invalid IL or missing references)
		//IL_012f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0145: Unknown result type (might be due to invalid IL or missing references)
		//IL_0247: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (WoundTreaterComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<WoundTreaterComponent>(this, ref target, hookCtx, false, context))
		{
			WoundType WoundTemp = WoundType.Brute;
			if (!serialization.TryCustomCopy<WoundType>(Wound, ref WoundTemp, hookCtx, false, context))
			{
				WoundTemp = Wound;
			}
			target.Wound = WoundTemp;
			bool TreatsTemp = false;
			if (!serialization.TryCustomCopy<bool>(Treats, ref TreatsTemp, hookCtx, false, context))
			{
				TreatsTemp = Treats;
			}
			target.Treats = TreatsTemp;
			bool ConsumableTemp = false;
			if (!serialization.TryCustomCopy<bool>(Consumable, ref ConsumableTemp, hookCtx, false, context))
			{
				ConsumableTemp = Consumable;
			}
			target.Consumable = ConsumableTemp;
			ProtoId<DamageGroupPrototype> GroupTemp = default(ProtoId<DamageGroupPrototype>);
			if (!serialization.TryCustomCopy<ProtoId<DamageGroupPrototype>>(Group, ref GroupTemp, hookCtx, false, context))
			{
				GroupTemp = serialization.CreateCopy<ProtoId<DamageGroupPrototype>>(Group, hookCtx, context, false);
			}
			target.Group = GroupTemp;
			TimeSpan ScalingDoAfterTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(ScalingDoAfter, ref ScalingDoAfterTemp, hookCtx, false, context))
			{
				ScalingDoAfterTemp = serialization.CreateCopy<TimeSpan>(ScalingDoAfter, hookCtx, context, false);
			}
			target.ScalingDoAfter = ScalingDoAfterTemp;
			EntProtoId<SkillDefinitionComponent> DoAfterSkillTemp = default(EntProtoId<SkillDefinitionComponent>);
			if (!serialization.TryCustomCopy<EntProtoId<SkillDefinitionComponent>>(DoAfterSkill, ref DoAfterSkillTemp, hookCtx, false, context))
			{
				DoAfterSkillTemp = serialization.CreateCopy<EntProtoId<SkillDefinitionComponent>>(DoAfterSkill, hookCtx, context, false);
			}
			target.DoAfterSkill = DoAfterSkillTemp;
			float[] DoAfterSkillMultipliersTemp = null;
			if (DoAfterSkillMultipliers == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<float[]>(DoAfterSkillMultipliers, ref DoAfterSkillMultipliersTemp, hookCtx, true, context))
			{
				DoAfterSkillMultipliersTemp = serialization.CreateCopy<float[]>(DoAfterSkillMultipliers, hookCtx, context, false);
			}
			target.DoAfterSkillMultipliers = DoAfterSkillMultipliersTemp;
			float SelfTargetDoAfterMultiplierTemp = 0f;
			if (!serialization.TryCustomCopy<float>(SelfTargetDoAfterMultiplier, ref SelfTargetDoAfterMultiplierTemp, hookCtx, false, context))
			{
				SelfTargetDoAfterMultiplierTemp = SelfTargetDoAfterMultiplier;
			}
			target.SelfTargetDoAfterMultiplier = SelfTargetDoAfterMultiplierTemp;
			FixedPoint2? DamageTemp = null;
			if (!serialization.TryCustomCopy<FixedPoint2?>(Damage, ref DamageTemp, hookCtx, false, context))
			{
				DamageTemp = serialization.CreateCopy<FixedPoint2?>(Damage, hookCtx, context, false);
			}
			target.Damage = DamageTemp;
			FixedPoint2? UnskilledDamageTemp = null;
			if (!serialization.TryCustomCopy<FixedPoint2?>(UnskilledDamage, ref UnskilledDamageTemp, hookCtx, false, context))
			{
				UnskilledDamageTemp = serialization.CreateCopy<FixedPoint2?>(UnskilledDamage, hookCtx, context, false);
			}
			target.UnskilledDamage = UnskilledDamageTemp;
			bool CanUseUnskilledTemp = false;
			if (!serialization.TryCustomCopy<bool>(CanUseUnskilled, ref CanUseUnskilledTemp, hookCtx, false, context))
			{
				CanUseUnskilledTemp = CanUseUnskilled;
			}
			target.CanUseUnskilled = CanUseUnskilledTemp;
			Dictionary<EntProtoId<SkillDefinitionComponent>, int> SkillsTemp = null;
			if (Skills == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<Dictionary<EntProtoId<SkillDefinitionComponent>, int>>(Skills, ref SkillsTemp, hookCtx, true, context))
			{
				SkillsTemp = serialization.CreateCopy<Dictionary<EntProtoId<SkillDefinitionComponent>, int>>(Skills, hookCtx, context, false);
			}
			target.Skills = SkillsTemp;
			SoundSpecifier TreatBeginSoundTemp = null;
			if (!serialization.TryCustomCopy<SoundSpecifier>(TreatBeginSound, ref TreatBeginSoundTemp, hookCtx, true, context))
			{
				TreatBeginSoundTemp = serialization.CreateCopy<SoundSpecifier>(TreatBeginSound, hookCtx, context, false);
			}
			target.TreatBeginSound = TreatBeginSoundTemp;
			SoundSpecifier TreatEndSoundTemp = null;
			if (!serialization.TryCustomCopy<SoundSpecifier>(TreatEndSound, ref TreatEndSoundTemp, hookCtx, true, context))
			{
				TreatEndSoundTemp = serialization.CreateCopy<SoundSpecifier>(TreatEndSound, hookCtx, context, false);
			}
			target.TreatEndSound = TreatEndSoundTemp;
			LocId? UserPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(UserPopup, ref UserPopupTemp, hookCtx, false, context))
			{
				UserPopupTemp = serialization.CreateCopy<LocId?>(UserPopup, hookCtx, context, false);
			}
			target.UserPopup = UserPopupTemp;
			LocId? TargetPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(TargetPopup, ref TargetPopupTemp, hookCtx, false, context))
			{
				TargetPopupTemp = serialization.CreateCopy<LocId?>(TargetPopup, hookCtx, context, false);
			}
			target.TargetPopup = TargetPopupTemp;
			LocId? OthersPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(OthersPopup, ref OthersPopupTemp, hookCtx, false, context))
			{
				OthersPopupTemp = serialization.CreateCopy<LocId?>(OthersPopup, hookCtx, context, false);
			}
			target.OthersPopup = OthersPopupTemp;
			LocId? TargetStartPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(TargetStartPopup, ref TargetStartPopupTemp, hookCtx, false, context))
			{
				TargetStartPopupTemp = serialization.CreateCopy<LocId?>(TargetStartPopup, hookCtx, context, false);
			}
			target.TargetStartPopup = TargetStartPopupTemp;
			LocId? UserFinishPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(UserFinishPopup, ref UserFinishPopupTemp, hookCtx, false, context))
			{
				UserFinishPopupTemp = serialization.CreateCopy<LocId?>(UserFinishPopup, hookCtx, context, false);
			}
			target.UserFinishPopup = UserFinishPopupTemp;
			LocId? TargetFinishPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(TargetFinishPopup, ref TargetFinishPopupTemp, hookCtx, false, context))
			{
				TargetFinishPopupTemp = serialization.CreateCopy<LocId?>(TargetFinishPopup, hookCtx, context, false);
			}
			target.TargetFinishPopup = TargetFinishPopupTemp;
			LocId? OthersFinishPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(OthersFinishPopup, ref OthersFinishPopupTemp, hookCtx, false, context))
			{
				OthersFinishPopupTemp = serialization.CreateCopy<LocId?>(OthersFinishPopup, hookCtx, context, false);
			}
			target.OthersFinishPopup = OthersFinishPopupTemp;
			LocId? NoneSelfPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(NoneSelfPopup, ref NoneSelfPopupTemp, hookCtx, false, context))
			{
				NoneSelfPopupTemp = serialization.CreateCopy<LocId?>(NoneSelfPopup, hookCtx, context, false);
			}
			target.NoneSelfPopup = NoneSelfPopupTemp;
			LocId? NoneOtherPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(NoneOtherPopup, ref NoneOtherPopupTemp, hookCtx, false, context))
			{
				NoneOtherPopupTemp = serialization.CreateCopy<LocId?>(NoneOtherPopup, hookCtx, context, false);
			}
			target.NoneOtherPopup = NoneOtherPopupTemp;
			LocId? NoWoundsOnUserPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(NoWoundsOnUserPopup, ref NoWoundsOnUserPopupTemp, hookCtx, false, context))
			{
				NoWoundsOnUserPopupTemp = serialization.CreateCopy<LocId?>(NoWoundsOnUserPopup, hookCtx, context, false);
			}
			target.NoWoundsOnUserPopup = NoWoundsOnUserPopupTemp;
			LocId? NoWoundsOnTargetPopupTemp = null;
			if (!serialization.TryCustomCopy<LocId?>(NoWoundsOnTargetPopup, ref NoWoundsOnTargetPopupTemp, hookCtx, false, context))
			{
				NoWoundsOnTargetPopupTemp = serialization.CreateCopy<LocId?>(NoWoundsOnTargetPopup, hookCtx, context, false);
			}
			target.NoWoundsOnTargetPopup = NoWoundsOnTargetPopupTemp;
			ushort? CurrentDoAfterTemp = null;
			if (!serialization.TryCustomCopy<ushort?>(CurrentDoAfter, ref CurrentDoAfterTemp, hookCtx, false, context))
			{
				CurrentDoAfterTemp = CurrentDoAfter;
			}
			target.CurrentDoAfter = CurrentDoAfterTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref WoundTreaterComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		WoundTreaterComponent cast = (WoundTreaterComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		WoundTreaterComponent cast = (WoundTreaterComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		WoundTreaterComponent def = (WoundTreaterComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref IComponentDelta target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		WoundTreaterComponent def = (WoundTreaterComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponentDelta)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref IComponentDelta target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override WoundTreaterComponent Instantiate()
	{
		return new WoundTreaterComponent();
	}

	IComponentDelta IComponentDelta.Instantiate()
	{
		return (IComponentDelta)(object)Instantiate();
	}

	IComponentDelta ISerializationGenerated<IComponentDelta>.Instantiate()
	{
		return (IComponentDelta)(object)Instantiate();
	}
}
