// Decompiled with JetBrains decompiler
// Type: Robust.Shared.CVars
// Assembly: Robust.Shared, Version=272.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 00043EA9-5325-44A7-AF0D-91DD061626DD
// Assembly location: C:\Users\sus\AppData\Roaming\Space Station 14\launcher\engines\Robust.Shared.dll

using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using System;

#nullable enable
namespace Robust.Shared;

[CVarDefs]
public abstract class CVars
{
  public static readonly CVarDef<int> NetMaxConnections = CVarDef.Create<int>("net.max_connections", 256 /*0x0100*/, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<int> NetPort = CVarDef.Create<int>("net.port", 1212, CVar.ARCHIVE);
  public static readonly CVarDef<int> NetSendBufferSize = CVarDef.Create<int>("net.sendbuffersize", 131071 /*0x01FFFF*/, CVar.ARCHIVE);
  public static readonly CVarDef<int> NetReceiveBufferSize = CVarDef.Create<int>("net.receivebuffersize", 131071 /*0x01FFFF*/, CVar.ARCHIVE);
  public static readonly CVarDef<int> NetPoolSize = CVarDef.Create<int>("net.pool_size", 512 /*0x0200*/, CVar.SERVER | CVar.CLIENT);
  public static readonly CVarDef<int> NetMtu = CVarDef.Create<int>("net.mtu", 700, CVar.ARCHIVE);
  public static readonly CVarDef<int> NetMtuIpv6 = CVarDef.Create<int>("net.mtu_ipv6", 1232, CVar.ARCHIVE);
  public static readonly CVarDef<bool> NetMtuExpand = CVarDef.Create<bool>("net.mtu_expand", false, CVar.ARCHIVE);
  public static readonly CVarDef<float> NetMtuExpandFrequency = CVarDef.Create<float>("net.mtu_expand_frequency", 2f, CVar.ARCHIVE);
  public static readonly CVarDef<int> NetMtuExpandFailAttempts = CVarDef.Create<int>("net.mtu_expand_fail_attempts", 5, CVar.ARCHIVE);
  public static readonly CVarDef<bool> NetVerbose = CVarDef.Create<bool>("net.verbose", false);
  public static readonly CVarDef<string> NetBindTo = CVarDef.Create<string>("net.bindto", "0.0.0.0,::", CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<bool> NetDualStack = CVarDef.Create<bool>("net.dualstack", false, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<bool> NetInterp = CVarDef.Create<bool>("net.interp", true, CVar.REPLICATED | CVar.ARCHIVE | CVar.CLIENT);
  public static readonly CVarDef<int> NetBufferSize = CVarDef.Create<int>("net.buffer_size", 2, CVar.REPLICATED | CVar.ARCHIVE | CVar.CLIENT);
  public static readonly CVarDef<int> NetMaxBufferSize = CVarDef.Create<int>("net.max_buffer_size", 512 /*0x0200*/, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<bool> NetLogging = CVarDef.Create<bool>("net.logging", false, CVar.ARCHIVE);
  public static readonly CVarDef<bool> NetPredict = CVarDef.Create<bool>("net.predict", true, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> NetPredictTickBias = CVarDef.Create<int>("net.predict_tick_bias", 1, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<float> NetPredictLagBias = CVarDef.Create<float>("net.predict_lag_bias", OperatingSystem.IsWindows() ? 0.016f : 0.0f, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> NetStateBufMergeThreshold = CVarDef.Create<int>("net.state_buf_merge_threshold", 5, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<bool> NetPVS = CVarDef.Create<bool>("net.pvs", true, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<int> NetPvsEntityGrowth = CVarDef.Create<int>("net.pvs_entity_growth", 65536 /*0x010000*/, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<int> NetPvsEntityInitial = CVarDef.Create<int>("net.pvs_entity_initial", 65536 /*0x010000*/, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<int> NetPvsEntityMax = CVarDef.Create<int>("net.pvs_entity_max", 16777216 /*0x01000000*/, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<bool> NetPvsAsync = CVarDef.Create<bool>("net.pvs_async", true, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<float> NetMaxUpdateRange = CVarDef.Create<float>("net.pvs_range", 25f, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<float> NetPvsPriorityRange = CVarDef.Create<float>("net.pvs_priority_range", 32.5f, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<int> NetForceAckThreshold = CVarDef.Create<int>("net.force_ack_threshold", 60, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<int> NetPVSEntityBudget = CVarDef.Create<int>("net.pvs_budget", 50, CVar.REPLICATED | CVar.ARCHIVE | CVar.CLIENT);
  public static readonly CVarDef<int> NetPVSEntityEnterBudget = CVarDef.Create<int>("net.pvs_enter_budget", 200, CVar.REPLICATED | CVar.ARCHIVE | CVar.CLIENT);
  public static readonly CVarDef<int> NetPVSEntityExitBudget = CVarDef.Create<int>("net.pvs_exit_budget", 75, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> NetPvsCompressLevel = CVarDef.Create<int>("net.pvs_compress_level", 3, CVar.ARCHIVE);
  public static readonly CVarDef<bool> NetLogLateMsg = CVarDef.Create<bool>("net.log_late_msg", true);
  public static readonly CVarDef<int> NetTickrate = CVarDef.Create<int>("net.tickrate", 30, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<int> NetTimeStartOffset = CVarDef.Create<int>("net.time_start_offset", 0, CVar.SERVERONLY);
  public static readonly CVarDef<float> ConnectionTimeout = CVarDef.Create<float>("net.connection_timeout", 25f, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<float> ResendHandshakeInterval = CVarDef.Create<float>("net.handshake_interval", 3f, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> MaximumHandshakeAttempts = CVarDef.Create<int>("net.handshake_attempts", 5, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<bool> NetEncrypt = CVarDef.Create<bool>("net.encrypt", true, CVar.CLIENTONLY);
  public static readonly CVarDef<bool> NetUPnP = CVarDef.Create<bool>("net.upnp", false, CVar.SERVERONLY);
  public static readonly CVarDef<string> NetLidgrenAppIdentifier = CVarDef.Create<string>("net.lidgren_app_identifier", "RobustToolbox");
  public static readonly CVarDef<float> NetFakeLoss = CVarDef.Create<float>("net.fakeloss", 0.0f, CVar.CHEAT);
  public static readonly CVarDef<float> NetFakeLagMin = CVarDef.Create<float>("net.fakelagmin", 0.0f, CVar.CHEAT);
  public static readonly CVarDef<float> NetFakeLagRand = CVarDef.Create<float>("net.fakelagrand", 0.0f, CVar.CHEAT);
  public static readonly CVarDef<float> NetFakeDuplicates = CVarDef.Create<float>("net.fakeduplicates", 0.0f, CVar.CHEAT);
  public static readonly CVarDef<float> NetHappyEyeballsDelay = CVarDef.Create<float>("net.happy_eyeballs_delay", 0.025f, CVar.CLIENTONLY);
  public static readonly CVarDef<bool> NetLidgrenLogWarning = CVarDef.Create<bool>("net.lidgren_log_warning", true);
  public static readonly CVarDef<bool> NetLidgrenLogError = CVarDef.Create<bool>("net.lidgren_log_error", true);
  public static readonly CVarDef<bool> NetEncryptionThread = CVarDef.Create<bool>("net.encryption_thread", true);
  public static readonly CVarDef<int> NetEncryptionThreadChannelSize = CVarDef.Create<int>("net.encryption_thread_channel_size", 16 /*0x10*/);
  public static readonly CVarDef<bool> NetHWId = CVarDef.Create<bool>("net.hwid", true, CVar.SERVERONLY);
  public static readonly CVarDef<bool> TransferHttp = CVarDef.Create<bool>("transfer.http", false, CVar.SERVERONLY);
  public static readonly CVarDef<string> TransferHttpEndpoint = CVarDef.Create<string>("transfer.http_endpoint", "http://localhost:1212/", CVar.SERVERONLY);
  public static readonly CVarDef<int> TransferStreamLimit = CVarDef.Create<int>("transfer.stream_limit", 10, CVar.SERVERONLY);
  internal static readonly CVarDef<bool> TransferArtificialDelay = CVarDef.Create<bool>("transfer.artificial_delay", false);
  public static readonly CVarDef<int> SysWinTickPeriod = CVarDef.Create<int>("sys.win_tick_period", 3, CVar.SERVERONLY);
  public static readonly CVarDef<bool> SysProfileOpt = CVarDef.Create<bool>("sys.profile_opt", true);
  public static readonly CVarDef<int> SysGameThreadStackSize = CVarDef.Create<int>("sys.game_thread_stack_size", 8388608 /*0x800000*/);
  public static readonly CVarDef<int> SysGameThreadPriority = CVarDef.Create<int>("sys.game_thread_priority", 3);
  public static readonly CVarDef<bool> SysGCCollectStart = CVarDef.Create<bool>("sys.gc_collect_start", true);
  public static readonly CVarDef<bool> SysPreciseSleep = CVarDef.Create<bool>("sys.precise_sleep", true);
  public static readonly CVarDef<bool> MetricsEnabled = CVarDef.Create<bool>("metrics.enabled", false, CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsHost = CVarDef.Create<string>("metrics.host", "localhost", CVar.SERVERONLY);
  public static readonly CVarDef<int> MetricsPort = CVarDef.Create<int>("metrics.port", 44880, CVar.SERVERONLY);
  public static readonly CVarDef<float> MetricsUpdateInterval = CVarDef.Create<float>("metrics.update_interval", 0.0f, CVar.SERVERONLY);
  public static readonly CVarDef<bool> MetricsRuntime = CVarDef.Create<bool>("metrics.runtime", true, CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeGc = CVarDef.Create<string>("metrics.runtime_gc", "Counters", CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeGcHistogram = CVarDef.Create<string>("metrics.runtime_gc_histogram", "0.5,1.0,2.0,4.0,6.0,10.0,15.0,20.0", CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeContention = CVarDef.Create<string>("metrics.runtime_contention", "Counters", CVar.SERVERONLY);
  public static readonly CVarDef<int> MetricsRuntimeContentionSampleRate = CVarDef.Create<int>("metrics.runtime_contention_sample_rate", 50, CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeThreadPool = CVarDef.Create<string>("metrics.runtime_thread_pool", "Counters", CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeThreadPoolQueueHistogram = CVarDef.Create<string>("metrics.runtime_thread_pool_queue_histogram", "0,10,30,60,120,180", CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeJit = CVarDef.Create<string>("metrics.runtime_jit", "Counters", CVar.SERVERONLY);
  public static readonly CVarDef<int> MetricsRuntimeJitSampleRate = CVarDef.Create<int>("metrics.runtime_jit_sample_rate", 10, CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeException = CVarDef.Create<string>("metrics.runtime_exception", "Counters", CVar.SERVERONLY);
  public static readonly CVarDef<string> MetricsRuntimeSocket = CVarDef.Create<string>("metrics.runtime_socket", "Counters", CVar.SERVERONLY);
  public static readonly CVarDef<bool> StatusEnabled = CVarDef.Create<bool>("status.enabled", true, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<string> StatusBind = CVarDef.Create<string>("status.bind", "", CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<int> StatusMaxConnections = CVarDef.Create<int>("status.max_connections", 5, CVar.SERVERONLY);
  public static readonly CVarDef<string> StatusConnectAddress = CVarDef.Create<string>("status.connectaddress", "", CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<string> StatusPrivacyPolicyLink = CVarDef.Create<string>("status.privacy_policy_link", "https://example.com/privacy", CVar.SERVER | CVar.REPLICATED);
  public static readonly CVarDef<string> StatusPrivacyPolicyIdentifier = CVarDef.Create<string>("status.privacy_policy_identifier", "", CVar.SERVER | CVar.REPLICATED);
  public static readonly CVarDef<string> StatusPrivacyPolicyVersion = CVarDef.Create<string>("status.privacy_policy_version", "", CVar.SERVER | CVar.REPLICATED);
  public static readonly CVarDef<string> BuildEngineVersion = CVarDef.Create<string>("build.engine_version", typeof (CVars).Assembly.GetName().Version?.ToString(3) ?? string.Empty);
  public static readonly CVarDef<string> BuildForkId = CVarDef.Create<string>("build.fork_id", "");
  public static readonly CVarDef<string> BuildVersion = CVarDef.Create<string>("build.version", "");
  public static readonly CVarDef<string> BuildDownloadUrl = CVarDef.Create<string>("build.download_url", string.Empty);
  public static readonly CVarDef<string> BuildManifestUrl = CVarDef.Create<string>("build.manifest_url", string.Empty);
  public static readonly CVarDef<string> BuildManifestDownloadUrl = CVarDef.Create<string>("build.manifest_download_url", string.Empty);
  public static readonly CVarDef<string> BuildHash = CVarDef.Create<string>("build.hash", "");
  public static readonly CVarDef<string> BuildManifestHash = CVarDef.Create<string>("build.manifest_hash", "");
  public static readonly CVarDef<string> EntitiesCategoryFilter = CVarDef.Create<string>("build.entities_category_filter", "");
  public static readonly CVarDef<string> WatchdogToken = CVarDef.Create<string>("watchdog.token", "", CVar.SERVERONLY | CVar.CONFIDENTIAL);
  public static readonly CVarDef<string> WatchdogKey = CVarDef.Create<string>("watchdog.key", "", CVar.SERVERONLY);
  public static readonly CVarDef<string> WatchdogBaseUrl = CVarDef.Create<string>("watchdog.baseUrl", "http://localhost:5000", CVar.SERVERONLY);
  [Obsolete("Use net.max_connections instead")]
  public static readonly CVarDef<int> GameMaxPlayers = CVarDef.Create<int>("game.maxplayers", 0, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<string> GameHostName = CVarDef.Create<string>("game.hostname", "MyServer", CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<string> GameDesc = CVarDef.Create<string>("game.desc", "Just another server, don't mind me!", CVar.SERVERONLY);
  public static readonly CVarDef<bool> GameDeleteEmptyGrids = CVarDef.Create<bool>("game.delete_empty_grids", true, CVar.SERVER | CVar.ARCHIVE);
  public static readonly CVarDef<bool> GameAutoPauseEmpty = CVarDef.Create<bool>("game.auto_pause_empty", true, CVar.SERVERONLY);
  public static readonly CVarDef<float> GameTimeScale = CVarDef.Create<float>("game.time_scale", 1f, CVar.SERVER | CVar.REPLICATED);
  public static readonly CVarDef<bool> LogEnabled = CVarDef.Create<bool>("log.enabled", true, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<string> LogPath = CVarDef.Create<string>("log.path", "logs", CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<string> LogFormat = CVarDef.Create<string>("log.format", "log_%(date)s-T%(time)s.txt", CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<Robust.Shared.Log.LogLevel> LogLevel = CVarDef.Create<Robust.Shared.Log.LogLevel>("log.level", Robust.Shared.Log.LogLevel.Info, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<bool> LogRuntimeLog = CVarDef.Create<bool>("log.runtimelog", true, CVar.ARCHIVE | CVar.SERVERONLY);
  public static readonly CVarDef<float> MaxLightRadius = CVarDef.Create<float>("light.max_radius", 32.1f, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> MaxLightCount = CVarDef.Create<int>("light.max_light_count", 2048 /*0x0800*/, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> MaxOccluderCount = CVarDef.Create<int>("light.max_occluder_count", 2048 /*0x0800*/, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<float> LightResolutionScale = CVarDef.Create<float>("light.resolution_scale", 0.5f, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<int> MaxShadowcastingLights = CVarDef.Create<int>("light.max_shadowcasting_lights", 128 /*0x80*/, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<bool> LightSoftShadows = CVarDef.Create<bool>("light.soft_shadows", true, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<bool> LightBlur = CVarDef.Create<bool>("light.blur", true, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<float> LightBlurFactor = CVarDef.Create<float>("light.blur_factor", 1f / 1000f, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<float> LookupEnlargementRange = CVarDef.Create<float>("lookup.enlargement_range", 10f, CVar.CHEAT | CVar.REPLICATED | CVar.ARCHIVE);
  public static readonly CVarDef<bool> LokiEnabled = CVarDef.Create<bool>("loki.enabled", false, CVar.SERVERONLY);
  public static readonly CVarDef<string> LokiName = CVarDef.Create<string>("loki.name", "", CVar.SERVERONLY);
  public static readonly CVarDef<string> LokiAddress = CVarDef.Create<string>("loki.address", "", CVar.SERVERONLY);
  public static readonly CVarDef<string> LokiUsername = CVarDef.Create<string>("loki.username", "", CVar.SERVERONLY);
  public static readonly CVarDef<string> LokiPassword = CVarDef.Create<string>("loki.password", "", CVar.SERVERONLY);
  public static readonly CVarDef<int> AuthMode = CVarDef.Create<int>("auth.mode", 1, CVar.SERVERONLY);
  public static readonly CVarDef<bool> AuthAllowLocal = CVarDef.Create<bool>("auth.allowlocal", true, CVar.SERVERONLY);
  public static readonly CVarDef<string> AuthServer = CVarDef.Create<string>("auth.server", "https://auth.spacestation14.com/", CVar.SERVERONLY);
  public static readonly CVarDef<double> RenderSpriteDirectionBias = CVarDef.Create<double>("render.sprite_direction_bias", -0.05, CVar.ARCHIVE | CVar.CLIENTONLY);
  public static readonly CVarDef<string> RenderFOVColor;
  public static readonly CVarDef<bool> RenderTileEdges;
  public static readonly CVarDef<int> DoubleClickDelay;
  public static readonly CVarDef<int> DoubleClickRange;
  public static readonly CVarDef<bool> DisplayVSync;
  public static readonly CVarDef<int> DisplayMaxFPS;
  public static readonly CVarDef<int> DisplayWindowMode;
  public static readonly CVarDef<int> DisplayWidth;
  public static readonly CVarDef<int> DisplayHeight;
  public static readonly CVarDef<float> DisplayUIScale;
  public static readonly CVarDef<int> DisplayRenderer;
  public static readonly CVarDef<bool> DisplayCompat;
  public static readonly CVarDef<int> DisplayOpenGLVersion;
  public static readonly CVarDef<bool> DisplayAngle;
  public static readonly CVarDef<bool> DisplayAngleCustomSwapChain;
  public static readonly CVarDef<bool> DisplayAngleForceEs2;
  public static readonly CVarDef<bool> DisplayAngleForce10_0;
  public static readonly CVarDef<bool> DisplayAngleDxgi1;
  public static readonly CVarDef<string> DisplayAdapter;
  public static readonly CVarDef<int> DisplayGpuPreference;
  public static readonly CVarDef<bool> DisplayEgl;
  public static readonly CVarDef<bool> DisplayAngleEs3On10_0;
  public static readonly CVarDef<int> DisplayFontDpi;
  public static readonly CVarDef<string> DisplayOGLOverrideVersion;
  public static readonly CVarDef<bool> DisplayOGLCheckErrors;
  public static readonly CVarDef<bool> DisplayForceSyncWindows;
  public static readonly CVarDef<bool> DisplayThreadWindowBlit;
  public static readonly CVarDef<bool> DisplayThreadUnlockBeforeSwap;
  public static readonly CVarDef<int> DisplayInputBufferSize;
  public static readonly CVarDef<bool> DisplayWin32Experience;
  public static readonly CVarDef<string> DisplayWindowIconSet;
  public static readonly CVarDef<string> DisplaySplashLogo;
  public static readonly CVarDef<bool> DisplayUSQWERTYHotkeys;
  public static readonly CVarDef<string> DisplayWindowingApi;
  public static readonly CVarDef<bool> DisplayWin11ImmersiveDarkMode;
  public static readonly CVarDef<bool> DisplayThreadWindowApi;
  public static readonly CVarDef<int> AudioDefaultConcurrent;
  public static readonly CVarDef<int> AudioAttenuation;
  public static readonly CVarDef<string> AudioDevice;
  public static readonly CVarDef<float> AudioMasterVolume;
  public static readonly CVarDef<float> AudioRaycastLength;
  public static readonly CVarDef<float> AudioEndBuffer;
  public static readonly CVarDef<int> AudioTickRate;
  public static readonly CVarDef<float> AudioZOffset;
  public static readonly CVarDef<string> PlayerName;
  public static readonly CVarDef<int> TargetMinimumTickrate;
  public static readonly CVarDef<bool> GenerateGridFixtures;
  public static readonly CVarDef<bool> GridSplitting;
  public static readonly CVarDef<float> GridFixtureEnlargement;
  public static readonly CVarDef<float> AngularSleepTolerance;
  public static readonly CVarDef<float> LinearSleepTolerance;
  public static readonly CVarDef<bool> SleepAllowed;
  public static readonly CVarDef<float> TimeToSleep;
  public static readonly CVarDef<int> PositionIterations;
  public static readonly CVarDef<int> VelocityIterations;
  public static readonly CVarDef<bool> WarmStarting;
  public static readonly CVarDef<bool> AutoClearForces;
  public static readonly CVarDef<float> VelocityThreshold;
  public static readonly CVarDef<float> Baumgarte;
  public static readonly CVarDef<float> MaxLinearCorrection;
  public static readonly CVarDef<float> MaxAngularCorrection;
  public static readonly CVarDef<float> MaxLinVelocity;
  public static readonly CVarDef<float> MaxAngVelocity;
  public static readonly CVarDef<string> InterfaceTheme;
  public static readonly CVarDef<bool> InterfaceAudio;
  public static readonly CVarDef<int> ResAutoScaleUpperX;
  public static readonly CVarDef<int> ResAutoScaleUpperY;
  public static readonly CVarDef<int> ResAutoScaleLowX;
  public static readonly CVarDef<int> ResAutoScaleLowY;
  public static readonly CVarDef<float> ResAutoScaleMin;
  public static readonly CVarDef<bool> ResAutoScaleEnabled;
  public static readonly CVarDef<bool> DiscordEnabled;
  public static readonly CVarDef<string> DiscordRichPresenceMainIconId;
  public static readonly CVarDef<string> DiscordRichPresenceSecondIconId;
  public static readonly CVarDef<bool> ResCheckPathCasing;
  public static readonly CVarDef<bool> ResTexturePreloadingEnabled;
  public static readonly CVarDef<int> ResRSIAtlasSize;
  public static readonly CVarDef<bool> ResTexturePreloadCache;
  public static readonly CVarDef<int> ResStreamSeekMode;
  public static readonly CVarDef<bool> ResPrototypeReloadWatch;
  public static readonly CVarDef<bool> ResCheckBadFileExtensions;
  public static readonly CVarDef<int> DebugTargetFps;
  public static readonly CVarDef<float> MidiVolume;
  public static readonly CVarDef<int> MidiParallelism;
  public static readonly CVarDef<bool> HubAdvertise;
  public static readonly CVarDef<string> HubTags;
  public static readonly CVarDef<string> HubUrls;
  public static readonly CVarDef<string> HubServerUrl;
  public static readonly CVarDef<string> HubIpifyUrl;
  public static readonly CVarDef<int> HubAdvertiseInterval;
  public static readonly CVarDef<bool> AczStreamCompress;
  public static readonly CVarDef<int> AczStreamCompressLevel;
  public static readonly CVarDef<bool> AczBlobCompress;
  public static readonly CVarDef<int> AczBlobCompressLevel;
  public static readonly CVarDef<int> AczBlobCompressSaveThreshold;
  public static readonly CVarDef<bool> AczManifestCompress;
  public static readonly CVarDef<int> AczManifestCompressLevel;
  public static readonly CVarDef<float> ConCompletionDelay;
  public static readonly CVarDef<int> ConCompletionCount;
  public static readonly CVarDef<int> ConCompletionMargin;
  public static readonly CVarDef<int> ConMaxEntries;
  public static readonly CVarDef<int> ThreadParallelCount;
  public static readonly CVarDef<bool> ProfEnabled;
  public static readonly CVarDef<int> ProfBufferSize;
  public static readonly CVarDef<int> ProfIndexSize;
  public static readonly CVarDef<string> ReplayDirectory;
  public static readonly CVarDef<long> ReplayMaxCompressedSize;
  public static readonly CVarDef<long> ReplayMaxUncompressedSize;
  public static readonly CVarDef<long> ReplayServerGCSizeThreshold;
  public static readonly CVarDef<int> ReplayTickBatchSize;
  public static readonly CVarDef<int> ReplayWriteChannelSize;
  public static readonly CVarDef<bool> ReplayServerRecordingEnabled;
  public static readonly CVarDef<bool> ReplayClientRecordingEnabled;
  public static readonly CVarDef<int> ReplayMaxScrubTime;
  public static readonly CVarDef<int> ReplaySkipThreshold;
  public static readonly CVarDef<int> CheckpointMinInterval;
  public static readonly CVarDef<int> CheckpointInterval;
  public static readonly CVarDef<int> CheckpointEntitySpawnThreshold;
  public static readonly CVarDef<int> CheckpointEntityStateThreshold;
  public static readonly CVarDef<bool> ReplayDynamicalScrubbing;
  public static readonly CVarDef<bool> ReplayMakeContentBundle;
  public static readonly CVarDef<bool> ReplayIgnoreErrors;
  public static readonly CVarDef<bool> CfgCheckUnused;
  internal static readonly CVarDef<string> CfgRollbackData;
  public static readonly CVarDef<bool> ResourceUploadingEnabled;
  public static readonly CVarDef<float> ResourceUploadingLimitMb;
  public static readonly CVarDef<bool> LaunchLauncher;
  public static readonly CVarDef<bool> LaunchContentBundle;
  public static readonly CVarDef<int> ToolshedNearbyLimit;
  public static readonly CVarDef<int> ToolshedNearbyEntitiesLimit;
  public static readonly CVarDef<int> ToolshedPrototypesAutocompleteLimit;
  public static readonly CVarDef<string> LocCultureName;
  public static readonly CVarDef<string> XamlHotReloadMarkerName;
  public static readonly CVarDef<bool> UIXamlJitPreload;
  public static readonly CVarDef<bool> FontSystem;
  public static readonly CVarDef<bool> FontWindowsDownloadable;
  public static readonly CVarDef<bool> LoadingShowBar;
  private const bool DefaultShowDebug = false;
  public static readonly CVarDef<bool> LoadingShowDebug;

  protected CVars() => throw new InvalidOperationException("This class must not be instantiated");

  static CVars()
  {
    Color black = Color.Black;
    CVars.RenderFOVColor = CVarDef.Create<string>("render.fov_color", ((Color) ref black).ToHex(), CVar.SERVER | CVar.REPLICATED);
    CVars.RenderTileEdges = CVarDef.Create<bool>("render.tile_edges", true, CVar.CLIENTONLY);
    CVars.DoubleClickDelay = CVarDef.Create<int>("controls.double_click_delay", 250, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DoubleClickRange = CVarDef.Create<int>("controls.double_click_range", 10, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DisplayVSync = CVarDef.Create<bool>("display.vsync", true, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DisplayMaxFPS = CVarDef.Create<int>("display.max_fps", 0, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DisplayWindowMode = CVarDef.Create<int>("display.windowmode", 0, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DisplayWidth = CVarDef.Create<int>("display.width", 1280 /*0x0500*/, CVar.CLIENTONLY);
    CVars.DisplayHeight = CVarDef.Create<int>("display.height", 720, CVar.CLIENTONLY);
    CVars.DisplayUIScale = CVarDef.Create<float>("display.uiScale", 0.0f, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DisplayRenderer = CVarDef.Create<int>("display.renderer", 0, CVar.CLIENTONLY);
    CVars.DisplayCompat = CVarDef.Create<bool>("display.compat", false, CVar.CLIENTONLY);
    CVars.DisplayOpenGLVersion = CVarDef.Create<int>("display.opengl_version", 0, CVar.CLIENTONLY);
    CVars.DisplayAngle = CVarDef.Create<bool>("display.angle", false, CVar.CLIENTONLY);
    CVars.DisplayAngleCustomSwapChain = CVarDef.Create<bool>("display.angle_custom_swap_chain", true, CVar.CLIENTONLY);
    CVars.DisplayAngleForceEs2 = CVarDef.Create<bool>("display.angle_force_es2", false, CVar.CLIENTONLY);
    CVars.DisplayAngleForce10_0 = CVarDef.Create<bool>("display.angle_force_10_0", false, CVar.CLIENTONLY);
    CVars.DisplayAngleDxgi1 = CVarDef.Create<bool>("display.angle_dxgi1", false, CVar.CLIENTONLY);
    CVars.DisplayAdapter = CVarDef.Create<string>("display.adapter", "", CVar.CLIENTONLY);
    CVars.DisplayGpuPreference = CVarDef.Create<int>("display.gpu_preference", 2, CVar.CLIENTONLY);
    CVars.DisplayEgl = CVarDef.Create<bool>("display.egl", false, CVar.CLIENTONLY);
    CVars.DisplayAngleEs3On10_0 = CVarDef.Create<bool>("display.angle_es3_on_10_0", true, CVar.CLIENTONLY);
    CVars.DisplayFontDpi = CVarDef.Create<int>("display.fontdpi", 96 /*0x60*/, CVar.CLIENTONLY);
    CVars.DisplayOGLOverrideVersion = CVarDef.Create<string>("display.ogl_override_version", string.Empty, CVar.CLIENTONLY);
    CVars.DisplayOGLCheckErrors = CVarDef.Create<bool>("display.ogl_check_errors", false, CVar.CLIENTONLY);
    CVars.DisplayForceSyncWindows = CVarDef.Create<bool>("display.force_sync_windows", true, CVar.CLIENTONLY);
    CVars.DisplayThreadWindowBlit = CVarDef.Create<bool>("display.thread_window_blit", true, CVar.CLIENTONLY);
    CVars.DisplayThreadUnlockBeforeSwap = CVarDef.Create<bool>("display.thread_unlock_before_swap", false, CVar.CLIENTONLY);
    CVars.DisplayInputBufferSize = CVarDef.Create<int>("display.input_buffer_size", 32 /*0x20*/, CVar.CLIENTONLY);
    CVars.DisplayWin32Experience = CVarDef.Create<bool>("display.win32_experience", false, CVar.CLIENTONLY);
    CVars.DisplayWindowIconSet = CVarDef.Create<string>("display.window_icon_set", "", CVar.CLIENTONLY);
    CVars.DisplaySplashLogo = CVarDef.Create<string>("display.splash_logo", "", CVar.CLIENTONLY);
    CVars.DisplayUSQWERTYHotkeys = CVarDef.Create<bool>("display.use_US_QWERTY_hotkeys", false, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DisplayWindowingApi = CVarDef.Create<string>("display.windowing_api", "sdl3", CVar.CLIENTONLY);
    CVars.DisplayWin11ImmersiveDarkMode = CVarDef.Create<bool>("display.win11_immersive_dark_mode", true, CVar.CLIENTONLY);
    CVars.DisplayThreadWindowApi = CVarDef.Create<bool>("display.thread_window_api", false, CVar.CLIENTONLY);
    CVars.AudioDefaultConcurrent = CVarDef.Create<int>("audio.default_concurrent", 16 /*0x10*/, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.AudioAttenuation = CVarDef.Create<int>("audio.attenuation", 16 /*0x10*/, CVar.REPLICATED | CVar.ARCHIVE);
    CVars.AudioDevice = CVarDef.Create<string>("audio.device", string.Empty, CVar.CLIENTONLY);
    CVars.AudioMasterVolume = CVarDef.Create<float>("audio.mastervolume", 0.5f, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.AudioRaycastLength = CVarDef.Create<float>("audio.raycast_length", 15f, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.AudioEndBuffer = CVarDef.Create<float>("audio.end_buffer", 0.01f, CVar.REPLICATED);
    CVars.AudioTickRate = CVarDef.Create<int>("audio.tick_rate", 30, CVar.CLIENTONLY);
    CVars.AudioZOffset = CVarDef.Create<float>("audio.z_offset", -5f, CVar.REPLICATED);
    CVars.PlayerName = CVarDef.Create<string>("player.name", "JoeGenero", CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.TargetMinimumTickrate = CVarDef.Create<int>("physics.target_minimum_tickrate", 60, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
    CVars.GenerateGridFixtures = CVarDef.Create<bool>("physics.grid_fixtures", true, CVar.REPLICATED);
    CVars.GridSplitting = CVarDef.Create<bool>("physics.grid_splitting", true, CVar.ARCHIVE);
    CVars.GridFixtureEnlargement = CVarDef.Create<float>("physics.grid_fixture_enlargement", -0.01f, CVar.REPLICATED | CVar.ARCHIVE);
    CVars.AngularSleepTolerance = CVarDef.Create<float>("physics.angsleeptol", (float) Math.PI / 600f);
    CVars.LinearSleepTolerance = CVarDef.Create<float>("physics.linsleeptol", 0.01f);
    CVars.SleepAllowed = CVarDef.Create<bool>("physics.sleepallowed", true);
    CVars.TimeToSleep = CVarDef.Create<float>("physics.timetosleep", 0.2f);
    CVars.PositionIterations = CVarDef.Create<int>("physics.positer", 3);
    CVars.VelocityIterations = CVarDef.Create<int>("physics.veliter", 8);
    CVars.WarmStarting = CVarDef.Create<bool>("physics.warmstart", true);
    CVars.AutoClearForces = CVarDef.Create<bool>("physics.autoclearforces", true);
    CVars.VelocityThreshold = CVarDef.Create<float>("physics.velocitythreshold", 0.5f);
    CVars.Baumgarte = CVarDef.Create<float>("physics.baumgarte", 0.2f);
    CVars.MaxLinearCorrection = CVarDef.Create<float>("physics.maxlinearcorrection", 0.2f);
    CVars.MaxAngularCorrection = CVarDef.Create<float>("physics.maxangularcorrection", 0.139626354f);
    CVars.MaxLinVelocity = CVarDef.Create<float>("physics.maxlinvelocity", 400f, CVar.SERVER | CVar.REPLICATED);
    CVars.MaxAngVelocity = CVarDef.Create<float>("physics.maxangvelocity", 15f);
    CVars.InterfaceTheme = CVarDef.Create<string>("interface.theme", "", CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.InterfaceAudio = CVarDef.Create<bool>("interface.audio", true, CVar.REPLICATED);
    CVars.ResAutoScaleUpperX = CVarDef.Create<int>("interface.resolutionAutoScaleUpperCutoffX", 1080, CVar.CLIENTONLY);
    CVars.ResAutoScaleUpperY = CVarDef.Create<int>("interface.resolutionAutoScaleUpperCutoffY", 720, CVar.CLIENTONLY);
    CVars.ResAutoScaleLowX = CVarDef.Create<int>("interface.resolutionAutoScaleLowerCutoffX", 520, CVar.CLIENTONLY);
    CVars.ResAutoScaleLowY = CVarDef.Create<int>("interface.resolutionAutoScaleLowerCutoffY", 520, CVar.CLIENTONLY);
    CVars.ResAutoScaleMin = CVarDef.Create<float>("interface.resolutionAutoScaleMinimum", 0.5f, CVar.CLIENTONLY);
    CVars.ResAutoScaleEnabled = CVarDef.Create<bool>("interface.resolutionAutoScaleEnabled", true, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DiscordEnabled = CVarDef.Create<bool>("discord.enabled", true, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.DiscordRichPresenceMainIconId = CVarDef.Create<string>("discord.rich_main_icon_id", "devstation", CVar.SERVER | CVar.REPLICATED);
    CVars.DiscordRichPresenceSecondIconId = CVarDef.Create<string>("discord.rich_second_icon_id", "logo", CVar.SERVER | CVar.REPLICATED);
    CVars.ResCheckPathCasing = CVarDef.Create<bool>("res.checkpathcasing", false);
    CVars.ResTexturePreloadingEnabled = CVarDef.Create<bool>("res.texturepreloadingenabled", true, CVar.CLIENTONLY);
    CVars.ResRSIAtlasSize = CVarDef.Create<int>("res.rsi_atlas_size", 12288 /*0x3000*/, CVar.CLIENTONLY);
    CVars.ResTexturePreloadCache = CVarDef.Create<bool>("res.texture_preload_cache", true, CVar.CLIENTONLY);
    CVars.ResStreamSeekMode = CVarDef.Create<int>("res.stream_seek_mode", 0);
    CVars.ResPrototypeReloadWatch = CVarDef.Create<bool>("res.prototype_reload_watch", true, CVar.CLIENTONLY);
    CVars.ResCheckBadFileExtensions = CVarDef.Create<bool>("res.check_bad_file_extensions", true);
    CVars.DebugTargetFps = CVarDef.Create<int>("debug.target_fps", 60, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.MidiVolume = CVarDef.Create<float>("midi.volume", 0.5f, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.MidiParallelism = CVarDef.Create<int>("midi.parallelism", 1, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.HubAdvertise = CVarDef.Create<bool>("hub.advertise", false, CVar.SERVERONLY);
    CVars.HubTags = CVarDef.Create<string>("hub.tags", "", CVar.ARCHIVE | CVar.SERVERONLY);
    CVars.HubUrls = CVarDef.Create<string>("hub.hub_urls", "https://hub.spacestation14.com/", CVar.SERVERONLY);
    CVars.HubServerUrl = CVarDef.Create<string>("hub.server_url", "", CVar.SERVERONLY);
    CVars.HubIpifyUrl = CVarDef.Create<string>("hub.ipify_url", "https://api.ipify.org?format=json", CVar.SERVERONLY);
    CVars.HubAdvertiseInterval = CVarDef.Create<int>("hub.advertise_interval", 120, CVar.SERVERONLY);
    CVars.AczStreamCompress = CVarDef.Create<bool>("acz.stream_compress", false, CVar.SERVERONLY);
    CVars.AczStreamCompressLevel = CVarDef.Create<int>("acz.stream_compress_level", 3, CVar.SERVERONLY);
    CVars.AczBlobCompress = CVarDef.Create<bool>("acz.blob_compress", true, CVar.SERVERONLY);
    CVars.AczBlobCompressLevel = CVarDef.Create<int>("acz.blob_compress_level", 14, CVar.SERVERONLY);
    CVars.AczBlobCompressSaveThreshold = CVarDef.Create<int>("acz.blob_compress_save_threshold", 14, CVar.SERVERONLY);
    CVars.AczManifestCompress = CVarDef.Create<bool>("acz.manifest_compress", true, CVar.SERVERONLY);
    CVars.AczManifestCompressLevel = CVarDef.Create<int>("acz.manifest_compress_level", 14, CVar.SERVERONLY);
    CVars.ConCompletionDelay = CVarDef.Create<float>("con.completion_delay", 0.0f, CVar.CLIENTONLY);
    CVars.ConCompletionCount = CVarDef.Create<int>("con.completion_count", 15, CVar.CLIENTONLY);
    CVars.ConCompletionMargin = CVarDef.Create<int>("con.completion_margin", 3, CVar.CLIENTONLY);
    CVars.ConMaxEntries = CVarDef.Create<int>("con.max_entries", 3000, CVar.CLIENTONLY);
    CVars.ThreadParallelCount = CVarDef.Create<int>("thread.parallel_count", 0);
    CVars.ProfEnabled = CVarDef.Create<bool>("prof.enabled", false);
    CVars.ProfBufferSize = CVarDef.Create<int>("prof.buffer_size", 8192 /*0x2000*/);
    CVars.ProfIndexSize = CVarDef.Create<int>("prof.index_size", 128 /*0x80*/);
    CVars.ReplayDirectory = CVarDef.Create<string>("replay.directory", "replays", CVar.ARCHIVE);
    CVars.ReplayMaxCompressedSize = CVarDef.Create<long>("replay.max_compressed_size", 524288L /*0x080000*/, CVar.ARCHIVE);
    CVars.ReplayMaxUncompressedSize = CVarDef.Create<long>("replay.max_uncompressed_size", 1048576L /*0x100000*/, CVar.ARCHIVE);
    CVars.ReplayServerGCSizeThreshold = CVarDef.Create<long>("replay.server_gc_size_threshold", 51200L);
    CVars.ReplayTickBatchSize = CVarDef.Create<int>("replay.replay_tick_batchSize", 1024 /*0x0400*/, CVar.ARCHIVE);
    CVars.ReplayWriteChannelSize = CVarDef.Create<int>("replay.write_channel_size", 5);
    CVars.ReplayServerRecordingEnabled = CVarDef.Create<bool>("replay.server_recording_enabled", true, CVar.ARCHIVE | CVar.SERVERONLY);
    CVars.ReplayClientRecordingEnabled = CVarDef.Create<bool>("replay.client_recording_enabled", true, CVar.SERVER | CVar.REPLICATED | CVar.ARCHIVE);
    CVars.ReplayMaxScrubTime = CVarDef.Create<int>("replay.max_scrub_time", 10);
    CVars.ReplaySkipThreshold = CVarDef.Create<int>("replay.skip_threshold", 30);
    CVars.CheckpointMinInterval = CVarDef.Create<int>("replay.checkpoint_min_interval", 60);
    CVars.CheckpointInterval = CVarDef.Create<int>("replay.checkpoint_interval", 500);
    CVars.CheckpointEntitySpawnThreshold = CVarDef.Create<int>("replay.checkpoint_entity_spawn_threshold", 1000);
    CVars.CheckpointEntityStateThreshold = CVarDef.Create<int>("replay.checkpoint_entity_state_threshold", 30000);
    CVars.ReplayDynamicalScrubbing = CVarDef.Create<bool>("replay.dynamical_scrubbing", true);
    CVars.ReplayMakeContentBundle = CVarDef.Create<bool>("replay.make_content_bundle", true);
    CVars.ReplayIgnoreErrors = CVarDef.Create<bool>("replay.ignore_errors", false, CVar.CLIENTONLY);
    CVars.CfgCheckUnused = CVarDef.Create<bool>("cfg.check_unused", true);
    CVars.CfgRollbackData = CVarDef.Create<string>("cfg.rollback_data", "", CVar.ARCHIVE);
    CVars.ResourceUploadingEnabled = CVarDef.Create<bool>("netres.enabled", true, CVar.SERVER | CVar.REPLICATED);
    CVars.ResourceUploadingLimitMb = CVarDef.Create<float>("netres.limit", 3f, CVar.SERVER | CVar.REPLICATED);
    CVars.LaunchLauncher = CVarDef.Create<bool>("launch.launcher", false, CVar.CLIENTONLY);
    CVars.LaunchContentBundle = CVarDef.Create<bool>("launch.content_bundle", false, CVar.CLIENTONLY);
    CVars.ToolshedNearbyLimit = CVarDef.Create<int>("toolshed.nearby_limit", 200, CVar.SERVER | CVar.REPLICATED);
    CVars.ToolshedNearbyEntitiesLimit = CVarDef.Create<int>("toolshed.nearby_entities_limit", 5, CVar.SERVER | CVar.REPLICATED);
    CVars.ToolshedPrototypesAutocompleteLimit = CVarDef.Create<int>("toolshed.prototype_autocomplete_limit", 256 /*0x0100*/, CVar.SERVER | CVar.REPLICATED);
    CVars.LocCultureName = CVarDef.Create<string>("loc.culture_name", "en-US", CVar.ARCHIVE);
    CVars.XamlHotReloadMarkerName = CVarDef.Create<string>("ui.xaml_hot_reload_marker_name", "SpaceStation14.slnx", CVar.CLIENTONLY);
    CVars.UIXamlJitPreload = CVarDef.Create<bool>("ui.xaml_jit_preload", false, CVar.CLIENTONLY);
    CVars.FontSystem = CVarDef.Create<bool>("font.system", true, CVar.CLIENTONLY);
    CVars.FontWindowsDownloadable = CVarDef.Create<bool>("font.windows_downloadable", false, CVar.ARCHIVE | CVar.CLIENTONLY);
    CVars.LoadingShowBar = CVarDef.Create<bool>("loading.show_bar", true, CVar.CLIENTONLY);
    CVars.LoadingShowDebug = CVarDef.Create<bool>("loading.show_debug", false, CVar.CLIENTONLY);
  }
}
