using System;
using CompiledRobustXaml;
using Content.Shared.Mech;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML.Proxy;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.Mech.Ui.Equipment;

[GenerateTypedNameReferences]
[XamlMetadata("resm:Content.Client.Mech.Ui.Equipment.MechSoundboardUiFragment.xaml?assembly=Content.Client", "Content.Client.Mech.Ui.Equipment.MechSoundboardUiFragment.xaml", "<equipment:MechSoundboardUiFragment\r\n    xmlns:equipment=\"clr-namespace:Content.Client.Mech.Ui.Equipment\"\r\n    xmlns=\"https://spacestation14.io\" Margin=\"1 0 2 0\" HorizontalExpand=\"True\" VerticalExpand=\"True\">\r\n    <BoxContainer Orientation=\"Vertical\"\r\n                  HorizontalExpand=\"True\"\r\n                  VerticalExpand=\"True\">\r\n        <ItemList Name=\"Sounds\"\r\n                  VerticalExpand=\"True\"\r\n                  MinHeight=\"160\"\r\n                  HorizontalExpand=\"True\"\r\n                  SelectMode=\"Button\"/>\r\n    </BoxContainer>\r\n</equipment:MechSoundboardUiFragment>\r\n")]
public sealed class MechSoundboardUiFragment : BoxContainer
{
	private ItemList Sounds => ((Control)this).FindControl<ItemList>("Sounds");

	public event Action<int>? OnPlayAction;

	public MechSoundboardUiFragment()
	{
		_0021XamlIlPopulateTrampoline(this);
		IoCManager.InjectDependencies<MechSoundboardUiFragment>(this);
	}

	public void UpdateContents(MechSoundboardUiState state)
	{
		foreach (string sound in state.Sounds)
		{
			Sounds.AddItem(Loc.GetString("mech-soundboard-" + sound), (Texture)null, true, (object)null, 1f).OnSelected += delegate(Item item)
			{
				this.OnPlayAction?.Invoke(Sounds.IndexOf(item));
			};
		}
	}

	public static void Populate_003AContent_002EClient_002EMech_002EUi_002EEquipment_002EMechSoundboardUiFragment_002Examl(IServiceProvider P_0, MechSoundboardUiFragment P_1)
	{
		//IL_003b: Unknown result type (might be due to invalid IL or missing references)
		//IL_005b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0060: Unknown result type (might be due to invalid IL or missing references)
		//IL_0061: Unknown result type (might be due to invalid IL or missing references)
		//IL_006c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0077: Unknown result type (might be due to invalid IL or missing references)
		//IL_0082: Unknown result type (might be due to invalid IL or missing references)
		//IL_0087: Unknown result type (might be due to invalid IL or missing references)
		//IL_0088: Unknown result type (might be due to invalid IL or missing references)
		//IL_0089: Unknown result type (might be due to invalid IL or missing references)
		//IL_0098: Expected O, but got Unknown
		//IL_00af: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ba: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00de: Expected O, but got Unknown
		//IL_00f0: Expected O, but got Unknown
		XamlIlContext.Context<MechSoundboardUiFragment> context = new XamlIlContext.Context<MechSoundboardUiFragment>(P_0, null, "resm:Content.Client.Mech.Ui.Equipment.MechSoundboardUiFragment.xaml?assembly=Content.Client");
		context.RootObject = P_1;
		context.IntermediateRoot = P_1;
		((Control)P_1).Margin = new Thickness(1f, 0f, 2f, 0f);
		((Control)P_1).HorizontalExpand = true;
		((Control)P_1).VerticalExpand = true;
		BoxContainer val = new BoxContainer();
		val.Orientation = (LayoutOrientation)1;
		((Control)val).HorizontalExpand = true;
		((Control)val).VerticalExpand = true;
		ItemList val2 = new ItemList();
		((Control)val2).Name = "Sounds";
		Control val3 = (Control)val2;
		context.RobustNameScope.Register("Sounds", val3);
		((Control)val2).VerticalExpand = true;
		((Control)val2).MinHeight = 160f;
		((Control)val2).HorizontalExpand = true;
		val2.SelectMode = (ItemListSelectMode)3;
		val3 = (Control)val2;
		((Control)val).XamlChildren.Add(val3);
		val3 = (Control)val;
		((Control)P_1).XamlChildren.Add(val3);
		if ((val3 = (Control)(object)((P_1 is Control) ? P_1 : null)) != null)
		{
			context.RobustNameScope.Absorb(val3.NameScope);
			val3.NameScope = context.RobustNameScope;
		}
		context.RobustNameScope.Complete();
	}

	private static void _0021XamlIlPopulateTrampoline(MechSoundboardUiFragment P_0)
	{
		if (!IoCManager.Resolve<IXamlProxyHelper>().Populate(typeof(MechSoundboardUiFragment), (object)P_0))
		{
			Populate_003AContent_002EClient_002EMech_002EUi_002EEquipment_002EMechSoundboardUiFragment_002Examl(null, P_0);
		}
	}
}
