using System;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.Xenonids.Hive;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
public sealed class HijackBurrowedSurgeComponent : Component, ISerializationGenerated<HijackBurrowedSurgeComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class HijackBurrowedSurgeComponent_AutoState : IComponentState
	{
		public TimeSpan NextSurgeAt;

		public int PooledLarva;

		public TimeSpan SurgeEvery;

		public TimeSpan ReduceSurgeBy;

		public TimeSpan MinSurgeTime;

		public TimeSpan ResetSurgeTime;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class HijackBurrowedSurgeComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<HijackBurrowedSurgeComponent, ComponentGetState>((ComponentEventRefHandler<HijackBurrowedSurgeComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<HijackBurrowedSurgeComponent, ComponentHandleState>((ComponentEventRefHandler<HijackBurrowedSurgeComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, HijackBurrowedSurgeComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new HijackBurrowedSurgeComponent_AutoState
			{
				NextSurgeAt = component.NextSurgeAt,
				PooledLarva = component.PooledLarva,
				SurgeEvery = component.SurgeEvery,
				ReduceSurgeBy = component.ReduceSurgeBy,
				MinSurgeTime = component.MinSurgeTime,
				ResetSurgeTime = component.ResetSurgeTime
			};
		}

		private void OnHandleState(EntityUid uid, HijackBurrowedSurgeComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is HijackBurrowedSurgeComponent_AutoState state)
			{
				component.NextSurgeAt = state.NextSurgeAt;
				component.PooledLarva = state.PooledLarva;
				component.SurgeEvery = state.SurgeEvery;
				component.ReduceSurgeBy = state.ReduceSurgeBy;
				component.MinSurgeTime = state.MinSurgeTime;
				component.ResetSurgeTime = state.ResetSurgeTime;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan NextSurgeAt;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public int PooledLarva;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan SurgeEvery = TimeSpan.FromSeconds(90L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan ReduceSurgeBy = TimeSpan.FromSeconds(3L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan MinSurgeTime = TimeSpan.FromSeconds(30L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan ResetSurgeTime = TimeSpan.FromSeconds(90L);

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref HijackBurrowedSurgeComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (HijackBurrowedSurgeComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<HijackBurrowedSurgeComponent>(this, ref target, hookCtx, false, context))
		{
			TimeSpan NextSurgeAtTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(NextSurgeAt, ref NextSurgeAtTemp, hookCtx, false, context))
			{
				NextSurgeAtTemp = serialization.CreateCopy<TimeSpan>(NextSurgeAt, hookCtx, context, false);
			}
			target.NextSurgeAt = NextSurgeAtTemp;
			int PooledLarvaTemp = 0;
			if (!serialization.TryCustomCopy<int>(PooledLarva, ref PooledLarvaTemp, hookCtx, false, context))
			{
				PooledLarvaTemp = PooledLarva;
			}
			target.PooledLarva = PooledLarvaTemp;
			TimeSpan SurgeEveryTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(SurgeEvery, ref SurgeEveryTemp, hookCtx, false, context))
			{
				SurgeEveryTemp = serialization.CreateCopy<TimeSpan>(SurgeEvery, hookCtx, context, false);
			}
			target.SurgeEvery = SurgeEveryTemp;
			TimeSpan ReduceSurgeByTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(ReduceSurgeBy, ref ReduceSurgeByTemp, hookCtx, false, context))
			{
				ReduceSurgeByTemp = serialization.CreateCopy<TimeSpan>(ReduceSurgeBy, hookCtx, context, false);
			}
			target.ReduceSurgeBy = ReduceSurgeByTemp;
			TimeSpan MinSurgeTimeTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(MinSurgeTime, ref MinSurgeTimeTemp, hookCtx, false, context))
			{
				MinSurgeTimeTemp = serialization.CreateCopy<TimeSpan>(MinSurgeTime, hookCtx, context, false);
			}
			target.MinSurgeTime = MinSurgeTimeTemp;
			TimeSpan ResetSurgeTimeTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(ResetSurgeTime, ref ResetSurgeTimeTemp, hookCtx, false, context))
			{
				ResetSurgeTimeTemp = serialization.CreateCopy<TimeSpan>(ResetSurgeTime, hookCtx, context, false);
			}
			target.ResetSurgeTime = ResetSurgeTimeTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref HijackBurrowedSurgeComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		HijackBurrowedSurgeComponent cast = (HijackBurrowedSurgeComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		HijackBurrowedSurgeComponent cast = (HijackBurrowedSurgeComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		HijackBurrowedSurgeComponent def = (HijackBurrowedSurgeComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override HijackBurrowedSurgeComponent Instantiate()
	{
		return new HijackBurrowedSurgeComponent();
	}
}
