using System;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.Xenonids.Paralyzing;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] { typeof(XenoParalyzingSlashSystem) })]
public sealed class XenoParalyzingSlashComponent : Component, ISerializationGenerated<XenoParalyzingSlashComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoParalyzingSlashComponent_AutoState : IComponentState
	{
		public TimeSpan ActiveDuration;

		public TimeSpan DazeTime;

		public TimeSpan StunDelay;

		public TimeSpan StunDuration;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoParalyzingSlashComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<XenoParalyzingSlashComponent, ComponentGetState>((ComponentEventRefHandler<XenoParalyzingSlashComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<XenoParalyzingSlashComponent, ComponentHandleState>((ComponentEventRefHandler<XenoParalyzingSlashComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, XenoParalyzingSlashComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new XenoParalyzingSlashComponent_AutoState
			{
				ActiveDuration = component.ActiveDuration,
				DazeTime = component.DazeTime,
				StunDelay = component.StunDelay,
				StunDuration = component.StunDuration
			};
		}

		private void OnHandleState(EntityUid uid, XenoParalyzingSlashComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is XenoParalyzingSlashComponent_AutoState state)
			{
				component.ActiveDuration = state.ActiveDuration;
				component.DazeTime = state.DazeTime;
				component.StunDelay = state.StunDelay;
				component.StunDuration = state.StunDuration;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan ActiveDuration = TimeSpan.FromSeconds(5L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan DazeTime = TimeSpan.FromSeconds(8L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan StunDelay = TimeSpan.FromSeconds(4L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan StunDuration = TimeSpan.FromSeconds(4L);

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref XenoParalyzingSlashComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (XenoParalyzingSlashComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<XenoParalyzingSlashComponent>(this, ref target, hookCtx, false, context))
		{
			TimeSpan ActiveDurationTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(ActiveDuration, ref ActiveDurationTemp, hookCtx, false, context))
			{
				ActiveDurationTemp = serialization.CreateCopy<TimeSpan>(ActiveDuration, hookCtx, context, false);
			}
			target.ActiveDuration = ActiveDurationTemp;
			TimeSpan DazeTimeTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(DazeTime, ref DazeTimeTemp, hookCtx, false, context))
			{
				DazeTimeTemp = serialization.CreateCopy<TimeSpan>(DazeTime, hookCtx, context, false);
			}
			target.DazeTime = DazeTimeTemp;
			TimeSpan StunDelayTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(StunDelay, ref StunDelayTemp, hookCtx, false, context))
			{
				StunDelayTemp = serialization.CreateCopy<TimeSpan>(StunDelay, hookCtx, context, false);
			}
			target.StunDelay = StunDelayTemp;
			TimeSpan StunDurationTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(StunDuration, ref StunDurationTemp, hookCtx, false, context))
			{
				StunDurationTemp = serialization.CreateCopy<TimeSpan>(StunDuration, hookCtx, context, false);
			}
			target.StunDuration = StunDurationTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref XenoParalyzingSlashComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoParalyzingSlashComponent cast = (XenoParalyzingSlashComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoParalyzingSlashComponent cast = (XenoParalyzingSlashComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoParalyzingSlashComponent def = (XenoParalyzingSlashComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override XenoParalyzingSlashComponent Instantiate()
	{
		return new XenoParalyzingSlashComponent();
	}
}
