// Decompiled with JetBrains decompiler
// Type: Content.Shared.RatKing.RatKingServantComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared.RatKing;

[RegisterComponent]
[NetworkedComponent]
[Access(new Type[] {typeof (SharedRatKingSystem)})]
[AutoGenerateComponentState(false, false)]
public sealed class RatKingServantComponent : 
  Component,
  ISerializationGenerated<RatKingServantComponent>,
  ISerializationGenerated
{
  [DataField("king", false, 1, false, false, null)]
  [AutoNetworkedField]
  public EntityUid? King;

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref RatKingServantComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (RatKingServantComponent) target1;
    if (serialization.TryCustomCopy<RatKingServantComponent>(this, ref target, hookCtx, false, context))
      return;
    EntityUid? target2 = new EntityUid?();
    if (!serialization.TryCustomCopy<EntityUid?>(this.King, ref target2, hookCtx, false, context))
      target2 = serialization.CreateCopy<EntityUid?>(this.King, hookCtx, context);
    target.King = target2;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref RatKingServantComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RatKingServantComponent target1 = (RatKingServantComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RatKingServantComponent target1 = (RatKingServantComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    RatKingServantComponent target1 = (RatKingServantComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual RatKingServantComponent Component.Instantiate() => new RatKingServantComponent();

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class RatKingServantComponent_AutoState : IComponentState
  {
    public NetEntity? King;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class RatKingServantComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<RatKingServantComponent, ComponentGetState>(new ComponentEventRefHandler<RatKingServantComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<RatKingServantComponent, ComponentHandleState>(new ComponentEventRefHandler<RatKingServantComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      RatKingServantComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new RatKingServantComponent.RatKingServantComponent_AutoState()
      {
        King = this.GetNetEntity(component.King)
      };
    }

    private void OnHandleState(
      EntityUid uid,
      RatKingServantComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is RatKingServantComponent.RatKingServantComponent_AutoState current))
        return;
      component.King = this.EnsureEntity<RatKingServantComponent>(current.King, uid);
    }
  }
}
