using System;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Localization;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.Xenonids.Rest;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] { typeof(XenoRestSystem) })]
public sealed class ActionBlockIfRestingComponent : Component, ISerializationGenerated<ActionBlockIfRestingComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ActionBlockIfRestingComponent_AutoState : IComponentState
	{
		public LocId Popup;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class ActionBlockIfRestingComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<ActionBlockIfRestingComponent, ComponentGetState>((ComponentEventRefHandler<ActionBlockIfRestingComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<ActionBlockIfRestingComponent, ComponentHandleState>((ComponentEventRefHandler<ActionBlockIfRestingComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, ActionBlockIfRestingComponent component, ref ComponentGetState args)
		{
			//IL_0008: Unknown result type (might be due to invalid IL or missing references)
			//IL_000d: Unknown result type (might be due to invalid IL or missing references)
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new ActionBlockIfRestingComponent_AutoState
			{
				Popup = component.Popup
			};
		}

		private void OnHandleState(EntityUid uid, ActionBlockIfRestingComponent component, ref ComponentHandleState args)
		{
			//IL_0012: Unknown result type (might be due to invalid IL or missing references)
			//IL_0017: Unknown result type (might be due to invalid IL or missing references)
			if (((ComponentHandleState)(ref args)).Current is ActionBlockIfRestingComponent_AutoState state)
			{
				component.Popup = state.Popup;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public LocId Popup = LocId.op_Implicit("rmc-xeno-rest-cant");

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref ActionBlockIfRestingComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0028: Unknown result type (might be due to invalid IL or missing references)
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_0056: Unknown result type (might be due to invalid IL or missing references)
		//IL_0044: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (ActionBlockIfRestingComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<ActionBlockIfRestingComponent>(this, ref target, hookCtx, false, context))
		{
			LocId PopupTemp = default(LocId);
			if (!serialization.TryCustomCopy<LocId>(Popup, ref PopupTemp, hookCtx, false, context))
			{
				PopupTemp = serialization.CreateCopy<LocId>(Popup, hookCtx, context, false);
			}
			target.Popup = PopupTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref ActionBlockIfRestingComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ActionBlockIfRestingComponent cast = (ActionBlockIfRestingComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ActionBlockIfRestingComponent cast = (ActionBlockIfRestingComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		ActionBlockIfRestingComponent def = (ActionBlockIfRestingComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override ActionBlockIfRestingComponent Instantiate()
	{
		return new ActionBlockIfRestingComponent();
	}
}
