using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Numerics;
using Content.Shared._RMC14.Xenonids.Pheromones;
using Content.Shared.Access;
using Content.Shared.Alert;
using Content.Shared.Chat.Prototypes;
using Content.Shared.Eye;
using Content.Shared.Roles;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.Serialization.Manager.Exceptions;

namespace Content.Shared._RMC14.Xenonids;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] { typeof(XenoSystem) })]
public sealed class XenoComponent : Component, ISerializationGenerated<XenoComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoComponent_AutoState : IComponentState
	{
		public ProtoId<JobPrototype> Role;

		public List<EntProtoId> ActionIds;

		public Dictionary<EntProtoId, NetEntity> Actions;

		public HashSet<ProtoId<AccessLevelPrototype>> AccessLevels;

		public int Tier;

		public Vector2 HudOffset;

		public bool ContributesToVictory;

		public bool CountedInSlots;

		public bool BypassTierCount;

		public TimeSpan UnlockAt;

		public ProtoId<AlertPrototype> ArmorAlert;

		public bool SpawnAtLeaderPoint;

		public ProtoId<EmoteSoundsPrototype>? EmoteSounds;

		public bool MuteOnSpawn;

		public VisibilityFlags Visibility;

		public XenoPheromones? IgnorePheromones;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class XenoComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<XenoComponent, ComponentGetState>((ComponentEventRefHandler<XenoComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<XenoComponent, ComponentHandleState>((ComponentEventRefHandler<XenoComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, XenoComponent component, ref ComponentGetState args)
		{
			//IL_0008: Unknown result type (might be due to invalid IL or missing references)
			//IL_000d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0086: Unknown result type (might be due to invalid IL or missing references)
			//IL_008b: Unknown result type (might be due to invalid IL or missing references)
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new XenoComponent_AutoState
			{
				Role = component.Role,
				ActionIds = component.ActionIds,
				Actions = ((EntitySystem)this).GetNetEntityDictionary<EntProtoId>(component.Actions),
				AccessLevels = component.AccessLevels,
				Tier = component.Tier,
				HudOffset = component.HudOffset,
				ContributesToVictory = component.ContributesToVictory,
				CountedInSlots = component.CountedInSlots,
				BypassTierCount = component.BypassTierCount,
				UnlockAt = component.UnlockAt,
				ArmorAlert = component.ArmorAlert,
				SpawnAtLeaderPoint = component.SpawnAtLeaderPoint,
				EmoteSounds = component.EmoteSounds,
				MuteOnSpawn = component.MuteOnSpawn,
				Visibility = component.Visibility,
				IgnorePheromones = component.IgnorePheromones
			};
		}

		private void OnHandleState(EntityUid uid, XenoComponent component, ref ComponentHandleState args)
		{
			//IL_0012: Unknown result type (might be due to invalid IL or missing references)
			//IL_0017: Unknown result type (might be due to invalid IL or missing references)
			//IL_003f: Unknown result type (might be due to invalid IL or missing references)
			//IL_00b1: Unknown result type (might be due to invalid IL or missing references)
			//IL_00b6: Unknown result type (might be due to invalid IL or missing references)
			if (((ComponentHandleState)(ref args)).Current is XenoComponent_AutoState state)
			{
				component.Role = state.Role;
				component.ActionIds = ((state.ActionIds == null) ? null : new List<EntProtoId>(state.ActionIds));
				((EntitySystem)this).EnsureEntityDictionary<XenoComponent, EntProtoId>(state.Actions, uid, component.Actions);
				component.AccessLevels = ((state.AccessLevels == null) ? null : new HashSet<ProtoId<AccessLevelPrototype>>(state.AccessLevels));
				component.Tier = state.Tier;
				component.HudOffset = state.HudOffset;
				component.ContributesToVictory = state.ContributesToVictory;
				component.CountedInSlots = state.CountedInSlots;
				component.BypassTierCount = state.BypassTierCount;
				component.UnlockAt = state.UnlockAt;
				component.ArmorAlert = state.ArmorAlert;
				component.SpawnAtLeaderPoint = state.SpawnAtLeaderPoint;
				component.EmoteSounds = state.EmoteSounds;
				component.MuteOnSpawn = state.MuteOnSpawn;
				component.Visibility = state.Visibility;
				component.IgnorePheromones = state.IgnorePheromones;
			}
		}
	}

	[DataField(null, false, 1, true, false, null)]
	[AutoNetworkedField]
	public ProtoId<JobPrototype> Role;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public List<EntProtoId> ActionIds = new List<EntProtoId>();

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public Dictionary<EntProtoId, EntityUid> Actions = new Dictionary<EntProtoId, EntityUid>();

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public HashSet<ProtoId<AccessLevelPrototype>> AccessLevels = new HashSet<ProtoId<AccessLevelPrototype>> { ProtoId<AccessLevelPrototype>.op_Implicit("CMAccessXeno") };

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public int Tier;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public Vector2 HudOffset;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool ContributesToVictory = true;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool CountedInSlots = true;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool BypassTierCount;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan UnlockAt = TimeSpan.FromSeconds(60L);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public ProtoId<AlertPrototype> ArmorAlert = ProtoId<AlertPrototype>.op_Implicit("XenoArmor");

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool SpawnAtLeaderPoint;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public ProtoId<EmoteSoundsPrototype>? EmoteSounds = ProtoId<EmoteSoundsPrototype>.op_Implicit("Xeno");

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public bool MuteOnSpawn;

	public EmoteSoundsPrototype? Sounds;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public VisibilityFlags Visibility = VisibilityFlags.Xeno;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public XenoPheromones? IgnorePheromones;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref XenoComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		//IL_0028: Unknown result type (might be due to invalid IL or missing references)
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_0056: Unknown result type (might be due to invalid IL or missing references)
		//IL_0044: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_0065: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e0: Unknown result type (might be due to invalid IL or missing references)
		//IL_0225: Unknown result type (might be due to invalid IL or missing references)
		//IL_022d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0253: Unknown result type (might be due to invalid IL or missing references)
		//IL_0255: Unknown result type (might be due to invalid IL or missing references)
		//IL_0241: Unknown result type (might be due to invalid IL or missing references)
		//IL_024a: Unknown result type (might be due to invalid IL or missing references)
		//IL_024f: Unknown result type (might be due to invalid IL or missing references)
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (XenoComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<XenoComponent>(this, ref target, hookCtx, false, context))
		{
			ProtoId<JobPrototype> RoleTemp = default(ProtoId<JobPrototype>);
			if (!serialization.TryCustomCopy<ProtoId<JobPrototype>>(Role, ref RoleTemp, hookCtx, false, context))
			{
				RoleTemp = serialization.CreateCopy<ProtoId<JobPrototype>>(Role, hookCtx, context, false);
			}
			target.Role = RoleTemp;
			List<EntProtoId> ActionIdsTemp = null;
			if (ActionIds == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<List<EntProtoId>>(ActionIds, ref ActionIdsTemp, hookCtx, true, context))
			{
				ActionIdsTemp = serialization.CreateCopy<List<EntProtoId>>(ActionIds, hookCtx, context, false);
			}
			target.ActionIds = ActionIdsTemp;
			Dictionary<EntProtoId, EntityUid> ActionsTemp = null;
			if (Actions == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<Dictionary<EntProtoId, EntityUid>>(Actions, ref ActionsTemp, hookCtx, true, context))
			{
				ActionsTemp = serialization.CreateCopy<Dictionary<EntProtoId, EntityUid>>(Actions, hookCtx, context, false);
			}
			target.Actions = ActionsTemp;
			HashSet<ProtoId<AccessLevelPrototype>> AccessLevelsTemp = null;
			if (AccessLevels == null)
			{
				throw new NullNotAllowedException();
			}
			if (!serialization.TryCustomCopy<HashSet<ProtoId<AccessLevelPrototype>>>(AccessLevels, ref AccessLevelsTemp, hookCtx, true, context))
			{
				AccessLevelsTemp = serialization.CreateCopy<HashSet<ProtoId<AccessLevelPrototype>>>(AccessLevels, hookCtx, context, false);
			}
			target.AccessLevels = AccessLevelsTemp;
			int TierTemp = 0;
			if (!serialization.TryCustomCopy<int>(Tier, ref TierTemp, hookCtx, false, context))
			{
				TierTemp = Tier;
			}
			target.Tier = TierTemp;
			Vector2 HudOffsetTemp = default(Vector2);
			if (!serialization.TryCustomCopy<Vector2>(HudOffset, ref HudOffsetTemp, hookCtx, false, context))
			{
				HudOffsetTemp = serialization.CreateCopy<Vector2>(HudOffset, hookCtx, context, false);
			}
			target.HudOffset = HudOffsetTemp;
			bool ContributesToVictoryTemp = false;
			if (!serialization.TryCustomCopy<bool>(ContributesToVictory, ref ContributesToVictoryTemp, hookCtx, false, context))
			{
				ContributesToVictoryTemp = ContributesToVictory;
			}
			target.ContributesToVictory = ContributesToVictoryTemp;
			bool CountedInSlotsTemp = false;
			if (!serialization.TryCustomCopy<bool>(CountedInSlots, ref CountedInSlotsTemp, hookCtx, false, context))
			{
				CountedInSlotsTemp = CountedInSlots;
			}
			target.CountedInSlots = CountedInSlotsTemp;
			bool BypassTierCountTemp = false;
			if (!serialization.TryCustomCopy<bool>(BypassTierCount, ref BypassTierCountTemp, hookCtx, false, context))
			{
				BypassTierCountTemp = BypassTierCount;
			}
			target.BypassTierCount = BypassTierCountTemp;
			TimeSpan UnlockAtTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(UnlockAt, ref UnlockAtTemp, hookCtx, false, context))
			{
				UnlockAtTemp = serialization.CreateCopy<TimeSpan>(UnlockAt, hookCtx, context, false);
			}
			target.UnlockAt = UnlockAtTemp;
			ProtoId<AlertPrototype> ArmorAlertTemp = default(ProtoId<AlertPrototype>);
			if (!serialization.TryCustomCopy<ProtoId<AlertPrototype>>(ArmorAlert, ref ArmorAlertTemp, hookCtx, false, context))
			{
				ArmorAlertTemp = serialization.CreateCopy<ProtoId<AlertPrototype>>(ArmorAlert, hookCtx, context, false);
			}
			target.ArmorAlert = ArmorAlertTemp;
			bool SpawnAtLeaderPointTemp = false;
			if (!serialization.TryCustomCopy<bool>(SpawnAtLeaderPoint, ref SpawnAtLeaderPointTemp, hookCtx, false, context))
			{
				SpawnAtLeaderPointTemp = SpawnAtLeaderPoint;
			}
			target.SpawnAtLeaderPoint = SpawnAtLeaderPointTemp;
			ProtoId<EmoteSoundsPrototype>? EmoteSoundsTemp = null;
			if (!serialization.TryCustomCopy<ProtoId<EmoteSoundsPrototype>?>(EmoteSounds, ref EmoteSoundsTemp, hookCtx, false, context))
			{
				EmoteSoundsTemp = serialization.CreateCopy<ProtoId<EmoteSoundsPrototype>?>(EmoteSounds, hookCtx, context, false);
			}
			target.EmoteSounds = EmoteSoundsTemp;
			bool MuteOnSpawnTemp = false;
			if (!serialization.TryCustomCopy<bool>(MuteOnSpawn, ref MuteOnSpawnTemp, hookCtx, false, context))
			{
				MuteOnSpawnTemp = MuteOnSpawn;
			}
			target.MuteOnSpawn = MuteOnSpawnTemp;
			VisibilityFlags VisibilityTemp = VisibilityFlags.None;
			if (!serialization.TryCustomCopy<VisibilityFlags>(Visibility, ref VisibilityTemp, hookCtx, false, context))
			{
				VisibilityTemp = Visibility;
			}
			target.Visibility = VisibilityTemp;
			XenoPheromones? IgnorePheromonesTemp = null;
			if (!serialization.TryCustomCopy<XenoPheromones?>(IgnorePheromones, ref IgnorePheromonesTemp, hookCtx, false, context))
			{
				IgnorePheromonesTemp = IgnorePheromones;
			}
			target.IgnorePheromones = IgnorePheromonesTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref XenoComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoComponent cast = (XenoComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoComponent cast = (XenoComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		XenoComponent def = (XenoComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override XenoComponent Instantiate()
	{
		return new XenoComponent();
	}
}
