// Decompiled with JetBrains decompiler
// Type: Content.Client._RMC14.Dropship.Weapon.DropshipWeaponsButtonRow
// Assembly: Content.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B4469588-B038-4783-B6EC-1EFF6592A364
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Client.dll

using CompiledRobustXaml;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML.Proxy;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using System;
using System.Runtime.InteropServices;

#nullable enable
namespace Content.Client._RMC14.Dropship.Weapon;

[GenerateTypedNameReferences]
[XamlMetadata("resm:Content.Client._RMC14.Dropship.Weapon.DropshipWeaponsButtonRow.xaml?assembly=Content.Client", "Content.Client._RMC14.Dropship.Weapon.DropshipWeaponsButtonRow.xaml", "<controls:DropshipWeaponsButtonRow\r\n    xmlns=\"https://spacestation14.io\"\r\n    xmlns:controls=\"clr-namespace:Content.Client._RMC14.Dropship.Weapon\"\r\n    SeparationOverride=\"25\" HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\">\r\n    <Control Name=\"PaddingStart\" />\r\n    <controls:DropshipWeaponsButton Name=\"One\" Access=\"Public\" />\r\n    <controls:DropshipWeaponsButton Name=\"Two\" Access=\"Public\" />\r\n    <controls:DropshipWeaponsButton Name=\"Three\" Access=\"Public\" />\r\n    <controls:DropshipWeaponsButton Name=\"Four\" Access=\"Public\" />\r\n    <controls:DropshipWeaponsButton Name=\"Five\" Access=\"Public\" />\r\n    <Control Name=\"PaddingEnd\" />\r\n</controls:DropshipWeaponsButtonRow>\r\n")]
public sealed class DropshipWeaponsButtonRow : BoxContainer
{
  public DropshipWeaponsButtonRow()
  {
    DropshipWeaponsButtonRow.\u0021XamlIlPopulateTrampoline(this);
  }

  public void Refresh()
  {
    BoxContainer.LayoutOrientation orientation = this.Orientation;
    if (orientation != null)
    {
      if (orientation != 1)
        return;
      this.PaddingStart.HorizontalExpand = false;
      this.PaddingStart.VerticalExpand = true;
      this.PaddingEnd.HorizontalExpand = false;
      this.PaddingEnd.VerticalExpand = true;
      ((Control) this).SetHeight = 500f;
    }
    else
    {
      this.PaddingStart.HorizontalExpand = true;
      this.PaddingStart.VerticalExpand = false;
      this.PaddingEnd.HorizontalExpand = true;
      this.PaddingEnd.VerticalExpand = false;
    }
  }

  public void SetData(
    DropshipWeaponsButtonData? one = null,
    DropshipWeaponsButtonData? two = null,
    DropshipWeaponsButtonData? three = null,
    DropshipWeaponsButtonData? four = null,
    DropshipWeaponsButtonData? five = null)
  {
    this.SetData(this.One, one);
    this.SetData(this.Two, two);
    this.SetData(this.Three, three);
    this.SetData(this.Four, four);
    this.SetData(this.Five, five);
  }

  private void SetData(DropshipWeaponsButton button, DropshipWeaponsButtonData? data)
  {
    button.RichLabel.SetMarkupPermissive(Wrap(data?.Text));
    button.SetOnPressed(data?.OnPressed);

    static string Wrap(LocId? loc)
    {
      string empty;
      if (loc.HasValue)
      {
        LocId? nullable = loc;
        empty = Loc.GetString(nullable.HasValue ? LocId.op_Implicit(nullable.GetValueOrDefault()) : (string) null);
      }
      else
        empty = string.Empty;
      string str = empty;
      int num = 9;
      if (str == "WEAPON")
        num = 8;
      return $"[font size={num}][color=white]{str}[/color][/font]";
    }
  }

  private 
  #nullable disable
  Control PaddingStart => ((Control) this).FindControl<Control>(nameof (PaddingStart));

  public DropshipWeaponsButton One
  {
    get => ((Control) this).FindControl<DropshipWeaponsButton>(nameof (One));
  }

  public DropshipWeaponsButton Two
  {
    get => ((Control) this).FindControl<DropshipWeaponsButton>(nameof (Two));
  }

  public DropshipWeaponsButton Three
  {
    get => ((Control) this).FindControl<DropshipWeaponsButton>(nameof (Three));
  }

  public DropshipWeaponsButton Four
  {
    get => ((Control) this).FindControl<DropshipWeaponsButton>(nameof (Four));
  }

  public DropshipWeaponsButton Five
  {
    get => ((Control) this).FindControl<DropshipWeaponsButton>(nameof (Five));
  }

  private Control PaddingEnd => ((Control) this).FindControl<Control>(nameof (PaddingEnd));

  public static void Populate\u003AContent\u002EClient\u002E_RMC14\u002EDropship\u002EWeapon\u002EDropshipWeaponsButtonRow\u002Examl(
    [In] IServiceProvider obj0,
    [In] DropshipWeaponsButtonRow obj1)
  {
    XamlIlContext.Context<DropshipWeaponsButtonRow> context = new XamlIlContext.Context<DropshipWeaponsButtonRow>(obj0, (object[]) null, "resm:Content.Client._RMC14.Dropship.Weapon.DropshipWeaponsButtonRow.xaml?assembly=Content.Client");
    context.RootObject = obj1;
    context.IntermediateRoot = (object) obj1;
    DropshipWeaponsButtonRow weaponsButtonRow = obj1;
    weaponsButtonRow.SeparationOverride = new int?(25);
    ((Control) weaponsButtonRow).HorizontalAlignment = (Control.HAlignment) 2;
    ((Control) weaponsButtonRow).VerticalAlignment = (Control.VAlignment) 2;
    Control control1 = new Control();
    control1.Name = "PaddingStart";
    Control control2 = control1;
    context.RobustNameScope.Register("PaddingStart", control2);
    ((Control) weaponsButtonRow).XamlChildren.Add(control1);
    DropshipWeaponsButton dropshipWeaponsButton1 = new DropshipWeaponsButton();
    ((Control) dropshipWeaponsButton1).Name = "One";
    Control control3 = (Control) dropshipWeaponsButton1;
    context.RobustNameScope.Register("One", control3);
    ((Control) dropshipWeaponsButton1).Access = new AccessLevel?((AccessLevel) 0);
    ((Control) weaponsButtonRow).XamlChildren.Add((Control) dropshipWeaponsButton1);
    DropshipWeaponsButton dropshipWeaponsButton2 = new DropshipWeaponsButton();
    ((Control) dropshipWeaponsButton2).Name = "Two";
    Control control4 = (Control) dropshipWeaponsButton2;
    context.RobustNameScope.Register("Two", control4);
    ((Control) dropshipWeaponsButton2).Access = new AccessLevel?((AccessLevel) 0);
    ((Control) weaponsButtonRow).XamlChildren.Add((Control) dropshipWeaponsButton2);
    DropshipWeaponsButton dropshipWeaponsButton3 = new DropshipWeaponsButton();
    ((Control) dropshipWeaponsButton3).Name = "Three";
    Control control5 = (Control) dropshipWeaponsButton3;
    context.RobustNameScope.Register("Three", control5);
    ((Control) dropshipWeaponsButton3).Access = new AccessLevel?((AccessLevel) 0);
    ((Control) weaponsButtonRow).XamlChildren.Add((Control) dropshipWeaponsButton3);
    DropshipWeaponsButton dropshipWeaponsButton4 = new DropshipWeaponsButton();
    ((Control) dropshipWeaponsButton4).Name = "Four";
    Control control6 = (Control) dropshipWeaponsButton4;
    context.RobustNameScope.Register("Four", control6);
    ((Control) dropshipWeaponsButton4).Access = new AccessLevel?((AccessLevel) 0);
    ((Control) weaponsButtonRow).XamlChildren.Add((Control) dropshipWeaponsButton4);
    DropshipWeaponsButton dropshipWeaponsButton5 = new DropshipWeaponsButton();
    ((Control) dropshipWeaponsButton5).Name = "Five";
    Control control7 = (Control) dropshipWeaponsButton5;
    context.RobustNameScope.Register("Five", control7);
    ((Control) dropshipWeaponsButton5).Access = new AccessLevel?((AccessLevel) 0);
    ((Control) weaponsButtonRow).XamlChildren.Add((Control) dropshipWeaponsButton5);
    Control control8 = new Control();
    control8.Name = "PaddingEnd";
    Control control9 = control8;
    context.RobustNameScope.Register("PaddingEnd", control9);
    ((Control) weaponsButtonRow).XamlChildren.Add(control8);
    if (weaponsButtonRow is Control control10)
    {
      context.RobustNameScope.Absorb(control10.NameScope);
      control10.NameScope = context.RobustNameScope;
    }
    context.RobustNameScope.Complete();
  }

  private static void \u0021XamlIlPopulateTrampoline([In] DropshipWeaponsButtonRow obj0)
  {
    if (IoCManager.Resolve<IXamlProxyHelper>().Populate(typeof (DropshipWeaponsButtonRow), (object) obj0))
      return;
    DropshipWeaponsButtonRow.Populate\u003AContent\u002EClient\u002E_RMC14\u002EDropship\u002EWeapon\u002EDropshipWeaponsButtonRow\u002Examl((IServiceProvider) null, obj0);
  }
}
