using System;
using System.ComponentModel;
using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;

namespace Content.Shared._RMC14.Xenonids.Parasite;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
public sealed class TrapParasiteComponent : Component, ISerializationGenerated<TrapParasiteComponent>, ISerializationGenerated
{
	[Serializable]
	[NetSerializable]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class TrapParasiteComponent_AutoState : IComponentState
	{
		public TimeSpan JumpTime;

		public TimeSpan DisableTime;

		public TimeSpan? LeapAt;

		public TimeSpan? DisableAt;

		public TimeSpan NormalLeapDelay;
	}

	[RobustAutoGenerated]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class TrapParasiteComponent_AutoNetworkSystem : EntitySystem
	{
		public override void Initialize()
		{
			((EntitySystem)this).SubscribeLocalEvent<TrapParasiteComponent, ComponentGetState>((ComponentEventRefHandler<TrapParasiteComponent, ComponentGetState>)OnGetState, (Type[])null, (Type[])null);
			((EntitySystem)this).SubscribeLocalEvent<TrapParasiteComponent, ComponentHandleState>((ComponentEventRefHandler<TrapParasiteComponent, ComponentHandleState>)OnHandleState, (Type[])null, (Type[])null);
		}

		private void OnGetState(EntityUid uid, TrapParasiteComponent component, ref ComponentGetState args)
		{
			((ComponentGetState)(ref args)).State = (IComponentState)(object)new TrapParasiteComponent_AutoState
			{
				JumpTime = component.JumpTime,
				DisableTime = component.DisableTime,
				LeapAt = component.LeapAt,
				DisableAt = component.DisableAt,
				NormalLeapDelay = component.NormalLeapDelay
			};
		}

		private void OnHandleState(EntityUid uid, TrapParasiteComponent component, ref ComponentHandleState args)
		{
			if (((ComponentHandleState)(ref args)).Current is TrapParasiteComponent_AutoState state)
			{
				component.JumpTime = state.JumpTime;
				component.DisableTime = state.DisableTime;
				component.LeapAt = state.LeapAt;
				component.DisableAt = state.DisableAt;
				component.NormalLeapDelay = state.NormalLeapDelay;
			}
		}
	}

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan JumpTime = TimeSpan.FromSeconds(1.5);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan DisableTime = TimeSpan.FromSeconds(0.25);

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan? LeapAt;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan? DisableAt;

	[DataField(null, false, 1, false, false, null)]
	[AutoNetworkedField]
	public TimeSpan NormalLeapDelay;

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void InternalCopy(ref TrapParasiteComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		Component definitionCast = (Component)(object)target;
		((Component)this).InternalCopy(ref definitionCast, serialization, hookCtx, context);
		target = (TrapParasiteComponent)(object)definitionCast;
		if (!serialization.TryCustomCopy<TrapParasiteComponent>(this, ref target, hookCtx, false, context))
		{
			TimeSpan JumpTimeTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(JumpTime, ref JumpTimeTemp, hookCtx, false, context))
			{
				JumpTimeTemp = serialization.CreateCopy<TimeSpan>(JumpTime, hookCtx, context, false);
			}
			target.JumpTime = JumpTimeTemp;
			TimeSpan DisableTimeTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(DisableTime, ref DisableTimeTemp, hookCtx, false, context))
			{
				DisableTimeTemp = serialization.CreateCopy<TimeSpan>(DisableTime, hookCtx, context, false);
			}
			target.DisableTime = DisableTimeTemp;
			TimeSpan? LeapAtTemp = null;
			if (!serialization.TryCustomCopy<TimeSpan?>(LeapAt, ref LeapAtTemp, hookCtx, false, context))
			{
				LeapAtTemp = serialization.CreateCopy<TimeSpan?>(LeapAt, hookCtx, context, false);
			}
			target.LeapAt = LeapAtTemp;
			TimeSpan? DisableAtTemp = null;
			if (!serialization.TryCustomCopy<TimeSpan?>(DisableAt, ref DisableAtTemp, hookCtx, false, context))
			{
				DisableAtTemp = serialization.CreateCopy<TimeSpan?>(DisableAt, hookCtx, context, false);
			}
			target.DisableAt = DisableAtTemp;
			TimeSpan NormalLeapDelayTemp = default(TimeSpan);
			if (!serialization.TryCustomCopy<TimeSpan>(NormalLeapDelay, ref NormalLeapDelayTemp, hookCtx, false, context))
			{
				NormalLeapDelayTemp = serialization.CreateCopy<TimeSpan>(NormalLeapDelay, hookCtx, context, false);
			}
			target.NormalLeapDelay = NormalLeapDelayTemp;
		}
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public void Copy(ref TrapParasiteComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref Component target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		TrapParasiteComponent cast = (TrapParasiteComponent)(object)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = (Component)(object)cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref object target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		TrapParasiteComponent cast = (TrapParasiteComponent)target;
		Copy(ref cast, serialization, hookCtx, context);
		target = cast;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void InternalCopy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		TrapParasiteComponent def = (TrapParasiteComponent)(object)target;
		Copy(ref def, serialization, hookCtx, context);
		target = (IComponent)(object)def;
	}

	[Obsolete("Use ISerializationManager.CopyTo instead")]
	public override void Copy(ref IComponent target, ISerializationManager serialization, SerializationHookContext hookCtx, ISerializationContext? context = null)
	{
		((Component)this).InternalCopy(ref target, serialization, hookCtx, context);
	}

	[Obsolete("Use ISerializationManager.CreateCopy instead")]
	public override TrapParasiteComponent Instantiate()
	{
		return new TrapParasiteComponent();
	}
}
