// Decompiled with JetBrains decompiler
// Type: Content.Shared._RMC14.Xenonids.ResinSurge.XenoResinSurgeActionComponent
// Assembly: Content.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5417D05E-B3D9-4989-8630-1DD892BD48BB
// Assembly location: C:\Users\sus\Desktop\SS14_VFS_Dump_20260624_230444\Content.Shared.dll

using Robust.Shared.Analyzers;
using Robust.Shared.GameObjects;
using Robust.Shared.GameStates;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Manager.Attributes;
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

#nullable enable
namespace Content.Shared._RMC14.Xenonids.ResinSurge;

[RegisterComponent]
[NetworkedComponent]
[AutoGenerateComponentState(false, false)]
[Access(new Type[] {typeof (SharedXenoResinSurgeSystem)})]
public sealed class XenoResinSurgeActionComponent : 
  Component,
  ISerializationGenerated<XenoResinSurgeActionComponent>,
  ISerializationGenerated
{
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public float FailCooldownMult = 0.5f;
  [DataField(null, false, 1, false, false, null)]
  [AutoNetworkedField]
  public TimeSpan SuccessCooldown = TimeSpan.FromSeconds(10L);

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void InternalCopy(
    ref XenoResinSurgeActionComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    Component target1 = (Component) target;
    this.InternalCopy(ref target1, serialization, hookCtx, context);
    target = (XenoResinSurgeActionComponent) target1;
    if (serialization.TryCustomCopy<XenoResinSurgeActionComponent>(this, ref target, hookCtx, false, context))
      return;
    float target2 = 0.0f;
    if (!serialization.TryCustomCopy<float>(this.FailCooldownMult, ref target2, hookCtx, false, context))
      target2 = this.FailCooldownMult;
    target.FailCooldownMult = target2;
    TimeSpan target3 = new TimeSpan();
    if (!serialization.TryCustomCopy<TimeSpan>(this.SuccessCooldown, ref target3, hookCtx, false, context))
      target3 = serialization.CreateCopy<TimeSpan>(this.SuccessCooldown, hookCtx, context);
    target.SuccessCooldown = target3;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public void Copy(
    ref XenoResinSurgeActionComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref Component target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    XenoResinSurgeActionComponent target1 = (XenoResinSurgeActionComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (Component) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref object target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    XenoResinSurgeActionComponent target1 = (XenoResinSurgeActionComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (object) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void InternalCopy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    XenoResinSurgeActionComponent target1 = (XenoResinSurgeActionComponent) target;
    this.Copy(ref target1, serialization, hookCtx, context);
    target = (IComponent) target1;
  }

  [Obsolete("Use ISerializationManager.CopyTo instead")]
  public override void Copy(
    ref IComponent target,
    ISerializationManager serialization,
    SerializationHookContext hookCtx,
    ISerializationContext? context = null)
  {
    this.InternalCopy(ref target, serialization, hookCtx, context);
  }

  [PreserveBaseOverrides]
  [Obsolete("Use ISerializationManager.CreateCopy instead")]
  virtual XenoResinSurgeActionComponent Component.Instantiate()
  {
    return new XenoResinSurgeActionComponent();
  }

  [NetSerializable]
  [EditorBrowsable(EditorBrowsableState.Never)]
  [Serializable]
  public sealed class XenoResinSurgeActionComponent_AutoState : IComponentState
  {
    public float FailCooldownMult;
    public TimeSpan SuccessCooldown;
  }

  [RobustAutoGenerated]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public sealed class XenoResinSurgeActionComponent_AutoNetworkSystem : EntitySystem
  {
    public override void Initialize()
    {
      this.SubscribeLocalEvent<XenoResinSurgeActionComponent, ComponentGetState>(new ComponentEventRefHandler<XenoResinSurgeActionComponent, ComponentGetState>(this.OnGetState));
      this.SubscribeLocalEvent<XenoResinSurgeActionComponent, ComponentHandleState>(new ComponentEventRefHandler<XenoResinSurgeActionComponent, ComponentHandleState>(this.OnHandleState));
    }

    private void OnGetState(
      EntityUid uid,
      XenoResinSurgeActionComponent component,
      ref ComponentGetState args)
    {
      args.State = (IComponentState) new XenoResinSurgeActionComponent.XenoResinSurgeActionComponent_AutoState()
      {
        FailCooldownMult = component.FailCooldownMult,
        SuccessCooldown = component.SuccessCooldown
      };
    }

    private void OnHandleState(
      EntityUid uid,
      XenoResinSurgeActionComponent component,
      ref ComponentHandleState args)
    {
      if (!(args.Current is XenoResinSurgeActionComponent.XenoResinSurgeActionComponent_AutoState current))
        return;
      component.FailCooldownMult = current.FailCooldownMult;
      component.SuccessCooldown = current.SuccessCooldown;
    }
  }
}
